export const CLINICAL_PROTOCOLS = [
  {
    id: '1',
    title: 'Anti-inflamatório / BDNF',
    category: 'Anti-inflamatório',
    form: 'Cápsulas',
    posology: '1 dose/dia',
    content:
      'Omega 3 1000mg (36EPA/24DHA)\nOmega 3 1000mg (50DHA/20EPA)\nPiperina 5mg\nCúrcuma Longa 250mg\nBoswellia Serrata 200mg\nCrocus Sativus 50mg',
  },
  {
    id: '2',
    title: 'Probiótico Adulto (7 Cepas)',
    category: 'Probióticos',
    form: 'DR CAPS',
    posology: '1 cap à noite',
    content:
      'L. Helveticus 1BLH\nL. Plantarum 1BLH\nL. Paracasei 1BLH\nL. Reuteri 1BLH\nB. Longum 1BLH\nB. Infantis 1BLH\nS. Thermophilus 1BLH',
  },
  {
    id: '3',
    title: 'Probiótico Infantil (6 Cepas)',
    category: 'Probióticos',
    form: 'Conisnap',
    posology: '1 sachê/dia',
    content:
      'L. Rhamnosus 1BLH\nL. Acidophilus 1BLH\nB. Bifidum 1BLH\nB. Infantis 1BLH\nL. Reuteri 1BLH\nS. Boulardii 1BLH\nInulina 50mg',
  },
  {
    id: '4',
    title: 'Indutor do Sono Padrão',
    category: 'Sono',
    form: 'Cápsulas',
    posology: '1 dose 1h antes de dormir',
    content: 'Magnesio L Treonato 200mg\nL Triptofano 200mg\nPiridoxina 10mg',
  },
  {
    id: '5',
    title: 'Modulação de GABA Ansiedade',
    category: 'Sono',
    form: 'Cápsulas',
    posology: '1 dose à noite',
    content: 'GABA 200mg\nL Theanina 150mg\nMagnesio L Treonato 150mg',
  },
  {
    id: '6',
    title: 'Cronobiologia Noturna',
    category: 'Sono',
    form: 'Cápsulas',
    posology: '1 dose às 21h',
    content: 'Melatonina 0.21mg\n5-HTP 50mg\nPiridoxina 15mg',
  },
  {
    id: '7',
    title: 'Complexo Fitoterápico Noturno',
    category: 'Sono',
    form: 'Cápsulas',
    posology: '1 dose ao deitar',
    content: 'Valeriana 100mg\nMelissa 150mg\nL Triptofano 100mg',
  },
  {
    id: '8',
    title: 'Absorção Rápida Relaxante',
    category: 'Sono',
    form: 'Sublingual',
    posology: '1 tablete antes de dormir',
    content: 'Melatonina 0.21mg\nGABA 50mg\nL Theanina 50mg',
  },
  {
    id: '9',
    title: 'Xarope Calmante Infantil',
    category: 'Sono',
    form: 'Xarope',
    posology: '5ml à noite',
    content: 'Matricaria Chamomilla 5%\nPassiflora Incarnata 5%\nXarope base qsp 100ml',
  },
  {
    id: '10',
    title: 'Tintura Ansiedade Aguda',
    category: 'Sono',
    form: 'Tintura',
    posology: '20 gotas em água',
    content: 'Erythrina Mulungu 10%\nPassiflora Incarnata 10%\nÁlcool 30% qsp',
  },
  {
    id: '11',
    title: 'Gotas de Relaxamento',
    category: 'Sono',
    form: 'Tintura',
    posology: '10 gotas/dia',
    content: 'Matricaria Chamomilla 10%\nL Theanina 50mg/ml',
  },
  {
    id: '12',
    title: 'Xarope Mulungu',
    category: 'Sono',
    form: 'Xarope',
    posology: '10ml SOS',
    content: 'Erythrina Mulungu 10%\nMatricaria Chamomilla 5%',
  },
  {
    id: '13',
    title: 'SNC Fase Inicial',
    category: 'Estresse/Ansiedade/Depressão',
    form: 'Cápsulas',
    posology: '1 dose cedo',
    content: 'Rhodiola Rosea 200mg\nAshwagandha 300mg\nL Tirosina 200mg\nComplexo B 50mg',
  },
  {
    id: '14',
    title: 'SNC Manutenção',
    category: 'Estresse/Ansiedade/Depressão',
    form: 'Cápsulas',
    posology: '1 dose cedo',
    content: 'Panax Ginseng 200mg\nComplexo B (B1, B3, B6) 50mg\nVitamina C 200mg',
  },
  {
    id: '15',
    title: 'SNC Sexo Masculino',
    category: 'Estresse/Ansiedade/Depressão',
    form: 'Cápsulas',
    posology: '1 dose/dia',
    content: 'Maca Peruana 300mg\nTribulus Terrestris 200mg\nZinco 20mg\n(Sem 5-HTP)',
  },
  {
    id: '16',
    title: 'SNC Resiliência Total',
    category: 'Estresse/Ansiedade/Depressão',
    form: 'Cápsulas',
    posology: '1 dose/dia',
    content: 'L Theanina 200mg\nMagnésio Dimalato 200mg\nRelora 150mg',
  },
  {
    id: '17',
    title: 'Modulação de Euforia e Humor',
    category: 'Estresse/Ansiedade/Depressão',
    form: 'Cápsulas',
    posology: '1 dose/dia',
    content: 'Coenzima Q10 75mg\n5-HTP 100mg\nVitamina B6 15mg',
  },
  {
    id: '18',
    title: 'Regulação de Humor',
    category: 'Cognição/Memória',
    form: 'Cápsulas',
    posology: '1 dose pela manhã',
    content: 'Rhodiola Rosea 150mg\nRelora 100mg',
  },
  {
    id: '19',
    title: 'Concentração Intensa',
    category: 'Cognição/Memória',
    form: 'Cápsulas',
    posology: '1 dose cedo',
    content: 'Synapsa (Bacopa monnieri) 320mg\nL Tirosina 100mg',
  },
  {
    id: '20',
    title: 'Performance Mental',
    category: 'Cognição/Memória',
    form: 'Cápsulas',
    posology: '1 dose cedo',
    content: 'Green Tea Extrato 250mg\nCafeína 50mg\nL Theanina 100mg',
  },
  {
    id: '21',
    title: 'Fixação de Memória',
    category: 'Cognição/Memória',
    form: 'Cápsulas',
    posology: '1 dose no almoço',
    content: 'Fosfatidilserina 100mg\nSaffrin 15mg\nZinco 10mg',
  },
  {
    id: '22',
    title: 'Combate à Fadiga Mental',
    category: 'Cognição/Memória',
    form: 'Cápsulas',
    posology: '1 dose pela manhã',
    content: 'Serenzo 250mg\nCoenzima Q10 50mg\nNADH 5mg',
  },
  {
    id: '23',
    title: 'Cognitive Booster Estrutural',
    category: 'Cognição/Memória',
    form: 'Sachê',
    posology: '1 sachê/dia',
    content: 'Magnesio L Treonato 1g\nTaurina 500mg\nInositol 1g',
  },
  {
    id: '24',
    title: 'Foco Executivo Avançado',
    category: 'Cognição/Memória',
    form: 'Cápsulas',
    posology: '1 dose/dia',
    content: 'Citicolina 150mg\nL Tirosina 300mg',
  },
  {
    id: '25',
    title: 'Oxigenação Cerebral',
    category: 'Cognição/Memória',
    form: 'Cápsulas',
    posology: '1 dose/dia',
    content: 'Ginkgo Biloba 80mg\nVinpocetina 10mg',
  },
  {
    id: '26',
    title: 'Neuroproteção Antioxidante',
    category: 'Cognição/Memória',
    form: 'Cápsulas',
    posology: '1 dose/dia',
    content: 'Resveratrol 50mg\nAstaxantina 30mg',
  },
  {
    id: '27',
    title: 'Clareza Mental Rápida',
    category: 'Cognição/Memória',
    form: 'Cápsulas',
    posology: '1 dose/dia',
    content: 'Huperzine A 100mcg\nAlpha GPC 100mg',
  },
  {
    id: '28',
    title: 'Metilação B-Complex',
    category: 'SNC/Vitaminas',
    form: 'Cápsulas',
    posology: '1 dose/dia',
    content: 'Metilfolato 400mcg\nMetilcobalamina 500mcg',
  },
  {
    id: '29',
    title: 'Aporte Intenso de Colina',
    category: 'SNC/Vitaminas',
    form: 'Cápsulas',
    posology: '1 dose/dia',
    content: 'Bitartarato de Colina 300mg\nVitamina B5 50mg',
  },
  {
    id: '30',
    title: 'Bases Neurais Primárias',
    category: 'SNC/Vitaminas',
    form: 'Cápsulas',
    posology: '1 dose/dia',
    content: 'Vitamina B1 50mg\nVitamina B5 50mg\nVitamina B6 20mg',
  },
  {
    id: '31',
    title: 'Suporte Estabilizador Lítio',
    category: 'SNC/Vitaminas',
    form: 'Cápsulas',
    posology: '1 dose/dia',
    content: 'Orotato de Lítio 5mg\nInositol 200mg',
  },
  {
    id: '32',
    title: 'Energia Celular Mitocondrial',
    category: 'SNC/Vitaminas',
    form: 'Cápsulas',
    posology: '1 dose/dia',
    content: 'PQQ 10mg\nNADH 10mg\nL-Carnitina 200mg',
  },
  {
    id: '33',
    title: 'Neuro Gênese Avançada',
    category: 'SNC/Vitaminas',
    form: 'Cápsulas',
    posology: '1 dose/dia',
    content: 'Lion Mane (Juba de Leão) 500mg\nFosfatidilcolina 100mg',
  },
  {
    id: '34',
    title: 'Crise Aguda de Enxaqueca',
    category: 'Enxaqueca',
    form: 'Cápsulas',
    posology: '1 dose SOS',
    content: 'Vit B2 (Riboflavina) 400mg\nMagnesio Quelato 300mg\nCQ10 150mg',
  },
  {
    id: '35',
    title: 'Profilaxia e Manutenção',
    category: 'Enxaqueca',
    form: 'Cápsulas',
    posology: '1 dose/dia',
    content: 'Vit B2 200mg\nMagnesio Quelato 150mg\nCQ10 50mg\nFeverfew 50mg',
  },
  {
    id: '36',
    title: 'Modulação Nasal Olfativa',
    category: 'SNC/Vitaminas',
    form: 'Spray Nasal',
    posology: '1 jato em cada narina',
    content: 'Pinetonina 30%\nSoro Fisiológico qsp 30ml',
  },
  {
    id: '37',
    title: 'Complexo Imune Total',
    category: 'Imunidade',
    form: 'Cápsulas',
    posology: '1 dose/dia',
    content:
      'Vit D3 2000UI\nCQ10 50mg\nVit C 500mg\nZinco 15mg\nCobre 1mg\nLisina 300mg\nQuercetina 200mg\nSpirulina 200mg\nCúrcuma 150mg',
  },
]

export const PROTOCOL_CATEGORIES = [
  'Anti-inflamatório',
  'Probióticos',
  'Sono',
  'SNC/Vitaminas',
  'Estresse/Ansiedade/Depressão',
  'Cognição/Memória',
  'Enxaqueca',
  'Imunidade',
]

export const CLINICAL_REFERENCE = {
  neuroinflammation:
    'A neuroinflamação crônica de baixo grau desvia o metabolismo do triptofano para a via da quinurenina, reduzindo a síntese de serotonina e melatonina. Além disso, impacta negativamente a dopamina e a noradrenalina, gerando quadros clínicos de fadiga crônica, névoa mental e anedonia.',
  bdnf: 'O Fator Neurotrófico Derivado do Cérebro (BDNF) é uma proteína essencial para a sobrevivência neuronal, plasticidade sináptica e neurogênese no hipocampo. Níveis reduzidos estão intimamente associados ao declínio cognitivo e à depressão. Intervenções ricas em ômega-3, exercícios físicos e polifenóis (como a cúrcuma) são moduladores positivos.',
  gutBrain:
    'O eixo intestino-cérebro (Gut-Brain Axis) comunica-se bi-direcionalmente via nervo vago e metabólitos microbianos. Uma flora intestinal saudável (eubiose) é precursora vital de neurotransmissores como GABA e serotonina. A disbiose sistêmica altera a permeabilidade da barreira hematoencefálica, promovendo neuroinflamação reativa.',
  neurotransmitters: [
    { target: 'Serotonina', supplements: '5-HTP, Complexo B (B6, B9, B12), Magnésio' },
    { target: 'Noradrenalina', supplements: 'Tirosina, Complexo B, Vitamina C' },
    { target: 'GABA', supplements: 'Magnésio (Treonato, Taurato), Vitamina B6, L-Theanina' },
    { target: 'Melatonina', supplements: '5-HTP, Complexo B, Ômega 3, Magnésio' },
  ],
}
