export const MATRIX_DOMAINS = [
  {
    id: 'd1',
    name: 'Sistema de Ameaça',
    circuits: 'amígdala, insula, salience network',
    states: [
      { id: 1, name: 'vigilância adaptativa' },
      { id: 2, name: 'hipervigilância' },
      { id: 3, name: 'ansiedade antecipatória' },
      { id: 4, name: 'medo contextual' },
      { id: 5, name: 'resposta de congelamento' },
      { id: 6, name: 'resposta defensiva ativa' },
      { id: 7, name: 'ansiedade social' },
      { id: 8, name: 'paranoia adaptativa' },
      { id: 9, name: 'paranoia delirante' },
      { id: 10, name: 'trauma reativado' },
    ],
  },
  {
    id: 'd2',
    name: 'Sistema de Recompensa',
    circuits: 'estriado ventral, dopamina mesolímbica',
    states: [
      { id: 11, name: 'curiosidade exploratória' },
      { id: 12, name: 'motivação dirigida' },
      { id: 13, name: 'prazer hedônico' },
      { id: 14, name: 'prazer antecipatório' },
      { id: 15, name: 'estado de fluxo dopaminérgico' },
      { id: 16, name: 'recompensa condicionada' },
      { id: 17, name: 'compulsão' },
      { id: 18, name: 'anedonia parcial' },
      { id: 19, name: 'anedonia profunda' },
      { id: 20, name: 'dependência motivacional' },
    ],
  },
  {
    id: 'd3',
    name: 'Sistema Cognitivo Executivo',
    circuits: 'dorsolateral PFC, frontoparietal network',
    states: [
      { id: 21, name: 'foco sustentado' },
      { id: 22, name: 'foco seletivo' },
      { id: 23, name: 'memória de trabalho ativa' },
      { id: 24, name: 'raciocínio lógico' },
      { id: 25, name: 'flexibilidade cognitiva' },
      { id: 26, name: 'criatividade analítica' },
      { id: 27, name: 'fadiga executiva' },
      { id: 28, name: 'sobrecarga cognitiva' },
      { id: 29, name: 'rigidez cognitiva' },
      { id: 30, name: 'colapso executivo' },
    ],
  },
  {
    id: 'd4',
    name: 'Sistema de Consciência',
    circuits: 'Default Mode Network, global workspace',
    states: [
      { id: 31, name: 'consciência reflexiva' },
      { id: 32, name: 'consciência narrativa' },
      { id: 33, name: 'devaneio espontâneo' },
      { id: 34, name: 'imaginação construtiva' },
      { id: 35, name: 'insight criativo' },
      { id: 36, name: 'metacognição' },
      { id: 37, name: 'dissociação leve' },
      { id: 38, name: 'dissociação profunda' },
      { id: 39, name: 'consciência fragmentada' },
      { id: 40, name: 'integração global da consciência' },
    ],
  },
  {
    id: 'd5',
    name: 'Sistema Social',
    circuits: 'medial PFC, temporoparietal junction',
    states: [
      { id: 41, name: 'empatia emocional' },
      { id: 42, name: 'empatia cognitiva' },
      { id: 43, name: 'teoria da mente' },
      { id: 44, name: 'leitura emocional' },
      { id: 45, name: 'conexão social' },
      { id: 46, name: 'ansiedade social' },
      { id: 47, name: 'retraimento social' },
      { id: 48, name: 'isolamento social' },
      { id: 49, name: 'hipersensibilidade social' },
      { id: 50, name: 'alienação social' },
    ],
  },
  {
    id: 'd6',
    name: 'Sistema Regulatório',
    circuits: 'cingulado anterior, vmPFC',
    states: [
      { id: 51, name: 'equilíbrio emocional' },
      { id: 52, name: 'regulação cognitiva' },
      { id: 53, name: 'tolerância ao estresse' },
      { id: 54, name: 'resiliência adaptativa' },
      { id: 55, name: 'ruminação' },
      { id: 56, name: 'instabilidade emocional' },
      { id: 57, name: 'impulsividade' },
      { id: 58, name: 'explosividade emocional' },
      { id: 59, name: 'desregulação afetiva' },
      { id: 60, name: 'colapso regulatório' },
    ],
  },
  {
    id: 'd7',
    name: 'Sistema de Energia Neural',
    circuits: 'hipotálamo, locus coeruleus, sistema reticular',
    states: [
      { id: 61, name: 'alerta energético' },
      { id: 62, name: 'alerta sustentado' },
      { id: 63, name: 'fadiga neural' },
      { id: 64, name: 'exaustão mental' },
      { id: 65, name: 'burnout neurocognitivo' },
      { id: 66, name: 'hiperexcitação' },
      { id: 67, name: 'hipovigilância' },
      { id: 68, name: 'sonolência cognitiva' },
      { id: 69, name: 'instabilidade energética' },
      { id: 70, name: 'colapso energético' },
    ],
  },
  {
    id: 'd8',
    name: 'Sistema Integrativo',
    circuits: 'Triple Network',
    states: [
      { id: 71, name: 'integração adaptativa' },
      { id: 72, name: 'sincronização global' },
      { id: 73, name: 'criatividade sistêmica' },
      { id: 74, name: 'pensamento sistêmico' },
      { id: 75, name: 'estado de fluxo profundo' },
      { id: 76, name: 'desintegração parcial' },
      { id: 77, name: 'conflito de redes' },
      { id: 78, name: 'desorganização cognitiva' },
      { id: 79, name: 'fragmentação funcional' },
      { id: 80, name: 'colapso integrativo' },
    ],
  },
]
