export type CommandCenterStage = 'integration_draft' | 'trail_mapping' | 'navigation_ready' | 'demo_ready' | 'institutional_review' | 'release_candidate_preparation' | 'blocked'
export type CommandCenterDecision = 'continue' | 'refine' | 'pause' | 'prepare_release_candidate' | 'escalate_human_review' | 'not_ready'
export type CommandCenterAudienceType = 'internal_governance' | 'prefeitura_simulada' | 'clinica_simulada' | 'parceiro_agro_bio_simulado' | 'investidor_simulado' | 'juridico_simulado' | 'scientific_review_simulado' | 'regulatory_review_simulado'
export type CommandCenterVersionStatus = 'frozen' | 'active' | 'planned' | 'blocked' | 'legacy'
export type CommandCenterGuardrailStatus = 'compliant' | 'attention' | 'blocked'

export interface CommandCenterGuardrails { simulated_only: true; metadata_only: true; human_review_required: true; command_center_only: true; demo_preparation_only: true; contains_clinical_data: false; contains_patient_data: false; contains_personal_sensitive_data: false; real_operation_claim: false; real_pilot_claim: false; real_client_claim: false; real_contract_claim: false; real_partnership_claim: false; real_billing_claim: false; real_crm_claim: false; real_email_automation_claim: false; real_biological_sample_claim: false; real_eeg_claim: false; real_qeeg_claim: false; real_biomarker_claim: false; legal_signature_claim: false; diagnostic_truth_certification_claim: false; scientific_validation_claim: false; regulatory_validation_claim: false; external_certification_claim: false; treatment_claim: false; outcome_guarantee_claim: false; public_health_claim: false }
export interface SenseTrustCommandCenter extends CommandCenterGuardrails { commandCenterId: string; title: string; linkedV41HandoffRoomId: string; linkedV40CloseoutRoomId: string; linkedV39MonitoringRoomId: string; linkedV38ExecutionGovernanceRoomId: string; linkedV37ProposalRoomId: string; linkedV12LeanFreezeReference: string; stage: CommandCenterStage; decision: CommandCenterDecision; commandCenterReadinessScore: number; trailCompletenessScore: number; demoReadinessScore: number; guardrailIntegrityScore: number; releaseCandidatePreparationScore: number; versionNodes: CommandCenterVersionNode[]; trailMap: CommandCenterTrailMap; navigationRoutes: CommandCenterNavigationRoute[]; proofChain: CommandCenterProofChain; readinessSnapshot: CommandCenterReadinessSnapshot; riskSnapshot: CommandCenterRiskSnapshot; guardrailSnapshot: CommandCenterGuardrailSnapshot; demoScenarios: CommandCenterDemoScenario[]; institutionalViews: CommandCenterInstitutionalView[]; audienceProfiles: CommandCenterAudienceProfile[]; handoffLinks: CommandCenterHandoffLink[]; releaseCandidatePreparation: CommandCenterReleaseCandidatePreparation; auditTrail: CommandCenterAuditTrail; executiveReport: CommandCenterExecutiveReport }
export interface CommandCenterVersionNode { id: string; version: string; label: string; route: string; status: CommandCenterVersionStatus; readinessScore: number; simulated_only: true; metadata_only: true }
export interface CommandCenterTrailMap { id: string; nodes: string[]; links: string[]; simulated_only: true; metadata_only: true }
export interface CommandCenterNavigationRoute { id: string; label: string; route: string; version: string; simulated_only: true; metadata_only: true }
export interface CommandCenterProofChain { id: string; steps: CommandCenterProofStep[]; simulated_only: true; metadata_only: true; human_review_required: true }
export interface CommandCenterProofStep { id: string; version: string; proofLabel: string; guardrailStatus: CommandCenterGuardrailStatus; simulated_only: true; metadata_only: true }
export interface CommandCenterReadinessSnapshot { id: string; commandCenterId: string; scores: number[]; summary: string; simulated_only: true; metadata_only: true }
export interface CommandCenterRiskSnapshot { id: string; commandCenterId: string; risks: string[]; simulated_only: true; metadata_only: true; human_review_required: true }
export interface CommandCenterGuardrailSnapshot { id: string; commandCenterId: string; status: CommandCenterGuardrailStatus; guardrails: string[]; simulated_only: true; metadata_only: true; human_review_required: true }
export interface CommandCenterDemoScenario { id: string; title: string; audienceType: CommandCenterAudienceType; no_real_submission: true; simulated_only: true; metadata_only: true }
export interface CommandCenterInstitutionalView { id: string; title: string; audienceType: CommandCenterAudienceType; narrative: string; simulated_only: true; metadata_only: true; demo_preparation_only: true }
export interface CommandCenterAudienceProfile { id: string; audienceType: CommandCenterAudienceType; reviewNeed: string; simulated_only: true; metadata_only: true; human_review_required: true }
export interface CommandCenterHandoffLink { id: string; label: string; route: string; linkedVersion: string; simulated_only: true; metadata_only: true }
export interface CommandCenterReleaseCandidatePreparation { id: string; targetVersion: 'v4.3'; readinessScore: number; blockers: string[]; simulated_only: true; metadata_only: true; human_review_required: true }
export interface CommandCenterAuditTrail { id: string; events: string[]; append_only_simulated: true; simulated_only: true; metadata_only: true }
export interface CommandCenterExecutiveReport { id: string; summary: string; decision: CommandCenterDecision; simulated_only: true; metadata_only: true; human_review_required: true; command_center_only: true; demo_preparation_only: true }
