export type DemoDistributionStage = 'draft' | 'material_preparation' | 'narrative_review' | 'guardrail_review' | 'demo_ready' | 'distribution_ready' | 'blocked' | 'archived'
export type DemoDistributionDecision = 'continue' | 'refine' | 'pause' | 'demo_ready' | 'distribution_ready' | 'not_ready' | 'escalate_human_review' | 'block_distribution'
export type PartnerPresentationAudienceType = 'internal_governance' | 'prefeitura_simulada' | 'clinica_simulada' | 'parceiro_agro_bio_simulado' | 'investidor_simulado' | 'juridico_simulado' | 'scientific_review_simulado' | 'regulatory_review_simulado'
export type PartnerPresentationMaterialType = 'executive_one_pager' | 'demo_script' | 'deck_outline' | 'route_map' | 'claims_matrix' | 'risk_disclosure' | 'follow_up_template_simulado' | 'institutional_brief'
export type PartnerPresentationClaimStatus = 'approved' | 'requires_review' | 'prohibited'
export interface DemoDistributionGuardrails { simulated_only: true; metadata_only: true; human_review_required: true; demo_distribution_only: true; partner_presentation_only: true; release_candidate_linked: true; contains_clinical_data: false; contains_patient_data: false; contains_personal_sensitive_data: false; real_operation_claim: false; real_pilot_claim: false; real_client_claim: false; real_contract_claim: false; real_partnership_claim: false; real_billing_claim: false; real_crm_claim: false; real_email_automation_claim: false; real_lead_collection_claim: false; real_analytics_claim: false; real_biological_sample_claim: false; real_eeg_claim: false; real_qeeg_claim: false; real_biomarker_claim: false; legal_signature_claim: false; diagnostic_truth_certification_claim: false; scientific_validation_claim: false; regulatory_validation_claim: false; external_certification_claim: false; treatment_claim: false; outcome_guarantee_claim: false; public_health_claim: false; binding_proposal_claim: false; commercial_commitment_claim: false; legal_commitment_claim: false }
export interface SenseTrustDemoDistributionPartnerPresentationKit extends DemoDistributionGuardrails { kitId: string; title: string; linkedV43PilotOSReleaseCandidateId: string; linkedV42CommandCenterId: string; linkedV41HandoffRoomId: string; linkedV40CloseoutRoomId: string; linkedV39MonitoringRoomId: string; linkedV38ExecutionGovernanceRoomId: string; linkedV37ProposalRoomId: string; linkedV12LeanFreezeReference: string; stage: DemoDistributionStage; decision: DemoDistributionDecision; demoDistributionReadinessScore: number; partnerPresentationReadinessScore: number; claimsSafetyScore: number; materialCompletenessScore: number; humanReviewCompletenessScore: number; demoDistributionScenarios: DemoDistributionScenario[]; audienceProfiles: PartnerPresentationAudienceProfile[]; narrativeTracks: PartnerPresentationNarrativeTrack[]; presentationPackages: PartnerPresentationPackage[]; materials: PartnerPresentationMaterial[]; onePagers: PartnerPresentationOnePager[]; deckOutlines: PartnerPresentationDeckOutline[]; demoScripts: PartnerPresentationDemoScript[]; routeMaps: PartnerPresentationRouteMap[]; authorizedClaims: PartnerPresentationAuthorizedClaim[]; prohibitedClaims: PartnerPresentationProhibitedClaim[]; preMeetingChecklists: PartnerPresentationPreMeetingChecklist[]; postMeetingChecklists: PartnerPresentationPostMeetingChecklist[]; distributionLogs: PartnerPresentationDistributionLog[]; riskRegister: PartnerPresentationRiskRegister; humanReviewQueue: PartnerPresentationHumanReviewQueue; auditTrail: PartnerPresentationAuditTrail; executiveReport: PartnerPresentationExecutiveReport }
export interface DemoDistributionScenario { id: string; title: string; audienceType: PartnerPresentationAudienceType; no_real_distribution: true; simulated_only: true; metadata_only: true }
export interface PartnerPresentationAudienceProfile { id: string; audienceType: PartnerPresentationAudienceType; label: string; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PartnerPresentationNarrativeTrack { id: string; title: string; narrative: string; simulated_only: true; metadata_only: true }
export interface PartnerPresentationPackage { id: string; title: string; audienceType: PartnerPresentationAudienceType; packageScore: number; simulated_only: true; metadata_only: true; partner_presentation_only: true }
export interface PartnerPresentationMaterial { id: string; title: string; materialType: PartnerPresentationMaterialType; no_real_submission: true; simulated_only: true; metadata_only: true }
export interface PartnerPresentationOnePager { id: string; title: string; bullets: string[]; simulated_only: true; metadata_only: true }
export interface PartnerPresentationDeckOutline { id: string; title: string; sections: string[]; simulated_only: true; metadata_only: true }
export interface PartnerPresentationDemoScript { id: string; title: string; steps: string[]; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PartnerPresentationRouteMap { id: string; routes: string[]; releaseCandidateRoute: string; simulated_only: true; metadata_only: true; release_candidate_linked: true }
export interface PartnerPresentationAuthorizedClaim { id: string; claim: string; status: PartnerPresentationClaimStatus; simulated_only: true; metadata_only: true }
export interface PartnerPresentationProhibitedClaim { id: string; claim: string; status: PartnerPresentationClaimStatus; simulated_only: true; metadata_only: true }
export interface PartnerPresentationPreMeetingChecklist { id: string; items: string[]; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PartnerPresentationPostMeetingChecklist { id: string; items: string[]; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PartnerPresentationDistributionLog { id: string; events: string[]; no_real_email: true; no_real_crm: true; no_real_lead_collection: true; simulated_only: true; metadata_only: true }
export interface PartnerPresentationRiskRegister { id: string; risks: string[]; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PartnerPresentationHumanReviewQueue { id: string; items: string[]; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PartnerPresentationAuditTrail { id: string; events: string[]; append_only_simulated: true; simulated_only: true; metadata_only: true }
export interface PartnerPresentationExecutiveReport { id: string; summary: string; decision: DemoDistributionDecision; simulated_only: true; metadata_only: true; human_review_required: true; demo_distribution_only: true; partner_presentation_only: true; release_candidate_linked: true }
