export type InstitutionalHandoffStage = 'draft' | 'package_preparation' | 'evidence_review' | 'stakeholder_review' | 'legal_review_required' | 'human_review_required' | 'handoff_ready' | 'handoff_blocked' | 'archive_ready'
export type InstitutionalHandoffDecision = 'prepare' | 'pause' | 'refine' | 'block' | 'handoff_ready' | 'not_ready' | 'escalate_human_review'
export type InstitutionalHandoffRecipientType = 'prefeitura_simulada' | 'clinica_simulada' | 'parceiro_agro_bio_simulado' | 'investidor_simulado' | 'juridico_simulado' | 'comite_interno_simulado'

export interface InstitutionalHandoffGuardrails { simulated_only: true; metadata_only: true; human_review_required: true; handoff_preparation_only: true; contains_clinical_data: false; contains_patient_data: false; contains_personal_sensitive_data: false; real_operation_claim: false; real_clinical_operation_claim: false; real_client_claim: false; real_contract_claim: false; real_partnership_claim: false; real_billing_claim: false; real_crm_claim: false; real_email_automation_claim: false; real_biological_sample_claim: false; real_eeg_claim: false; real_qeeg_claim: false; real_biomarker_claim: false; legal_signature_claim: false; diagnostic_truth_certification_claim: false; scientific_validation_claim: false; regulatory_validation_claim: false; outcome_guarantee_claim: false }
export interface SenseTrustInstitutionalHandoffRoom extends InstitutionalHandoffGuardrails { roomId: string; simulatedOrganizationName: string; linkedV40CloseoutRoomId: string; linkedV39MonitoringRoomId: string; linkedV38ExecutionGovernanceRoomId: string; linkedV37ProposalRoomId: string; linkedV12LeanFreezeReference: string; handoffStage: InstitutionalHandoffStage; handoffDecision: InstitutionalHandoffDecision; handoffReadinessScore: number; packageCompletenessScore: number; evidenceBundleScore: number; riskClearanceScore: number; humanReviewCompletenessScore: number }
export interface InstitutionalHandoffScenario extends SenseTrustInstitutionalHandoffRoom { packages: InstitutionalHandoffPackage[]; recipientProfiles: InstitutionalHandoffRecipientProfile[]; materials: InstitutionalHandoffMaterial[]; evidenceBundles: InstitutionalHandoffEvidenceBundle[]; responsibilityMatrix: InstitutionalHandoffResponsibilityMatrix; decisionRecords: InstitutionalHandoffDecisionRecord[]; reviewQueue: InstitutionalHandoffReviewQueue; riskRegister: InstitutionalHandoffRiskRegister; boundaryClaimsGuardrails: InstitutionalHandoffBoundaryClaimsGuardrail[]; auditTrail: InstitutionalHandoffAuditTrail; executiveReport: InstitutionalHandoffExecutiveReport }
export interface InstitutionalHandoffState extends InstitutionalHandoffGuardrails { version: 'v4.1'; rooms: SenseTrustInstitutionalHandoffRoom[]; scenarios: InstitutionalHandoffScenario[]; packages: InstitutionalHandoffPackage[]; recipientProfiles: InstitutionalHandoffRecipientProfile[]; materials: InstitutionalHandoffMaterial[]; evidenceBundles: InstitutionalHandoffEvidenceBundle[]; responsibilityMatrices: InstitutionalHandoffResponsibilityMatrix[]; decisionRecords: InstitutionalHandoffDecisionRecord[]; reviewQueues: InstitutionalHandoffReviewQueue[]; riskRegisters: InstitutionalHandoffRiskRegister[]; boundaryClaimsGuardrails: InstitutionalHandoffBoundaryClaimsGuardrail[]; auditTrails: InstitutionalHandoffAuditTrail[]; executiveReports: InstitutionalHandoffExecutiveReport[] }
export interface InstitutionalHandoffPackage { id: string; roomId: string; title: string; completenessScore: number; simulated_only: true; metadata_only: true; handoff_preparation_only: true }
export interface InstitutionalHandoffRecipientProfile { id: string; roomId: string; recipientType: InstitutionalHandoffRecipientType; label: string; reviewNeed: string; simulated_only: true; metadata_only: true; human_review_required: true }
export interface InstitutionalHandoffMaterial { id: string; roomId: string; title: string; materialType: string; no_real_submission: true; simulated_only: true; metadata_only: true }
export interface InstitutionalHandoffEvidenceBundle { id: string; roomId: string; title: string; evidenceScore: number; no_clinical_data: true; simulated_only: true; metadata_only: true }
export interface InstitutionalHandoffResponsibilityMatrix { id: string; roomId: string; responsibilities: string[]; simulated_only: true; metadata_only: true; human_review_required: true }
export interface InstitutionalHandoffDecisionRecord { id: string; roomId: string; decision: InstitutionalHandoffDecision; rationale: string; simulated_only: true; metadata_only: true; human_review_required: true }
export interface InstitutionalHandoffReviewQueue { id: string; roomId: string; reviewItems: string[]; simulated_only: true; metadata_only: true; human_review_required: true }
export interface InstitutionalHandoffRiskRegister { id: string; roomId: string; risks: string[]; simulated_only: true; metadata_only: true; human_review_required: true }
export interface InstitutionalHandoffBoundaryClaimsGuardrail { id: string; roomId: string; boundary: string; compliant: true; simulated_only: true; metadata_only: true; human_review_required: true }
export interface InstitutionalHandoffAuditTrail { id: string; roomId: string; events: string[]; append_only_simulated: true; simulated_only: true; metadata_only: true }
export interface InstitutionalHandoffExecutiveReport { id: string; roomId: string; summary: string; handoffDecision: InstitutionalHandoffDecision; simulated_only: true; metadata_only: true; human_review_required: true; handoff_preparation_only: true }
