export type SenseTrustScaleGateStatusType = 'draft' | 'ready_for_review' | 'readiness_reviewed' | 'scale_candidate' | 'refine_required' | 'paused' | 'blocked' | 'revoked_simulated'
export type SenseTrustScaleDecisionType = 'go' | 'pause' | 'refine' | 'scale' | 'block' | 'require_legal_review' | 'require_regulatory_review' | 'require_human_review'
export type SenseTrustMarketSegmentType = 'clinical_private' | 'public_health' | 'education' | 'legal_partner' | 'corporate_health' | 'government' | 'research' | 'investor_partner' | 'internal_operation'
export type SenseTrustReadinessLevel = 'initial' | 'emerging' | 'structured' | 'governed' | 'scale_candidate' | 'scale_ready_simulated'
export type SenseTrustStrategicRiskLevel = 'low' | 'medium' | 'high' | 'critical'

export interface SenseTrustScaleDecision { decision_id: string; scale_gate_id: string; decision_type: SenseTrustScaleDecisionType; decision_reason: string; required_reviews: string[]; blocked_actions: string[]; next_action: string; decision_hash: string; previous_decision_hash: string | null; timestamp_simulated: string; metadata_only: true; legal_decision_claim: false; regulatory_authorization_claim: false; commercial_commitment_claim: false; simulated_only: true }
export interface SenseTrustScaleDecisionBoard { board_id: string; scale_gate_id: string; decisions: SenseTrustScaleDecision[]; recommended_decision: SenseTrustScaleDecisionType; metadata_only: true; simulated_only: true }
export interface SenseTrustMarketPriorityItem { item_id: string; segment: SenseTrustMarketSegmentType; priority_score: number; rationale: string; risk_level: SenseTrustStrategicRiskLevel; simulated_only: true }
export interface SenseTrustMarketPrioritizationMatrix { matrix_id: string; items: SenseTrustMarketPriorityItem[]; top_segment: SenseTrustMarketSegmentType; metadata_only: true; simulated_only: true }
export interface SenseTrustRegulatoryReadinessItem { item_id: string; area: string; readiness_score: number; risk_level: SenseTrustStrategicRiskLevel; pending_action: string; simulated_only: true }
export interface SenseTrustRegulatoryReadinessMap { map_id: string; items: SenseTrustRegulatoryReadinessItem[]; readiness_score: number; metadata_only: true; simulated_only: true }
export interface SenseTrustInstitutionalRiskGovernanceMap { map_id: string; risk_score: number; risk_level: SenseTrustStrategicRiskLevel; mitigations: string[]; metadata_only: true; simulated_only: true }
export interface SenseTrustScaleCandidateScore { score_id: string; score: number; readiness_level: SenseTrustReadinessLevel; recommendation: SenseTrustScaleDecisionType; simulated_only: true }
export interface SenseTrustStrategicRoadmapItem { item_id: string; roadmap_id: string; title: string; action: string; priority: SenseTrustStrategicRiskLevel; owner_role: string; simulated_only: true }
export interface SenseTrustV3StrategicRoadmap { roadmap_id: string; items: SenseTrustStrategicRoadmapItem[]; roadmap_status: SenseTrustScaleGateStatusType; metadata_only: true; simulated_only: true }
export interface SenseTrustStrategicPartnerFitMatrix { matrix_id: string; segment: SenseTrustMarketSegmentType; fit_score: number; fit_rationale: string; partnership_claim: false; simulated_only: true }
export interface SenseTrustGovernanceToScaleAuditTrailItem { audit_id: string; scale_gate_id: string; action: SenseTrustScaleDecisionType; previous_status: SenseTrustScaleGateStatusType; new_status: SenseTrustScaleGateStatusType; logical_hash: string; timestamp_simulated: string; simulated_actor: string; metadata_only: true }
export interface SenseTrustStrategicScaleMisuseBlocker { blocker_id: string; blocked_misuse: string; risk: SenseTrustStrategicRiskLevel; blocked_action: string; safe_language: string; simulated_only: true }
export interface SenseTrustInstitutionalReadinessExecutiveReport { report_id: string; executive_summary: string; recommended_decision: SenseTrustScaleDecisionType; readiness_summary: string; market_summary: string; regulatory_summary: string; risk_summary: string; recommendation: string; simulated_only: true }
export interface SenseTrustInstitutionalScaleGateValidationResult { valid: boolean; errors: string[] }

export interface SenseTrustInstitutionalReadinessGate {
  readiness_gate_id: string; closeout_id: string; pilot_id: string; certificate_id: string; evidence_vault_id: string; learning_loop_id: string; readiness_title: string; readiness_status: SenseTrustScaleGateStatusType; readiness_level: SenseTrustReadinessLevel; maturity_score: number; v3_readiness_score: number; regulatory_readiness_score: number; market_priority_score: number; institutional_risk_score: number; recommended_decision: SenseTrustScaleDecisionType; required_reviews: string[]; blocked_actions: string[]; metadata_only: true; contains_clinical_data: false; contains_patient_data: false; contains_personal_sensitive_data: false; real_clinical_operation_claim: false; contract_binding_claim: false; client_claim: false; partnership_claim: false; regulatory_validation_claim: false; diagnostic_truth_certification_claim: false; simulated_only: true
}

export interface SenseTrustStrategicScaleGate {
  scale_gate_id: string; readiness_gate_id: string; strategic_title: string; decision_board_id: string; market_prioritization_matrix_id: string; regulatory_readiness_map_id: string; institutional_risk_governance_map_id: string; strategic_partner_fit_matrix_id: string; v3_strategic_roadmap_id: string; scale_candidate_score: SenseTrustScaleCandidateScore; scale_decision: SenseTrustScaleDecisionType; next_action: string; scale_blockers: string[]; logical_scale_gate_hash: string; previous_scale_gate_hash: string | null; metadata_only: true; simulated_only: true
}

export interface SenseTrustInstitutionalReadinessScaleGateState { state_id: string; version: 'v3.0'; readiness_gates: SenseTrustInstitutionalReadinessGate[]; strategic_scale_gates: SenseTrustStrategicScaleGate[]; scale_decision_boards: SenseTrustScaleDecisionBoard[]; scale_decisions: SenseTrustScaleDecision[]; market_prioritization_matrices: SenseTrustMarketPrioritizationMatrix[]; market_priority_items: SenseTrustMarketPriorityItem[]; regulatory_readiness_maps: SenseTrustRegulatoryReadinessMap[]; regulatory_readiness_items: SenseTrustRegulatoryReadinessItem[]; institutional_risk_governance_maps: SenseTrustInstitutionalRiskGovernanceMap[]; scale_candidate_scores: SenseTrustScaleCandidateScore[]; v3_strategic_roadmaps: SenseTrustV3StrategicRoadmap[]; strategic_roadmap_items: SenseTrustStrategicRoadmapItem[]; strategic_partner_fit_matrices: SenseTrustStrategicPartnerFitMatrix[]; governance_to_scale_audit_trail: SenseTrustGovernanceToScaleAuditTrailItem[]; strategic_scale_misuse_blockers: SenseTrustStrategicScaleMisuseBlocker[]; executive_reports: SenseTrustInstitutionalReadinessExecutiveReport[]; references: string[]; metadata_only: true; clinical_data_used: false; patient_data_used: false; personal_sensitive_data_used: false; real_clinical_operation_claimed: false; contract_binding_claimed: false; client_claim: false; partnership_claim: false; regulatory_validation_claim: false; diagnostic_truth_certification_claimed: false; real_revenue_claimed: false; real_billing_claimed: false; simulated_only: true }
export interface SenseTrustInstitutionalScaleGateExportPayload { schema: 'sensetrust.institutional_readiness_scale_gate_export.v1'; exported_at: string; state: SenseTrustInstitutionalReadinessScaleGateState; public_exposure: 'metadata_only'; simulated_only: true }
