export type PilotOSReleaseCandidateStage = 'draft' | 'hardening' | 'acceptance_review' | 'demo_readiness_review' | 'institutional_review' | 'release_candidate_ready' | 'blocked'
export type PilotOSReleaseCandidateDecision = 'continue' | 'refine' | 'pause' | 'release_candidate_ready' | 'not_ready' | 'escalate_human_review' | 'block_release'
export type PilotOSReleaseCandidateAudienceType = 'internal_governance' | 'prefeitura_simulada' | 'clinica_simulada' | 'parceiro_agro_bio_simulado' | 'investidor_simulado' | 'juridico_simulado' | 'scientific_review_simulado' | 'regulatory_review_simulado'
export type PilotOSReleaseCandidateGateStatus = 'pass' | 'attention' | 'blocked' | 'not_applicable'
export type PilotOSReleaseCandidateReadinessLevel = 'low' | 'moderate' | 'high' | 'release_candidate_ready'
export interface PilotOSReleaseCandidateGuardrails { simulated_only: true; metadata_only: true; human_review_required: true; release_candidate_only: true; demo_preparation_only: true; command_center_linked: true; contains_clinical_data: false; contains_patient_data: false; contains_personal_sensitive_data: false; real_operation_claim: false; real_pilot_claim: false; real_client_claim: false; real_contract_claim: false; real_partnership_claim: false; real_billing_claim: false; real_crm_claim: false; real_email_automation_claim: false; real_biological_sample_claim: false; real_eeg_claim: false; real_qeeg_claim: false; real_biomarker_claim: false; legal_signature_claim: false; diagnostic_truth_certification_claim: false; scientific_validation_claim: false; regulatory_validation_claim: false; external_certification_claim: false; treatment_claim: false; outcome_guarantee_claim: false; public_health_claim: false }
export interface SenseTrustPilotOSReleaseCandidate extends PilotOSReleaseCandidateGuardrails { releaseCandidateId: string; title: string; linkedV42CommandCenterId: string; linkedV41HandoffRoomId: string; linkedV40CloseoutRoomId: string; linkedV39MonitoringRoomId: string; linkedV38ExecutionGovernanceRoomId: string; linkedV37ProposalRoomId: string; linkedV12LeanFreezeReference: string; stage: PilotOSReleaseCandidateStage; decision: PilotOSReleaseCandidateDecision; pilotOSReadinessScore: number; acceptanceCriteriaScore: number; demoReadinessScore: number; guardrailIntegrityScore: number; institutionalPackageScore: number; releaseCandidateScore: number; versionMap: PilotOSReleaseCandidateVersionMap; acceptanceCriteria: PilotOSReleaseCandidateAcceptanceCriterion[]; readinessGates: PilotOSReleaseCandidateReadinessGate[]; demoFlows: PilotOSReleaseCandidateDemoFlow[]; navigationMap: PilotOSReleaseCandidateNavigationMap; proofChainSummary: PilotOSReleaseCandidateProofChainSummary; guardrailMatrix: PilotOSReleaseCandidateGuardrailMatrix; riskRegister: PilotOSReleaseCandidateRiskRegister; knownLimitations: PilotOSReleaseCandidateKnownLimitation[]; humanReviewQueue: PilotOSReleaseCandidateHumanReviewQueue; institutionalPackages: PilotOSReleaseCandidateInstitutionalPackage[]; executiveChecklist: PilotOSReleaseCandidateExecutiveChecklist; releaseDecision: PilotOSReleaseCandidateReleaseDecision; auditTrail: PilotOSReleaseCandidateAuditTrail; executiveReport: PilotOSReleaseCandidateExecutiveReport }
export interface PilotOSReleaseCandidateVersionMap { id: string; versions: string[]; commandCenterRoute: string; simulated_only: true; metadata_only: true }
export interface PilotOSReleaseCandidateAcceptanceCriterion { id: string; criterion: string; status: PilotOSReleaseCandidateGateStatus; simulated_only: true; metadata_only: true }
export interface PilotOSReleaseCandidateReadinessGate { id: string; gate: string; status: PilotOSReleaseCandidateGateStatus; level: PilotOSReleaseCandidateReadinessLevel; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PilotOSReleaseCandidateDemoFlow { id: string; title: string; audienceType: PilotOSReleaseCandidateAudienceType; no_real_submission: true; simulated_only: true; metadata_only: true }
export interface PilotOSReleaseCandidateNavigationMap { id: string; routes: string[]; simulated_only: true; metadata_only: true; command_center_linked: true }
export interface PilotOSReleaseCandidateProofChainSummary { id: string; summary: string; steps: string[]; simulated_only: true; metadata_only: true }
export interface PilotOSReleaseCandidateGuardrailMatrix { id: string; guardrails: string[]; status: PilotOSReleaseCandidateGateStatus; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PilotOSReleaseCandidateRiskRegister { id: string; risks: string[]; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PilotOSReleaseCandidateKnownLimitation { id: string; limitation: string; mitigation: string; simulated_only: true; metadata_only: true }
export interface PilotOSReleaseCandidateHumanReviewQueue { id: string; items: string[]; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PilotOSReleaseCandidateInstitutionalPackage { id: string; title: string; audienceType: PilotOSReleaseCandidateAudienceType; packageScore: number; simulated_only: true; metadata_only: true; demo_preparation_only: true }
export interface PilotOSReleaseCandidateExecutiveChecklist { id: string; items: string[]; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PilotOSReleaseCandidateReleaseDecision { id: string; decision: PilotOSReleaseCandidateDecision; rationale: string; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PilotOSReleaseCandidateAuditTrail { id: string; events: string[]; append_only_simulated: true; simulated_only: true; metadata_only: true }
export interface PilotOSReleaseCandidateExecutiveReport { id: string; summary: string; decision: PilotOSReleaseCandidateDecision; simulated_only: true; metadata_only: true; human_review_required: true; release_candidate_only: true; command_center_linked: true }
