export type PilotExecutionStage = 'draft_governance' | 'pre_activation_review' | 'simulated_activation_ready' | 'simulated_execution_monitoring' | 'pause_required' | 'refine_required' | 'stop_required' | 'closeout_ready'
export type PilotExecutionDecision = 'go_simulated' | 'pause' | 'refine' | 'stop' | 'escalate_human_review' | 'pending_review'
export type PilotExecutionRiskLevel = 'low' | 'moderate' | 'high' | 'critical'
export type PilotExecutionEvidenceStatus = 'missing' | 'pending' | 'partial' | 'sufficient' | 'rejected' | 'requires_review'
export type PilotExecutionBoundaryStatus = 'compliant' | 'warning' | 'violation' | 'blocked'
export type PilotExecutionReviewDomain = 'governance' | 'legal' | 'scientific' | 'regulatory' | 'ethical' | 'technical' | 'commercial' | 'human_review'

export interface PilotExecutionGuardrails { simulated_only: true; metadata_only: true; human_review_required: true; contains_clinical_data: false; contains_patient_data: false; contains_personal_sensitive_data: false; real_clinical_operation_claim: false; real_pilot_execution_claim: false; real_client_claim: false; real_contract_claim: false; real_partnership_claim: false; real_billing_claim: false; real_revenue_claim: false; legal_signature_claim: false; regulatory_authorization_claim: false; scientific_validation_claim: false; external_certification_claim: false; diagnostic_truth_certification_claim: false; public_health_claim: false; treatment_claim: false; outcome_guarantee_claim: false; automated_crm_claim: false; real_email_automation_claim: false; production_deploy_claim: false }
export interface StrategicPilotExecutionGovernanceRoom extends PilotExecutionGuardrails { roomId: string; simulatedOrganizationName: string; sourceProposalReference: string; linkedV37ProposalRoomId: string; linkedV36ConversionRoomId: string; linkedV35EngagementRoomId: string; linkedV12LeanFreezeReference: string; pilotExecutionStage: PilotExecutionStage; executionReadinessScore: number; evidenceSufficiencyScore: number; riskBurdenScore: number; governanceCompletenessScore: number; recommendedDecision: PilotExecutionDecision }
export interface StrategicPilotExecutionScenario extends StrategicPilotExecutionGovernanceRoom { activationGates: PilotExecutionActivationGate[]; checkpoints: PilotExecutionCheckpoint[]; milestones: PilotExecutionMilestone[]; cadence: PilotExecutionCadence[]; responsibilityMatrix: PilotExecutionResponsibilityMatrix; evidenceLedger: PilotExecutionEvidenceLedger; deviationRegister: PilotExecutionDeviationRegister; riskRegister: PilotExecutionRiskRegister; interruptionRules: PilotExecutionInterruptionRule[]; decisionBoard: PilotExecutionDecisionBoard; humanReviewQueue: PilotExecutionHumanReviewQueue; stakeholderReviewBoard: PilotExecutionStakeholderReviewBoard; boundaryClaimsGuardrails: PilotExecutionBoundaryClaimsGuardrail[]; auditTrail: PilotExecutionAuditTrail; executiveReport: StrategicPilotExecutionExecutiveReport }
export interface PilotExecutionGovernanceState extends PilotExecutionGuardrails { version: 'v3.8'; rooms: StrategicPilotExecutionGovernanceRoom[]; scenarios: StrategicPilotExecutionScenario[]; activationGates: PilotExecutionActivationGate[]; checkpoints: PilotExecutionCheckpoint[]; milestones: PilotExecutionMilestone[]; cadences: PilotExecutionCadence[]; responsibilityMatrices: PilotExecutionResponsibilityMatrix[]; evidenceLedgers: PilotExecutionEvidenceLedger[]; evidenceRecords: PilotExecutionEvidenceRecord[]; deviationRegisters: PilotExecutionDeviationRegister[]; deviationItems: PilotExecutionDeviationItem[]; riskRegisters: PilotExecutionRiskRegister[]; riskItems: PilotExecutionRiskItem[]; interruptionRules: PilotExecutionInterruptionRule[]; decisionBoards: PilotExecutionDecisionBoard[]; decisionItems: PilotExecutionDecisionItem[]; humanReviewQueues: PilotExecutionHumanReviewQueue[]; humanReviewItems: PilotExecutionHumanReviewItem[]; stakeholderReviewBoards: PilotExecutionStakeholderReviewBoard[]; boundaryClaimsGuardrails: PilotExecutionBoundaryClaimsGuardrail[]; auditTrails: PilotExecutionAuditTrail[]; executiveReports: StrategicPilotExecutionExecutiveReport[] }
export interface PilotExecutionActivationGate { id: string; roomId: string; title: string; status: PilotExecutionEvidenceStatus; requiredDomain: PilotExecutionReviewDomain; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PilotExecutionCheckpoint { id: string; roomId: string; label: string; sequence: number; decision: PilotExecutionDecision; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PilotExecutionMilestone { id: string; roomId: string; title: string; stage: PilotExecutionStage; evidenceStatus: PilotExecutionEvidenceStatus; simulated_only: true; metadata_only: true }
export interface PilotExecutionCadence { id: string; roomId: string; cadenceLabel: string; reviewDomain: PilotExecutionReviewDomain; human_review_required: true; simulated_only: true; metadata_only: true }
export interface PilotExecutionResponsibilityRole { id: string; role: string; responsibility: string; reviewDomain: PilotExecutionReviewDomain; simulated_only: true; metadata_only: true }
export interface PilotExecutionResponsibilityMatrix { id: string; roomId: string; roles: PilotExecutionResponsibilityRole[]; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PilotExecutionEvidenceRequirement { id: string; title: string; status: PilotExecutionEvidenceStatus; reviewDomain: PilotExecutionReviewDomain; simulated_only: true; metadata_only: true }
export interface PilotExecutionEvidenceRecord extends PilotExecutionEvidenceRequirement { ledgerId: string; source: string }
export interface PilotExecutionEvidenceLedger { id: string; roomId: string; records: PilotExecutionEvidenceRecord[]; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PilotExecutionDeviationItem { id: string; title: string; boundaryStatus: PilotExecutionBoundaryStatus; decision: PilotExecutionDecision; simulated_only: true; metadata_only: true }
export interface PilotExecutionDeviationRegister { id: string; roomId: string; items: PilotExecutionDeviationItem[]; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PilotExecutionRiskItem { id: string; title: string; level: PilotExecutionRiskLevel; mitigation: string; simulated_only: true; metadata_only: true }
export interface PilotExecutionRiskRegister { id: string; roomId: string; items: PilotExecutionRiskItem[]; highestRisk: PilotExecutionRiskLevel; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PilotExecutionInterruptionRule { id: string; roomId: string; trigger: string; decision: PilotExecutionDecision; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PilotExecutionDecisionItem { id: string; label: string; decision: PilotExecutionDecision; rationale: string; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PilotExecutionDecisionBoard { id: string; roomId: string; items: PilotExecutionDecisionItem[]; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PilotExecutionHumanReviewItem { id: string; reason: string; domain: PilotExecutionReviewDomain; decision: PilotExecutionDecision; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PilotExecutionHumanReviewQueue { id: string; roomId: string; items: PilotExecutionHumanReviewItem[]; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PilotExecutionStakeholderReviewBoard { id: string; roomId: string; domains: PilotExecutionReviewDomain[]; status: PilotExecutionEvidenceStatus; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PilotExecutionBoundaryClaimsGuardrail { id: string; roomId: string; prohibitedClaim: string; safeLanguage: string; status: PilotExecutionBoundaryStatus; simulated_only: true; metadata_only: true }
export interface PilotExecutionAuditTrail { id: string; roomId: string; events: string[]; append_only_simulated: true; simulated_only: true; metadata_only: true }
export interface StrategicPilotExecutionExecutiveReport { id: string; roomId: string; summary: string; recommendedDecision: PilotExecutionDecision; requiredHumanReview: true; simulated_only: true; metadata_only: true }
