export type SenseTrustPartnerEngagementStage = 'not_started' | 'prepared' | 'simulated_outreach' | 'simulated_meeting' | 'simulated_feedback' | 'follow_up_required' | 'human_review_required' | 'paused' | 'blocked' | 'closed_simulated'
export type SenseTrustPartnerEngagementStatus = 'draft' | 'ready_for_review' | 'engagement_ready' | 'meeting_simulated' | 'response_reviewed' | 'follow_up_ready' | 'refine_required' | 'paused' | 'blocked' | 'revoked_simulated'
export type SenseTrustPartnerInteractionType = 'simulated_intro' | 'simulated_meeting' | 'simulated_feedback' | 'simulated_objection' | 'simulated_follow_up' | 'human_review_note' | 'legal_review_pending' | 'regulatory_review_pending' | 'scientific_review_pending' | 'executive_decision'
export type SenseTrustPartnerEngagementDecision = 'go' | 'pause' | 'refine' | 'follow_up' | 'prepare_new_brief' | 'require_human_review' | 'require_legal_review' | 'require_regulatory_review' | 'require_scientific_review' | 'block'
export type SenseTrustPartnerEngagementRiskLevel = 'low' | 'medium' | 'high' | 'critical'
export type SenseTrustPartnerEngagementConfidenceLevel = 'low' | 'medium' | 'high' | 'simulated_only'
export type SenseTrustEngagementPartnerType = 'clinic_network' | 'public_sector' | 'education_network' | 'legal_partner' | 'research_partner' | 'enterprise_partner' | 'government_partner' | 'investor_partner' | 'internal_strategy'

export interface SenseTrustStrategicPartnerEngagementControlRoom { partner_engagement_control_room_id: string; partner_readiness_room_id: string; evidence_simulator_id: string; simulation_console_id: string; operating_model_id: string; room_title: string; engagement_status: SenseTrustPartnerEngagementStatus; engagement_track_count: number; interaction_ledger_id: string; meeting_simulation_board_id: string; response_matrix_id: string; objection_resolution_map_id: string; engagement_risk_register_id: string; follow_up_decision_board_id: string; engagement_readiness_score_id: string; human_review_escalation_queue_id: string; boundary_claims_guardrail_id: string; engagement_audit_trail_id: string; executive_report_id: string; recommended_engagement_decision: SenseTrustPartnerEngagementDecision; blocked_actions: string[]; required_reviews: string[]; logical_partner_engagement_hash: string; previous_partner_engagement_hash: string | null; metadata_only: true; contains_clinical_data: false; contains_patient_data: false; contains_personal_sensitive_data: false; real_clinical_operation_claim: false; contract_binding_claim: false; client_claim: false; partnership_claim: false; regulatory_validation_claim: false; diagnostic_truth_certification_claim: false; real_revenue_claim: false; real_billing_claim: false; real_impact_claim: false; real_capacity_claim: false; real_scientific_validation_claim: false; external_certification_claim: false; real_crm_claim: false; real_email_automation_claim: false; simulated_only: true }
export interface SenseTrustPartnerEngagementTrack { partner_engagement_track_id: string; partner_engagement_control_room_id: string; partner_profile_id: string; partner_type: SenseTrustEngagementPartnerType; partner_label: string; engagement_stage: SenseTrustPartnerEngagementStage; engagement_status: SenseTrustPartnerEngagementStatus; interaction_count: number; open_objections: number; risk_level: SenseTrustPartnerEngagementRiskLevel; confidence_level: SenseTrustPartnerEngagementConfidenceLevel; recommended_decision: SenseTrustPartnerEngagementDecision; required_reviews: string[]; blocked_actions: string[]; metadata_only: true; real_partner_claim: false; client_claim: false; contract_binding_claim: false; partnership_claim: false; commercial_commitment_claim: false; regulatory_authorization_claim: false; real_outreach_claim: false; simulated_only: true }
export interface SenseTrustPartnerInteractionLedgerItem { interaction_item_id: string; interaction_ledger_id: string; interaction_type: SenseTrustPartnerInteractionType; title: string; status: SenseTrustPartnerEngagementStatus; simulated_only: true }
export interface SenseTrustPartnerInteractionLedger { interaction_ledger_id: string; partner_engagement_control_room_id: string; items: SenseTrustPartnerInteractionLedgerItem[]; metadata_only: true; real_crm_claim: false; real_email_automation_claim: false; simulated_only: true }
export interface SenseTrustPartnerMeetingSimulationItem { meeting_item_id: string; meeting_simulation_board_id: string; topic: string; stage: SenseTrustPartnerEngagementStage; simulated_only: true }
export interface SenseTrustPartnerMeetingSimulationBoard { meeting_simulation_board_id: string; partner_engagement_control_room_id: string; items: SenseTrustPartnerMeetingSimulationItem[]; metadata_only: true; real_meeting_claim: false; simulated_only: true }
export interface SenseTrustPartnerResponseMatrixItem { response_item_id: string; response_matrix_id: string; trigger: string; safe_response: string; risk_level: SenseTrustPartnerEngagementRiskLevel; simulated_only: true }
export interface SenseTrustPartnerResponseMatrix { response_matrix_id: string; partner_engagement_control_room_id: string; items: SenseTrustPartnerResponseMatrixItem[]; metadata_only: true; simulated_only: true }
export interface SenseTrustPartnerObjectionResolutionItem { objection_resolution_item_id: string; objection_resolution_map_id: string; objection: string; resolution_status: SenseTrustPartnerEngagementStatus; required_review: string; simulated_only: true }
export interface SenseTrustPartnerObjectionResolutionMap { objection_resolution_map_id: string; partner_engagement_control_room_id: string; items: SenseTrustPartnerObjectionResolutionItem[]; metadata_only: true; simulated_only: true }
export interface SenseTrustPartnerEngagementRiskItem { risk_item_id: string; engagement_risk_register_id: string; risk_title: string; risk_level: SenseTrustPartnerEngagementRiskLevel; mitigation: string; simulated_only: true }
export interface SenseTrustPartnerEngagementRiskRegister { engagement_risk_register_id: string; partner_engagement_control_room_id: string; items: SenseTrustPartnerEngagementRiskItem[]; highest_risk_level: SenseTrustPartnerEngagementRiskLevel; metadata_only: true; legal_or_regulatory_opinion_claim: false; simulated_only: true }
export interface SenseTrustPartnerFollowUpDecisionItem { follow_up_decision_item_id: string; follow_up_decision_board_id: string; decision: SenseTrustPartnerEngagementDecision; rationale: string; simulated_only: true }
export interface SenseTrustPartnerFollowUpDecisionBoard { follow_up_decision_board_id: string; partner_engagement_control_room_id: string; items: SenseTrustPartnerFollowUpDecisionItem[]; metadata_only: true; binding_decision_claim: false; simulated_only: true }
export interface SenseTrustPartnerEngagementReadinessScoreItem { score_item_id: string; engagement_readiness_score_id: string; dimension: string; score: number; confidence: SenseTrustPartnerEngagementConfidenceLevel; simulated_only: true }
export interface SenseTrustPartnerEngagementReadinessScore { engagement_readiness_score_id: string; partner_engagement_control_room_id: string; items: SenseTrustPartnerEngagementReadinessScoreItem[]; aggregate_score: number; recommended_decision: SenseTrustPartnerEngagementDecision; metadata_only: true; simulated_only: true }
export interface SenseTrustPartnerHumanReviewEscalationItem { escalation_item_id: string; human_review_escalation_queue_id: string; reason: string; reviewer_role: string; simulated_only: true }
export interface SenseTrustPartnerHumanReviewEscalationQueue { human_review_escalation_queue_id: string; partner_engagement_control_room_id: string; items: SenseTrustPartnerHumanReviewEscalationItem[]; metadata_only: true; real_regulatory_process_claim: false; simulated_only: true }
export interface SenseTrustPartnerBoundaryClaimsGuardrailItem { guardrail_item_id: string; boundary_claims_guardrail_id: string; prohibited_claim: string; safe_language: string; simulated_only: true }
export interface SenseTrustPartnerBoundaryClaimsGuardrail { boundary_claims_guardrail_id: string; partner_engagement_control_room_id: string; items: SenseTrustPartnerBoundaryClaimsGuardrailItem[]; metadata_only: true; simulated_only: true }
export interface SenseTrustPartnerEngagementAuditTrailItem { audit_trail_item_id: string; engagement_audit_trail_id: string; action: string; actor_role: string; simulated_only: true }
export interface SenseTrustPartnerEngagementAuditTrail { engagement_audit_trail_id: string; partner_engagement_control_room_id: string; items: SenseTrustPartnerEngagementAuditTrailItem[]; metadata_only: true; append_only_simulated: true; simulated_only: true }
export interface SenseTrustStrategicPartnerEngagementExecutiveReport { report_id: string; partner_engagement_control_room_id: string; executive_summary: string; recommended_decision: SenseTrustPartnerEngagementDecision; interaction_summary: string; objection_summary: string; risk_summary: string; human_review_summary: string; simulated_only: true }
export interface SenseTrustStrategicPartnerEngagementControlRoomState { state_id: string; version: 'v3.5'; rooms: SenseTrustStrategicPartnerEngagementControlRoom[]; tracks: SenseTrustPartnerEngagementTrack[]; interaction_ledgers: SenseTrustPartnerInteractionLedger[]; interaction_ledger_items: SenseTrustPartnerInteractionLedgerItem[]; meeting_simulation_boards: SenseTrustPartnerMeetingSimulationBoard[]; meeting_simulation_items: SenseTrustPartnerMeetingSimulationItem[]; response_matrices: SenseTrustPartnerResponseMatrix[]; response_matrix_items: SenseTrustPartnerResponseMatrixItem[]; objection_resolution_maps: SenseTrustPartnerObjectionResolutionMap[]; objection_resolution_items: SenseTrustPartnerObjectionResolutionItem[]; engagement_risk_registers: SenseTrustPartnerEngagementRiskRegister[]; engagement_risk_items: SenseTrustPartnerEngagementRiskItem[]; follow_up_decision_boards: SenseTrustPartnerFollowUpDecisionBoard[]; follow_up_decision_items: SenseTrustPartnerFollowUpDecisionItem[]; engagement_readiness_scores: SenseTrustPartnerEngagementReadinessScore[]; engagement_readiness_score_items: SenseTrustPartnerEngagementReadinessScoreItem[]; human_review_escalation_queues: SenseTrustPartnerHumanReviewEscalationQueue[]; human_review_escalation_items: SenseTrustPartnerHumanReviewEscalationItem[]; boundary_claims_guardrails: SenseTrustPartnerBoundaryClaimsGuardrail[]; boundary_claims_guardrail_items: SenseTrustPartnerBoundaryClaimsGuardrailItem[]; engagement_audit_trails: SenseTrustPartnerEngagementAuditTrail[]; engagement_audit_trail_items: SenseTrustPartnerEngagementAuditTrailItem[]; executive_reports: SenseTrustStrategicPartnerEngagementExecutiveReport[]; references: string[]; metadata_only: true; clinical_data_used: false; patient_data_used: false; personal_sensitive_data_used: false; real_clinical_operation_claimed: false; contract_binding_claimed: false; client_claim: false; partnership_claim: false; regulatory_validation_claim: false; diagnostic_truth_certification_claimed: false; real_revenue_claimed: false; real_billing_claimed: false; real_impact_claimed: false; real_capacity_claimed: false; real_scientific_validation_claimed: false; external_certification_claimed: false; real_crm_claimed: false; real_email_automation_claimed: false; simulated_only: true }
export interface SenseTrustStrategicPartnerEngagementExportPayload { schema: 'sensetrust.strategic_partner_engagement_export.v1'; exported_at: string; state: SenseTrustStrategicPartnerEngagementControlRoomState; public_exposure: 'metadata_only'; simulated_only: true }
export interface SenseTrustStrategicPartnerEngagementValidationResult { valid: boolean; errors: string[] }
