export type SenseTrustPilotProposalStage = 'not_started' | 'conversion_reviewed' | 'scope_drafted' | 'value_hypothesis_drafted' | 'entry_exit_criteria_drafted' | 'responsibility_matrix_drafted' | 'evidence_requirements_mapped' | 'legal_review_required' | 'scientific_review_required' | 'regulatory_review_required' | 'human_review_required' | 'proposal_ready_for_review' | 'paused' | 'blocked' | 'closed_simulated'
export type SenseTrustPilotProposalStatus = 'draft' | 'ready_for_review' | 'non_binding_scope_ready' | 'evidence_requirements_ready' | 'review_pending' | 'refine_required' | 'paused' | 'blocked' | 'revoked_simulated'
export type SenseTrustPilotProposalDecision = 'go' | 'pause' | 'refine' | 'prepare_non_binding_proposal' | 'require_human_review' | 'require_legal_review' | 'require_regulatory_review' | 'require_scientific_review' | 'block'
export type SenseTrustPilotProposalRiskLevel = 'low' | 'medium' | 'high' | 'critical'
export type SenseTrustPilotProposalConfidenceLevel = 'low' | 'medium' | 'high' | 'simulated_only'
export type SenseTrustPilotReviewRoutingType = 'human_review' | 'legal_review' | 'regulatory_review' | 'scientific_review' | 'executive_review' | 'commercial_review' | 'ethics_review'
export type SenseTrustPilotPartnerType = 'clinic_network' | 'public_sector' | 'education_network' | 'legal_partner' | 'research_partner' | 'enterprise_partner' | 'government_partner' | 'investor_partner' | 'internal_strategy'

export interface SenseTrustStrategicPartnershipPilotProposalRoom { partnership_pilot_proposal_room_id: string; partnership_conversion_decision_room_id: string; partner_engagement_control_room_id: string; partner_readiness_room_id: string; evidence_simulator_id: string; simulation_console_id: string; operating_model_id: string; room_title: string; pilot_proposal_status: SenseTrustPilotProposalStatus; pilot_proposal_candidate_count: number; non_binding_scope_matrix_id: string; value_hypothesis_canvas_id: string; entry_criteria_board_id: string; exit_criteria_board_id: string; responsibility_matrix_id: string; evidence_requirement_map_id: string; risk_interruption_register_id: string; legal_review_queue_id: string; scientific_review_queue_id: string; regulatory_review_queue_id: string; human_review_board_id: string; boundary_claims_guardrail_id: string; proposal_audit_trail_id: string; executive_report_id: string; recommended_pilot_proposal_decision: SenseTrustPilotProposalDecision; blocked_actions: string[]; required_reviews: string[]; logical_pilot_proposal_hash: string; previous_pilot_proposal_hash: string | null; metadata_only: true; contains_clinical_data: false; contains_patient_data: false; contains_personal_sensitive_data: false; real_clinical_operation_claim: false; contract_binding_claim: false; client_claim: false; partnership_claim: false; regulatory_validation_claim: false; diagnostic_truth_certification_claim: false; real_revenue_claim: false; real_billing_claim: false; real_impact_claim: false; real_capacity_claim: false; real_scientific_validation_claim: false; external_certification_claim: false; real_crm_claim: false; real_email_automation_claim: false; binding_proposal_claim: false; commercial_commitment_claim: false; legal_commitment_claim: false; real_loi_claim: false; real_mou_claim: false; simulated_only: true }
export interface SenseTrustPilotProposalCandidate { pilot_proposal_candidate_id: string; partnership_pilot_proposal_room_id: string; partnership_conversion_candidate_id: string; partner_engagement_track_id: string; partner_profile_id: string; partner_type: SenseTrustPilotPartnerType; partner_label: string; pilot_proposal_stage: SenseTrustPilotProposalStage; pilot_proposal_status: SenseTrustPilotProposalStatus; non_binding_scope_score: number; value_hypothesis_score: number; evidence_requirement_score: number; legal_review_need_score: number; scientific_review_need_score: number; regulatory_review_need_score: number; pilot_proposal_risk_level: SenseTrustPilotProposalRiskLevel; pilot_proposal_confidence_level: SenseTrustPilotProposalConfidenceLevel; recommended_pilot_proposal_decision: SenseTrustPilotProposalDecision; required_reviews: string[]; blocked_actions: string[]; metadata_only: true; real_partner_claim: false; client_claim: false; contract_binding_claim: false; partnership_claim: false; commercial_commitment_claim: false; regulatory_authorization_claim: false; binding_proposal_claim: false; legal_commitment_claim: false; real_loi_claim: false; real_mou_claim: false; simulated_only: true }
export interface SenseTrustNonBindingPilotScopeMatrixItem { scope_item_id: string; non_binding_scope_matrix_id: string; dimension: string; score: number; simulated_only: true }
export interface SenseTrustNonBindingPilotScopeMatrix { non_binding_scope_matrix_id: string; partnership_pilot_proposal_room_id: string; items: SenseTrustNonBindingPilotScopeMatrixItem[]; metadata_only: true; binding_proposal_claim: false; simulated_only: true }
export interface SenseTrustPilotValueHypothesisItem { value_hypothesis_item_id: string; value_hypothesis_canvas_id: string; hypothesis: string; confidence: SenseTrustPilotProposalConfidenceLevel; simulated_only: true }
export interface SenseTrustPilotValueHypothesisCanvas { value_hypothesis_canvas_id: string; partnership_pilot_proposal_room_id: string; items: SenseTrustPilotValueHypothesisItem[]; metadata_only: true; real_impact_claim: false; simulated_only: true }
export interface SenseTrustPilotEntryCriteriaItem { entry_criteria_item_id: string; entry_criteria_board_id: string; criterion: string; status: SenseTrustPilotProposalStatus; simulated_only: true }
export interface SenseTrustPilotEntryCriteriaBoard { entry_criteria_board_id: string; partnership_pilot_proposal_room_id: string; items: SenseTrustPilotEntryCriteriaItem[]; metadata_only: true; simulated_only: true }
export interface SenseTrustPilotExitCriteriaItem { exit_criteria_item_id: string; exit_criteria_board_id: string; criterion: string; status: SenseTrustPilotProposalStatus; simulated_only: true }
export interface SenseTrustPilotExitCriteriaBoard { exit_criteria_board_id: string; partnership_pilot_proposal_room_id: string; items: SenseTrustPilotExitCriteriaItem[]; metadata_only: true; simulated_only: true }
export interface SenseTrustPilotResponsibilityMatrixItem { responsibility_item_id: string; responsibility_matrix_id: string; role: string; responsibility: string; simulated_only: true }
export interface SenseTrustPilotResponsibilityMatrix { responsibility_matrix_id: string; partnership_pilot_proposal_room_id: string; items: SenseTrustPilotResponsibilityMatrixItem[]; metadata_only: true; legal_commitment_claim: false; simulated_only: true }
export interface SenseTrustPilotEvidenceRequirementItem { evidence_requirement_item_id: string; evidence_requirement_map_id: string; evidence_type: string; status: SenseTrustPilotProposalStatus; simulated_only: true }
export interface SenseTrustPilotEvidenceRequirementMap { evidence_requirement_map_id: string; partnership_pilot_proposal_room_id: string; items: SenseTrustPilotEvidenceRequirementItem[]; metadata_only: true; real_scientific_validation_claim: false; simulated_only: true }
export interface SenseTrustPilotRiskInterruptionItem { risk_interruption_item_id: string; risk_interruption_register_id: string; risk_title: string; risk_level: SenseTrustPilotProposalRiskLevel; interruption_rule: string; simulated_only: true }
export interface SenseTrustPilotRiskInterruptionRegister { risk_interruption_register_id: string; partnership_pilot_proposal_room_id: string; items: SenseTrustPilotRiskInterruptionItem[]; highest_risk_level: SenseTrustPilotProposalRiskLevel; metadata_only: true; simulated_only: true }
export interface SenseTrustPilotLegalReviewQueueItem { legal_review_item_id: string; legal_review_queue_id: string; routing_type: SenseTrustPilotReviewRoutingType; reason: string; simulated_only: true }
export interface SenseTrustPilotLegalReviewQueue { legal_review_queue_id: string; partnership_pilot_proposal_room_id: string; items: SenseTrustPilotLegalReviewQueueItem[]; metadata_only: true; legal_opinion_claim: false; simulated_only: true }
export interface SenseTrustPilotScientificReviewQueueItem { scientific_review_item_id: string; scientific_review_queue_id: string; routing_type: SenseTrustPilotReviewRoutingType; reason: string; simulated_only: true }
export interface SenseTrustPilotScientificReviewQueue { scientific_review_queue_id: string; partnership_pilot_proposal_room_id: string; items: SenseTrustPilotScientificReviewQueueItem[]; metadata_only: true; scientific_validation_claim: false; simulated_only: true }
export interface SenseTrustPilotRegulatoryReviewQueueItem { regulatory_review_item_id: string; regulatory_review_queue_id: string; routing_type: SenseTrustPilotReviewRoutingType; reason: string; simulated_only: true }
export interface SenseTrustPilotRegulatoryReviewQueue { regulatory_review_queue_id: string; partnership_pilot_proposal_room_id: string; items: SenseTrustPilotRegulatoryReviewQueueItem[]; metadata_only: true; regulatory_authorization_claim: false; simulated_only: true }
export interface SenseTrustPilotHumanReviewBoardItem { human_review_item_id: string; human_review_board_id: string; reason: string; reviewer_role: string; simulated_only: true }
export interface SenseTrustPilotHumanReviewBoard { human_review_board_id: string; partnership_pilot_proposal_room_id: string; items: SenseTrustPilotHumanReviewBoardItem[]; metadata_only: true; simulated_only: true }
export interface SenseTrustPilotBoundaryClaimsGuardrailItem { guardrail_item_id: string; boundary_claims_guardrail_id: string; prohibited_claim: string; safe_language: string; simulated_only: true }
export interface SenseTrustPilotBoundaryClaimsGuardrail { boundary_claims_guardrail_id: string; partnership_pilot_proposal_room_id: string; items: SenseTrustPilotBoundaryClaimsGuardrailItem[]; metadata_only: true; simulated_only: true }
export interface SenseTrustPilotProposalAuditTrailItem { audit_trail_item_id: string; proposal_audit_trail_id: string; action: string; actor_role: string; simulated_only: true }
export interface SenseTrustPilotProposalAuditTrail { proposal_audit_trail_id: string; partnership_pilot_proposal_room_id: string; items: SenseTrustPilotProposalAuditTrailItem[]; metadata_only: true; append_only_simulated: true; simulated_only: true }
export interface SenseTrustStrategicPartnershipPilotProposalExecutiveReport { report_id: string; partnership_pilot_proposal_room_id: string; executive_summary: string; recommended_decision: SenseTrustPilotProposalDecision; scope_summary: string; evidence_summary: string; risk_summary: string; human_review_summary: string; simulated_only: true }
export interface SenseTrustStrategicPartnershipPilotProposalRoomState { state_id: string; version: 'v3.7'; rooms: SenseTrustStrategicPartnershipPilotProposalRoom[]; candidates: SenseTrustPilotProposalCandidate[]; scope_matrices: SenseTrustNonBindingPilotScopeMatrix[]; scope_matrix_items: SenseTrustNonBindingPilotScopeMatrixItem[]; value_canvases: SenseTrustPilotValueHypothesisCanvas[]; value_items: SenseTrustPilotValueHypothesisItem[]; entry_boards: SenseTrustPilotEntryCriteriaBoard[]; entry_items: SenseTrustPilotEntryCriteriaItem[]; exit_boards: SenseTrustPilotExitCriteriaBoard[]; exit_items: SenseTrustPilotExitCriteriaItem[]; responsibility_matrices: SenseTrustPilotResponsibilityMatrix[]; responsibility_items: SenseTrustPilotResponsibilityMatrixItem[]; evidence_maps: SenseTrustPilotEvidenceRequirementMap[]; evidence_items: SenseTrustPilotEvidenceRequirementItem[]; risk_registers: SenseTrustPilotRiskInterruptionRegister[]; risk_items: SenseTrustPilotRiskInterruptionItem[]; legal_review_queues: SenseTrustPilotLegalReviewQueue[]; legal_review_items: SenseTrustPilotLegalReviewQueueItem[]; scientific_review_queues: SenseTrustPilotScientificReviewQueue[]; scientific_review_items: SenseTrustPilotScientificReviewQueueItem[]; regulatory_review_queues: SenseTrustPilotRegulatoryReviewQueue[]; regulatory_review_items: SenseTrustPilotRegulatoryReviewQueueItem[]; human_review_boards: SenseTrustPilotHumanReviewBoard[]; human_review_items: SenseTrustPilotHumanReviewBoardItem[]; boundary_claims_guardrails: SenseTrustPilotBoundaryClaimsGuardrail[]; boundary_claims_guardrail_items: SenseTrustPilotBoundaryClaimsGuardrailItem[]; audit_trails: SenseTrustPilotProposalAuditTrail[]; audit_trail_items: SenseTrustPilotProposalAuditTrailItem[]; executive_reports: SenseTrustStrategicPartnershipPilotProposalExecutiveReport[]; references: string[]; metadata_only: true; clinical_data_used: false; patient_data_used: false; personal_sensitive_data_used: false; real_clinical_operation_claimed: false; contract_binding_claimed: false; client_claim: false; partnership_claim: false; regulatory_validation_claim: false; diagnostic_truth_certification_claimed: false; real_revenue_claimed: false; real_billing_claimed: false; real_impact_claimed: false; real_capacity_claimed: false; real_scientific_validation_claimed: false; external_certification_claimed: false; real_crm_claimed: false; real_email_automation_claimed: false; binding_proposal_claimed: false; commercial_commitment_claimed: false; legal_commitment_claimed: false; real_loi_claimed: false; real_mou_claimed: false; simulated_only: true }
export interface SenseTrustStrategicPartnershipPilotProposalExportPayload { schema: 'sensetrust.strategic_partnership_pilot_proposal_export.v1'; exported_at: string; state: SenseTrustStrategicPartnershipPilotProposalRoomState; public_exposure: 'metadata_only'; simulated_only: true }
export interface SenseTrustStrategicPartnershipPilotProposalValidationResult { valid: boolean; errors: string[] }
