export type SenseTrustEvidenceSimulatorStatusType = 'draft' | 'ready_for_review' | 'evidence_reviewed' | 'evidence_package_ready' | 'refine_required' | 'paused' | 'blocked' | 'revoked_simulated'
export type SenseTrustEvidenceType = 'governance_document' | 'simulation_output' | 'risk_register' | 'decision_trace' | 'readiness_score' | 'human_review_note' | 'legal_review_pending' | 'regulatory_review_pending' | 'institutional_brief' | 'executive_report' | 'external_validation_pending'
export type SenseTrustEvidenceStrengthLevel = 'absent' | 'weak' | 'partial' | 'adequate_simulated' | 'strong_simulated' | 'external_validation_required'
export type SenseTrustProofRiskLevel = 'low' | 'medium' | 'high' | 'critical'
export type SenseTrustEvidenceReadinessDecisionType = 'go' | 'pause' | 'refine' | 'strengthen_evidence' | 'require_human_review' | 'require_legal_review' | 'require_regulatory_review' | 'block'
export type SenseTrustEvidenceConfidenceLevel = 'low' | 'medium' | 'high' | 'simulated_only'

export interface SenseTrustScenarioEvidenceItem { evidence_item_id: string; evidence_package_id: string; evidence_type: SenseTrustEvidenceType; evidence_title: string; evidence_description: string; evidence_source: string; evidence_strength_level: SenseTrustEvidenceStrengthLevel; proof_risk_level: SenseTrustProofRiskLevel; evidence_hash: string; previous_evidence_hash: string | null; timestamp_simulated: string; metadata_only: true; contains_clinical_data: false; contains_patient_data: false; real_world_evidence_claim: false; simulated_only: true }
export interface SenseTrustScenarioEvidencePackage { evidence_package_id: string; evidence_simulator_id: string; scenario_id: string; scenario_type: string; package_title: string; evidence_items: SenseTrustScenarioEvidenceItem[]; evidence_strength_level: SenseTrustEvidenceStrengthLevel; proof_risk_level: SenseTrustProofRiskLevel; evidence_confidence_level: SenseTrustEvidenceConfidenceLevel; readiness_decision: SenseTrustEvidenceReadinessDecisionType; missing_evidence: string[]; required_reviews: string[]; blocked_actions: string[]; metadata_only: true; real_evidence_claim: false; clinical_validation_claim: false; regulatory_authorization_claim: false; external_certification_claim: false; simulated_only: true }
export interface SenseTrustMinimumEvidenceRequirement { requirement_id: string; matrix_id: string; evidence_type: SenseTrustEvidenceType; requirement_title: string; strength_required: SenseTrustEvidenceStrengthLevel; simulated_only: true }
export interface SenseTrustMinimumEvidenceMatrix { matrix_id: string; evidence_simulator_id: string; requirements: SenseTrustMinimumEvidenceRequirement[]; matrix_summary: string; metadata_only: true; official_regulatory_requirement_claim: false; simulated_only: true }
export interface SenseTrustEvidenceGapItem { gap_item_id: string; evidence_simulator_id: string; related_scenario_id: string; gap_title: string; gap_description: string; gap_severity: SenseTrustProofRiskLevel; required_action: string; required_review: string; blocked_until_resolved: boolean; metadata_only: true; simulated_only: true }
export interface SenseTrustEvidenceGapAnalysis { gap_analysis_id: string; evidence_simulator_id: string; gap_items: SenseTrustEvidenceGapItem[]; gap_summary: string; metadata_only: true; external_audit_claim: false; simulated_only: true }
export interface SenseTrustProofRiskItem { proof_risk_item_id: string; evidence_simulator_id: string; related_scenario_id: string; risk_title: string; risk_description: string; proof_risk_level: SenseTrustProofRiskLevel; mitigation_action: string; human_review_required: boolean; legal_review_required: boolean; regulatory_review_required: boolean; metadata_only: true; simulated_only: true }
export interface SenseTrustProofRiskRegister { proof_risk_register_id: string; evidence_simulator_id: string; proof_risk_items: SenseTrustProofRiskItem[]; highest_risk_level: SenseTrustProofRiskLevel; metadata_only: true; legal_or_regulatory_opinion_claim: false; simulated_only: true }
export interface SenseTrustEvidenceMaturityScoreItem { maturity_item_id: string; evidence_simulator_id: string; dimension: string; score: number; strength_level: SenseTrustEvidenceStrengthLevel; simulated_only: true }
export interface SenseTrustEvidenceMaturityScore { maturity_score_id: string; evidence_simulator_id: string; items: SenseTrustEvidenceMaturityScoreItem[]; aggregate_score: number; metadata_only: true; external_certification_claim: false; simulated_only: true }
export interface SenseTrustEvidenceReadinessBoardItem { board_item_id: string; evidence_simulator_id: string; scenario_id: string; decision: SenseTrustEvidenceReadinessDecisionType; reason: string; simulated_only: true }
export interface SenseTrustEvidenceReadinessBoard { board_id: string; evidence_simulator_id: string; items: SenseTrustEvidenceReadinessBoardItem[]; recommended_decision: SenseTrustEvidenceReadinessDecisionType; metadata_only: true; regulatory_approval_claim: false; simulated_only: true }
export interface SenseTrustEvidenceToDecisionTraceItem { trace_item_id: string; trace_id: string; evidence_package_id: string; decision: SenseTrustEvidenceReadinessDecisionType; logical_hash: string; timestamp_simulated: string; metadata_only: true; simulated_only: true }
export interface SenseTrustEvidenceToDecisionTrace { trace_id: string; evidence_simulator_id: string; trace_items: SenseTrustEvidenceToDecisionTraceItem[]; metadata_only: true; execution_authorization_claim: false; simulated_only: true }
export interface SenseTrustInstitutionalEvidenceBrief { brief_id: string; evidence_simulator_id: string; title: string; summary: string; readiness_decision: SenseTrustEvidenceReadinessDecisionType; metadata_only: true; binding_proposal_claim: false; simulated_only: true }
export interface SenseTrustEvidenceStrengtheningPlanItem { plan_item_id: string; plan_id: string; action: string; owner_role: string; required_review: string; simulated_only: true }
export interface SenseTrustEvidenceStrengtheningPlan { plan_id: string; evidence_simulator_id: string; items: SenseTrustEvidenceStrengtheningPlanItem[]; plan_summary: string; metadata_only: true; contractual_commitment_claim: false; simulated_only: true }
export interface SenseTrustHumanReviewEvidenceQueueItem { queue_item_id: string; queue_id: string; evidence_package_id: string; review_reason: string; reviewer_role: string; simulated_only: true }
export interface SenseTrustHumanReviewEvidenceQueue { queue_id: string; evidence_simulator_id: string; items: SenseTrustHumanReviewEvidenceQueueItem[]; queue_summary: string; metadata_only: true; real_regulatory_process_claim: false; simulated_only: true }
export interface SenseTrustEvidenceMisuseBlocker { blocker_id: string; blocked_misuse: string; risk: SenseTrustProofRiskLevel; blocked_action: string; safe_language: string; simulated_only: true }
export interface SenseTrustStrategicScaleEvidenceExecutiveReport { report_id: string; evidence_simulator_id: string; executive_summary: string; recommended_decision: SenseTrustEvidenceReadinessDecisionType; evidence_summary: string; gap_summary: string; proof_risk_summary: string; human_review_summary: string; simulated_only: true }
export interface SenseTrustStrategicScaleEvidenceSimulator { evidence_simulator_id: string; simulation_console_id: string; operating_model_id: string; scale_gate_id: string; readiness_gate_id: string; closeout_id: string; evidence_simulator_title: string; evidence_status: SenseTrustEvidenceSimulatorStatusType; evidence_package_count: number; minimum_evidence_matrix_id: string; evidence_gap_analysis_id: string; proof_risk_register_id: string; evidence_maturity_score_id: string; evidence_readiness_board_id: string; evidence_to_decision_trace_id: string; institutional_evidence_brief_id: string; evidence_strengthening_plan_id: string; human_review_evidence_queue_id: string; executive_report_id: string; recommended_evidence_decision: SenseTrustEvidenceReadinessDecisionType; blocked_actions: string[]; required_reviews: string[]; logical_evidence_simulator_hash: string; previous_evidence_simulator_hash: string | null; metadata_only: true; contains_clinical_data: false; contains_patient_data: false; contains_personal_sensitive_data: false; real_clinical_operation_claim: false; contract_binding_claim: false; client_claim: false; partnership_claim: false; regulatory_validation_claim: false; diagnostic_truth_certification_claim: false; real_revenue_claim: false; real_billing_claim: false; real_impact_claim: false; real_capacity_claim: false; real_scientific_validation_claim: false; external_certification_claim: false; simulated_only: true }
export interface SenseTrustStrategicScaleEvidenceSimulatorState { state_id: string; version: 'v3.3'; evidence_simulators: SenseTrustStrategicScaleEvidenceSimulator[]; evidence_packages: SenseTrustScenarioEvidencePackage[]; evidence_items: SenseTrustScenarioEvidenceItem[]; minimum_evidence_matrices: SenseTrustMinimumEvidenceMatrix[]; minimum_evidence_requirements: SenseTrustMinimumEvidenceRequirement[]; gap_analyses: SenseTrustEvidenceGapAnalysis[]; gap_items: SenseTrustEvidenceGapItem[]; proof_risk_registers: SenseTrustProofRiskRegister[]; proof_risk_items: SenseTrustProofRiskItem[]; maturity_scores: SenseTrustEvidenceMaturityScore[]; maturity_score_items: SenseTrustEvidenceMaturityScoreItem[]; readiness_boards: SenseTrustEvidenceReadinessBoard[]; readiness_board_items: SenseTrustEvidenceReadinessBoardItem[]; evidence_to_decision_traces: SenseTrustEvidenceToDecisionTrace[]; evidence_to_decision_trace_items: SenseTrustEvidenceToDecisionTraceItem[]; institutional_evidence_briefs: SenseTrustInstitutionalEvidenceBrief[]; strengthening_plans: SenseTrustEvidenceStrengtheningPlan[]; strengthening_plan_items: SenseTrustEvidenceStrengtheningPlanItem[]; human_review_queues: SenseTrustHumanReviewEvidenceQueue[]; human_review_queue_items: SenseTrustHumanReviewEvidenceQueueItem[]; misuse_blockers: SenseTrustEvidenceMisuseBlocker[]; executive_reports: SenseTrustStrategicScaleEvidenceExecutiveReport[]; references: string[]; metadata_only: true; clinical_data_used: false; patient_data_used: false; personal_sensitive_data_used: false; real_clinical_operation_claimed: false; contract_binding_claimed: false; client_claim: false; partnership_claim: false; regulatory_validation_claim: false; diagnostic_truth_certification_claimed: false; real_revenue_claimed: false; real_billing_claimed: false; real_impact_claimed: false; real_capacity_claimed: false; real_scientific_validation_claimed: false; external_certification_claimed: false; simulated_only: true }
export interface SenseTrustStrategicScaleEvidenceExportPayload { schema: 'sensetrust.strategic_scale_evidence_export.v1'; exported_at: string; state: SenseTrustStrategicScaleEvidenceSimulatorState; public_exposure: 'metadata_only'; simulated_only: true }
export interface SenseTrustStrategicScaleEvidenceValidationResult { valid: boolean; errors: string[] }
