export type PilotCloseoutStage = 'closeout_draft' | 'evidence_synthesis' | 'learning_loop_review' | 'decision_review' | 'human_review_required' | 'go_recommended' | 'pause_recommended' | 'refine_recommended' | 'stop_recommended' | 'handoff_ready'
export type PilotCloseoutDecision = 'go' | 'pause' | 'refine' | 'stop' | 'handoff_ready' | 'not_ready' | 'escalate_human_review'
export type PilotOutcomeConfidenceLevel = 'low' | 'moderate' | 'high' | 'insufficient'
export type PilotOutcomeBoundaryStatus = 'compliant' | 'warning' | 'violation' | 'blocked'
export type PilotOutcomeReadinessStatus = 'ready' | 'partial' | 'not_ready' | 'requires_review'

export interface PilotOutcomeGuardrails { simulated_only: true; metadata_only: true; human_review_required: true; handoff_preparation_only: true; contains_clinical_data: false; contains_patient_data: false; contains_personal_sensitive_data: false; real_clinical_operation_claim: false; real_pilot_execution_claim: false; real_outcome_claim: false; real_biological_sample_claim: false; real_eeg_claim: false; real_qeeg_claim: false; real_biomarker_claim: false; real_client_claim: false; real_contract_claim: false; real_partnership_claim: false; real_billing_claim: false; real_revenue_claim: false; real_crm_claim: false; real_email_automation_claim: false; regulatory_authorization_claim: false; scientific_validation_claim: false; external_certification_claim: false; diagnostic_truth_certification_claim: false; treatment_claim: false; outcome_guarantee_claim: false; public_health_claim: false }
export interface StrategicPilotOutcomeCloseoutDecisionRoom extends PilotOutcomeGuardrails { roomId: string; simulatedOrganizationName: string; linkedV39MonitoringRoomId: string; linkedV38ExecutionGovernanceRoomId: string; linkedV37ProposalRoomId: string; linkedV12LeanFreezeReference: string; closeoutStage: PilotCloseoutStage; closeoutDecision: PilotCloseoutDecision; outcomeReadinessScore: number; evidenceSynthesisScore: number; riskResolutionScore: number; learningLoopScore: number; handoffReadinessScore: number; v41InstitutionalHandoffPreparation: true }
export interface StrategicPilotOutcomeScenario extends StrategicPilotOutcomeCloseoutDecisionRoom { outcomeSummaries: PilotOutcomeSummary[]; evidenceSynthesis: PilotOutcomeEvidenceSynthesis; checkpointReviews: PilotOutcomeCheckpointReview[]; riskReviews: PilotOutcomeRiskReview[]; deviationReviews: PilotOutcomeDeviationReview[]; learningLoop: PilotOutcomeLearningLoop; decisionBoard: PilotOutcomeDecisionBoard; readinessScorecard: PilotOutcomeReadinessScorecard; institutionalMaturityMatrix: PilotOutcomeInstitutionalMaturityMatrix; handoffReadinessBoard: PilotOutcomeHandoffReadinessBoard; humanReviewQueue: PilotOutcomeHumanReviewQueue; boundaryClaimsGuardrails: PilotOutcomeBoundaryClaimsGuardrail[]; auditTrail: PilotOutcomeAuditTrail; executiveReport: StrategicPilotOutcomeExecutiveReport }
export interface PilotCloseoutState extends PilotOutcomeGuardrails { version: 'v4.0'; rooms: StrategicPilotOutcomeCloseoutDecisionRoom[]; scenarios: StrategicPilotOutcomeScenario[]; outcomeSummaries: PilotOutcomeSummary[]; evidenceSynthesis: PilotOutcomeEvidenceSynthesis[]; evidenceItems: PilotOutcomeEvidenceItem[]; checkpointReviews: PilotOutcomeCheckpointReview[]; riskReviews: PilotOutcomeRiskReview[]; deviationReviews: PilotOutcomeDeviationReview[]; learningLoops: PilotOutcomeLearningLoop[]; lessonsLearned: PilotOutcomeLessonLearned[]; decisionBoards: PilotOutcomeDecisionBoard[]; decisionItems: PilotOutcomeDecisionItem[]; readinessScorecards: PilotOutcomeReadinessScorecard[]; institutionalMaturityMatrices: PilotOutcomeInstitutionalMaturityMatrix[]; handoffReadinessBoards: PilotOutcomeHandoffReadinessBoard[]; humanReviewQueues: PilotOutcomeHumanReviewQueue[]; boundaryClaimsGuardrails: PilotOutcomeBoundaryClaimsGuardrail[]; auditTrails: PilotOutcomeAuditTrail[]; executiveReports: StrategicPilotOutcomeExecutiveReport[]; v41InstitutionalHandoffPreparation: true }
export interface PilotOutcomeSummary { id: string; roomId: string; summary: string; confidenceLevel: PilotOutcomeConfidenceLevel; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PilotOutcomeEvidenceItem { id: string; title: string; status: PilotOutcomeReadinessStatus; confidenceLevel: PilotOutcomeConfidenceLevel; simulated_only: true; metadata_only: true }
export interface PilotOutcomeEvidenceSynthesis { id: string; roomId: string; items: PilotOutcomeEvidenceItem[]; synthesis: string; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PilotOutcomeCheckpointReview { id: string; roomId: string; checkpoint: string; status: PilotOutcomeReadinessStatus; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PilotOutcomeRiskReview { id: string; roomId: string; risk: string; status: PilotOutcomeReadinessStatus; mitigation: string; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PilotOutcomeDeviationReview { id: string; roomId: string; deviation: string; closeoutAction: string; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PilotOutcomeLessonLearned { id: string; lesson: string; nextAction: string; simulated_only: true; metadata_only: true }
export interface PilotOutcomeLearningLoop { id: string; roomId: string; lessons: PilotOutcomeLessonLearned[]; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PilotOutcomeDecisionItem { id: string; criterion: string; decision: PilotCloseoutDecision; confidenceLevel: PilotOutcomeConfidenceLevel; simulated_only: true; metadata_only: true }
export interface PilotOutcomeDecisionBoard { id: string; roomId: string; items: PilotOutcomeDecisionItem[]; finalDecision: PilotCloseoutDecision; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PilotOutcomeReadinessScorecard { id: string; roomId: string; outcomeReadinessScore: number; evidenceSynthesisScore: number; riskResolutionScore: number; learningLoopScore: number; handoffReadinessScore: number; status: PilotOutcomeReadinessStatus; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PilotOutcomeInstitutionalMaturityMatrix { id: string; roomId: string; maturityNotes: string[]; status: PilotOutcomeReadinessStatus; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PilotOutcomeHandoffReadinessBoard { id: string; roomId: string; handoffDecision: PilotCloseoutDecision; blockers: string[]; simulated_only: true; metadata_only: true; human_review_required: true; v41InstitutionalHandoffPreparation: true }
export interface PilotOutcomeHumanReviewQueue { id: string; roomId: string; reasons: string[]; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PilotOutcomeBoundaryClaimsGuardrail { id: string; roomId: string; claimBoundary: string; status: PilotOutcomeBoundaryStatus; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PilotOutcomeAuditTrail { id: string; roomId: string; events: string[]; append_only_simulated: true; simulated_only: true; metadata_only: true }
export interface StrategicPilotOutcomeExecutiveReport { id: string; roomId: string; summary: string; finalDecision: PilotCloseoutDecision; v41InstitutionalHandoffPreparation: true; simulated_only: true; metadata_only: true; human_review_required: true }
