export type SenseTrustOperatingModelStatusType = 'draft' | 'ready_for_review' | 'operating_model_reviewed' | 'scale_simulation_ready' | 'refine_required' | 'paused' | 'blocked' | 'revoked_simulated'
export type SenseTrustOperatingCadenceType = 'weekly_governance' | 'monthly_review' | 'quarterly_scale_gate' | 'risk_review' | 'human_review' | 'executive_review' | 'legal_review_pending' | 'regulatory_review_pending'
export type SenseTrustScaleOperatingDecisionType = 'go' | 'pause' | 'refine' | 'scale_simulated' | 'block' | 'require_legal_review' | 'require_regulatory_review' | 'require_human_review'
export type SenseTrustScaleOperatingRiskLevel = 'low' | 'medium' | 'high' | 'critical'
export type SenseTrustScaleOperatingRoleType = 'owner' | 'accountable' | 'reviewer' | 'contributor' | 'observer' | 'legal_pending' | 'regulatory_pending' | 'technical_owner' | 'clinical_governance_reviewer' | 'institutional_sponsor'
export type SenseTrustScaleExecutionStatusType = 'planned' | 'ready_for_review' | 'in_simulated_execution' | 'blocked' | 'paused' | 'completed_simulated' | 'requires_human_review'

export interface SenseTrustScaleOperatingCadenceItem { cadence_item_id: string; cadence_id: string; cadence_type: SenseTrustOperatingCadenceType; title: string; cadence_frequency: string; required_reviews: string[]; metadata_only: true; real_meeting_claim: false; simulated_only: true }
export interface SenseTrustScaleOperatingCadence { cadence_id: string; operating_model_id: string; cadence_title: string; cadence_items: SenseTrustScaleOperatingCadenceItem[]; cadence_summary: string; cadence_risk_level: SenseTrustScaleOperatingRiskLevel; metadata_only: true; real_meeting_claim: false; legal_obligation_claim: false; simulated_only: true }
export interface SenseTrustScaleRaciRole { role_id: string; raci_matrix_id: string; role_type: SenseTrustScaleOperatingRoleType; role_label: string; responsibility_summary: string; metadata_only: true; legal_responsibility_claim: false; employment_obligation_claim: false; simulated_only: true }
export interface SenseTrustScaleRaciMatrix { raci_matrix_id: string; operating_model_id: string; roles: SenseTrustScaleRaciRole[]; accountability_summary: string; unresolved_responsibilities: string[]; human_review_required: true; metadata_only: true; legal_responsibility_claim: false; employment_obligation_claim: false; simulated_only: true }
export interface SenseTrustScaleEntryCriterion { criterion_id: string; matrix_id: string; title: string; readiness_score: number; status: SenseTrustScaleExecutionStatusType; simulated_only: true }
export interface SenseTrustScaleExitCriterion { criterion_id: string; matrix_id: string; title: string; completion_score: number; status: SenseTrustScaleExecutionStatusType; simulated_only: true }
export interface SenseTrustScaleEntryExitCriteriaMatrix { matrix_id: string; operating_model_id: string; entry_criteria: SenseTrustScaleEntryCriterion[]; exit_criteria: SenseTrustScaleExitCriterion[]; metadata_only: true; contractual_clause_claim: false; simulated_only: true }
export interface SenseTrustInstitutionalExecutionPlanItem { execution_item_id: string; execution_plan_id: string; title: string; status: SenseTrustScaleExecutionStatusType; owner_role: string; blocked_reason: string | null; simulated_only: true }
export interface SenseTrustInstitutionalExecutionPlan { execution_plan_id: string; operating_model_id: string; execution_items: SenseTrustInstitutionalExecutionPlanItem[]; execution_summary: string; blocked_items: string[]; required_reviews: string[]; readiness_score: number; metadata_only: true; contractual_commitment_claim: false; real_operational_commitment_claim: false; simulated_only: true }
export interface SenseTrustScaleGovernanceCalendarItem { calendar_item_id: string; calendar_id: string; cadence_type: SenseTrustOperatingCadenceType; title: string; due_window_simulated: string; metadata_only: true; real_calendar_claim: false; simulated_only: true }
export interface SenseTrustScaleGovernanceCalendar { calendar_id: string; operating_model_id: string; calendar_items: SenseTrustScaleGovernanceCalendarItem[]; calendar_summary: string; metadata_only: true; real_calendar_claim: false; simulated_only: true }
export interface SenseTrustScaleRiskItem { risk_item_id: string; risk_register_id: string; risk_title: string; risk_level: SenseTrustScaleOperatingRiskLevel; mitigation: string; legal_or_regulatory_opinion_claim: false; simulated_only: true }
export interface SenseTrustScaleRiskRegister { risk_register_id: string; operating_model_id: string; risk_items: SenseTrustScaleRiskItem[]; highest_risk_level: SenseTrustScaleOperatingRiskLevel; metadata_only: true; legal_or_regulatory_opinion_claim: false; simulated_only: true }
export interface SenseTrustScaleDecisionLogItem { decision_log_item_id: string; operating_model_id: string; decision_type: SenseTrustScaleOperatingDecisionType; decision_reason: string; required_reviews: string[]; blocked_actions: string[]; next_action: string; decision_hash: string; previous_decision_hash: string | null; timestamp_simulated: string; metadata_only: true; legal_decision_claim: false; regulatory_authorization_claim: false; commercial_commitment_claim: false; simulated_only: true }
export interface SenseTrustScaleDecisionLog { decision_log_id: string; operating_model_id: string; decision_items: SenseTrustScaleDecisionLogItem[]; metadata_only: true; simulated_only: true }
export interface SenseTrustOperationalControlBoard { control_board_id: string; operating_model_id: string; board_summary: string; active_controls: string[]; blocked_actions: string[]; metadata_only: true; real_operation_claim: false; simulated_only: true }
export interface SenseTrustHumanReviewEscalationItem { escalation_item_id: string; escalation_path_id: string; trigger: string; reviewer_role: string; escalation_reason: string; simulated_only: true }
export interface SenseTrustHumanReviewEscalationPath { escalation_path_id: string; operating_model_id: string; escalation_items: SenseTrustHumanReviewEscalationItem[]; review_summary: string; metadata_only: true; real_regulatory_process_claim: false; simulated_only: true }
export interface SenseTrustScaleReadinessScorecard { scorecard_id: string; operating_model_id: string; operating_readiness_score: number; cadence_coverage_score: number; raci_completeness_score: number; entry_exit_score: number; execution_plan_score: number; human_review_score: number; recommended_decision: SenseTrustScaleOperatingDecisionType; metadata_only: true; simulated_only: true }
export interface SenseTrustOperatingModelMisuseBlocker { blocker_id: string; blocked_misuse: string; risk: SenseTrustScaleOperatingRiskLevel; blocked_action: string; safe_language: string; simulated_only: true }
export interface SenseTrustStrategicScaleOperatingExecutiveReport { report_id: string; operating_model_id: string; executive_summary: string; recommended_decision: SenseTrustScaleOperatingDecisionType; cadence_summary: string; raci_summary: string; risk_summary: string; human_review_summary: string; simulated_only: true }
export interface SenseTrustStrategicScaleOperatingModel { operating_model_id: string; scale_gate_id: string; readiness_gate_id: string; closeout_id: string; operating_model_title: string; operating_model_status: SenseTrustOperatingModelStatusType; operating_cadence_id: string; raci_matrix_id: string; entry_exit_criteria_matrix_id: string; institutional_execution_plan_id: string; governance_calendar_id: string; scale_risk_register_id: string; scale_decision_log_id: string; operational_control_board_id: string; human_review_escalation_path_id: string; scale_readiness_scorecard_id: string; executive_report_id: string; recommended_operating_decision: SenseTrustScaleOperatingDecisionType; blocked_actions: string[]; required_reviews: string[]; logical_operating_model_hash: string; previous_operating_model_hash: string | null; metadata_only: true; contains_clinical_data: false; contains_patient_data: false; contains_personal_sensitive_data: false; real_clinical_operation_claim: false; contract_binding_claim: false; client_claim: false; partnership_claim: false; regulatory_validation_claim: false; diagnostic_truth_certification_claim: false; real_revenue_claim: false; real_billing_claim: false; simulated_only: true }
export interface SenseTrustStrategicScaleOperatingModelState { state_id: string; version: 'v3.1'; operating_models: SenseTrustStrategicScaleOperatingModel[]; operating_cadences: SenseTrustScaleOperatingCadence[]; cadence_items: SenseTrustScaleOperatingCadenceItem[]; raci_matrices: SenseTrustScaleRaciMatrix[]; raci_roles: SenseTrustScaleRaciRole[]; entry_exit_criteria_matrices: SenseTrustScaleEntryExitCriteriaMatrix[]; entry_criteria: SenseTrustScaleEntryCriterion[]; exit_criteria: SenseTrustScaleExitCriterion[]; execution_plans: SenseTrustInstitutionalExecutionPlan[]; execution_plan_items: SenseTrustInstitutionalExecutionPlanItem[]; governance_calendars: SenseTrustScaleGovernanceCalendar[]; governance_calendar_items: SenseTrustScaleGovernanceCalendarItem[]; risk_registers: SenseTrustScaleRiskRegister[]; risk_items: SenseTrustScaleRiskItem[]; decision_logs: SenseTrustScaleDecisionLog[]; decision_log_items: SenseTrustScaleDecisionLogItem[]; operational_control_boards: SenseTrustOperationalControlBoard[]; human_review_escalation_paths: SenseTrustHumanReviewEscalationPath[]; human_review_escalation_items: SenseTrustHumanReviewEscalationItem[]; readiness_scorecards: SenseTrustScaleReadinessScorecard[]; misuse_blockers: SenseTrustOperatingModelMisuseBlocker[]; executive_reports: SenseTrustStrategicScaleOperatingExecutiveReport[]; references: string[]; metadata_only: true; clinical_data_used: false; patient_data_used: false; personal_sensitive_data_used: false; real_clinical_operation_claimed: false; contract_binding_claimed: false; client_claim: false; partnership_claim: false; regulatory_validation_claim: false; diagnostic_truth_certification_claimed: false; real_revenue_claimed: false; real_billing_claimed: false; legal_obligation_claimed: false; commercial_commitment_claimed: false; simulated_only: true }
export interface SenseTrustStrategicScaleOperatingExportPayload { schema: 'sensetrust.strategic_scale_operating_export.v1'; exported_at: string; state: SenseTrustStrategicScaleOperatingModelState; public_exposure: 'metadata_only'; simulated_only: true }
export interface SenseTrustStrategicScaleOperatingValidationResult { valid: boolean; errors: string[] }
