export type PilotMonitoringStage = 'intake_ready' | 'evidence_pending' | 'evidence_under_review' | 'checkpoint_monitoring' | 'deviation_detected' | 'human_review_required' | 'pause_recommended' | 'refine_recommended' | 'stop_recommended' | 'closeout_ready'
export type PilotEvidenceType = 'document' | 'meeting_record' | 'checkpoint_record' | 'governance_note' | 'risk_signal' | 'deviation_report' | 'stakeholder_feedback' | 'simulated_metadata' | 'audit_log' | 'decision_note'
export type PilotEvidenceStatus = 'pending' | 'received' | 'incomplete' | 'under_review' | 'accepted' | 'rejected' | 'requires_human_review'
export type PilotMonitoringSignalLevel = 'neutral' | 'attention' | 'warning' | 'critical' | 'blocked'
export type PilotMonitoringDecisionSignal = 'continue_monitoring' | 'request_more_evidence' | 'escalate_human_review' | 'recommend_pause' | 'recommend_refine' | 'recommend_stop' | 'prepare_closeout'
export type PilotEvidenceIntegrityStatus = 'intact' | 'incomplete' | 'inconsistent' | 'unverifiable' | 'blocked'
export type PilotEvidenceReviewStatus = PilotEvidenceStatus
export type PilotEvidenceClassification = PilotEvidenceType

export interface PilotMonitoringGuardrails { simulated_only: true; metadata_only: true; human_review_required: true; contains_clinical_data: false; contains_patient_data: false; contains_personal_sensitive_data: false; real_clinical_operation_claim: false; real_pilot_execution_claim: false; real_evidence_collection_claim: false; real_biological_sample_claim: false; real_eeg_claim: false; real_qeeg_claim: false; real_biomarker_claim: false; real_client_claim: false; real_contract_claim: false; real_partnership_claim: false; real_billing_claim: false; real_revenue_claim: false; real_crm_claim: false; real_email_automation_claim: false; legal_signature_claim: false; regulatory_authorization_claim: false; scientific_validation_claim: false; external_certification_claim: false; diagnostic_truth_certification_claim: false; treatment_claim: false; outcome_guarantee_claim: false; public_health_claim: false }
export interface StrategicPilotMonitoringEvidenceIntakeRoom extends PilotMonitoringGuardrails { roomId: string; simulatedOrganizationName: string; linkedV38ExecutionGovernanceRoomId: string; linkedV37ProposalRoomId: string; linkedV36ConversionRoomId: string; linkedV12LeanFreezeReference: string; monitoringStage: PilotMonitoringStage; monitoringReadinessScore: number; evidenceIntakeCompletenessScore: number; evidenceIntegrityScore: number; checkpointComplianceScore: number; deviationBurdenScore: number; riskSignalScore: number; decisionSignal: PilotMonitoringDecisionSignal; v40CloseoutPreparation: true }
export interface StrategicPilotMonitoringScenario extends StrategicPilotMonitoringEvidenceIntakeRoom { monitoringEvents: PilotMonitoringEvent[]; evidenceIntakeQueue: PilotEvidenceIntakeQueue; evidenceIntakeRecords: PilotEvidenceIntakeRecord[]; checkpointMonitoringRecords: PilotCheckpointMonitoringRecord[]; monitoringTimeline: PilotMonitoringTimeline; deviationSignals: PilotDeviationSignal[]; deviationEscalations: PilotDeviationEscalation[]; riskSignalUpdates: PilotRiskSignalUpdate[]; monitoringRiskRegister: PilotMonitoringRiskRegister; decisionTriggers: PilotDecisionTrigger[]; humanReviewTriggers: PilotHumanReviewTrigger[]; evidenceIntegrityChecks: PilotEvidenceIntegrityCheck[]; evidenceChainOfCustody: PilotEvidenceChainOfCustody; monitoringAuditTrail: PilotMonitoringAuditTrail; dashboardMetrics: PilotMonitoringDashboardMetric[]; executiveReport: PilotMonitoringExecutiveReport }
export interface PilotMonitoringState extends PilotMonitoringGuardrails { version: 'v3.9'; rooms: StrategicPilotMonitoringEvidenceIntakeRoom[]; scenarios: StrategicPilotMonitoringScenario[]; monitoringEvents: PilotMonitoringEvent[]; evidenceIntakeQueues: PilotEvidenceIntakeQueue[]; evidenceIntakeRecords: PilotEvidenceIntakeRecord[]; checkpointMonitoringRecords: PilotCheckpointMonitoringRecord[]; monitoringTimelines: PilotMonitoringTimeline[]; deviationSignals: PilotDeviationSignal[]; deviationEscalations: PilotDeviationEscalation[]; riskSignalUpdates: PilotRiskSignalUpdate[]; monitoringRiskRegisters: PilotMonitoringRiskRegister[]; riskItems: PilotMonitoringRiskItem[]; decisionTriggers: PilotDecisionTrigger[]; humanReviewTriggers: PilotHumanReviewTrigger[]; evidenceIntegrityChecks: PilotEvidenceIntegrityCheck[]; evidenceChainOfCustody: PilotEvidenceChainOfCustody[]; monitoringAuditTrails: PilotMonitoringAuditTrail[]; dashboardMetrics: PilotMonitoringDashboardMetric[]; executiveReports: PilotMonitoringExecutiveReport[]; v40CloseoutPreparation: true }
export interface PilotMonitoringEvent { id: string; roomId: string; label: string; signalLevel: PilotMonitoringSignalLevel; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PilotEvidenceIntakeRecord { id: string; queueId: string; evidenceType: PilotEvidenceType; title: string; status: PilotEvidenceStatus; integrityStatus: PilotEvidenceIntegrityStatus; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PilotEvidenceIntakeQueue { id: string; roomId: string; records: PilotEvidenceIntakeRecord[]; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PilotCheckpointSignal { id: string; label: string; signalLevel: PilotMonitoringSignalLevel; simulated_only: true; metadata_only: true }
export interface PilotCheckpointMonitoringRecord { id: string; roomId: string; checkpointLabel: string; status: PilotEvidenceStatus; signals: PilotCheckpointSignal[]; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PilotMonitoringTimeline { id: string; roomId: string; events: string[]; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PilotDeviationSignal { id: string; roomId: string; label: string; signalLevel: PilotMonitoringSignalLevel; decisionSignal: PilotMonitoringDecisionSignal; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PilotDeviationEscalation { id: string; roomId: string; reason: string; decisionSignal: PilotMonitoringDecisionSignal; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PilotRiskSignalUpdate { id: string; roomId: string; title: string; signalLevel: PilotMonitoringSignalLevel; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PilotMonitoringRiskItem { id: string; title: string; signalLevel: PilotMonitoringSignalLevel; mitigation: string; simulated_only: true; metadata_only: true }
export interface PilotMonitoringRiskRegister { id: string; roomId: string; items: PilotMonitoringRiskItem[]; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PilotDecisionTrigger { id: string; roomId: string; trigger: string; decisionSignal: PilotMonitoringDecisionSignal; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PilotHumanReviewTrigger { id: string; roomId: string; reason: string; signalLevel: PilotMonitoringSignalLevel; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PilotEvidenceIntegrityCheck { id: string; roomId: string; title: string; integrityStatus: PilotEvidenceIntegrityStatus; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PilotEvidenceChainOfCustody { id: string; roomId: string; custodyEvents: string[]; simulated_only: true; metadata_only: true; human_review_required: true }
export interface PilotMonitoringAuditTrail { id: string; roomId: string; events: string[]; append_only_simulated: true; simulated_only: true; metadata_only: true }
export interface PilotMonitoringDashboardMetric { id: string; label: string; value: number; simulated_only: true; metadata_only: true }
export interface PilotMonitoringExecutiveReport { id: string; roomId: string; summary: string; decisionSignal: PilotMonitoringDecisionSignal; v40CloseoutPreparation: true; simulated_only: true; metadata_only: true; human_review_required: true }
