export type SenseTrustPartnershipConversionStage = 'not_started' | 'engagement_reviewed' | 'intent_mapped' | 'qualification_review' | 'due_diligence_ready' | 'legal_review_required' | 'scientific_review_required' | 'regulatory_review_required' | 'human_review_required' | 'decision_ready' | 'paused' | 'blocked' | 'closed_simulated'
export type SenseTrustPartnershipConversionStatus = 'draft' | 'ready_for_review' | 'conversion_candidate' | 'intent_registered' | 'due_diligence_ready' | 'review_pending' | 'refine_required' | 'paused' | 'blocked' | 'revoked_simulated'
export type SenseTrustConversionDecision = 'go' | 'pause' | 'refine' | 'prepare_non_binding_brief' | 'require_human_review' | 'require_legal_review' | 'require_regulatory_review' | 'require_scientific_review' | 'block'
export type SenseTrustConversionRiskLevel = 'low' | 'medium' | 'high' | 'critical'
export type SenseTrustConversionConfidenceLevel = 'low' | 'medium' | 'high' | 'simulated_only'
export type SenseTrustReviewRoutingType = 'human_review' | 'legal_review' | 'regulatory_review' | 'scientific_review' | 'executive_review' | 'commercial_review' | 'ethics_review'
export type SenseTrustConversionPartnerType = 'clinic_network' | 'public_sector' | 'education_network' | 'legal_partner' | 'research_partner' | 'enterprise_partner' | 'government_partner' | 'investor_partner' | 'internal_strategy'

export interface SenseTrustStrategicPartnershipConversionDecisionRoom { partnership_conversion_decision_room_id: string; partner_engagement_control_room_id: string; partner_readiness_room_id: string; evidence_simulator_id: string; simulation_console_id: string; operating_model_id: string; room_title: string; conversion_status: SenseTrustPartnershipConversionStatus; conversion_candidate_count: number; qualification_matrix_id: string; non_binding_intent_register_id: string; due_diligence_readiness_board_id: string; legal_review_routing_board_id: string; scientific_review_routing_board_id: string; regulatory_review_routing_board_id: string; conversion_risk_register_id: string; conversion_decision_board_id: string; conversion_readiness_scorecard_id: string; human_review_conversion_queue_id: string; boundary_claims_guardrail_id: string; conversion_audit_trail_id: string; executive_report_id: string; recommended_conversion_decision: SenseTrustConversionDecision; blocked_actions: string[]; required_reviews: string[]; logical_partnership_conversion_hash: string; previous_partnership_conversion_hash: string | null; metadata_only: true; contains_clinical_data: false; contains_patient_data: false; contains_personal_sensitive_data: false; real_clinical_operation_claim: false; contract_binding_claim: false; client_claim: false; partnership_claim: false; regulatory_validation_claim: false; diagnostic_truth_certification_claim: false; real_revenue_claim: false; real_billing_claim: false; real_impact_claim: false; real_capacity_claim: false; real_scientific_validation_claim: false; external_certification_claim: false; real_crm_claim: false; real_email_automation_claim: false; binding_proposal_claim: false; commercial_commitment_claim: false; legal_commitment_claim: false; simulated_only: true }
export interface SenseTrustPartnershipConversionCandidate { partnership_conversion_candidate_id: string; partnership_conversion_decision_room_id: string; partner_engagement_track_id: string; partner_profile_id: string; partner_type: SenseTrustConversionPartnerType; partner_label: string; conversion_stage: SenseTrustPartnershipConversionStage; conversion_status: SenseTrustPartnershipConversionStatus; qualification_score: number; due_diligence_readiness_score: number; conversion_risk_level: SenseTrustConversionRiskLevel; conversion_confidence_level: SenseTrustConversionConfidenceLevel; recommended_conversion_decision: SenseTrustConversionDecision; required_reviews: string[]; blocked_actions: string[]; metadata_only: true; real_partner_claim: false; client_claim: false; contract_binding_claim: false; partnership_claim: false; commercial_commitment_claim: false; regulatory_authorization_claim: false; binding_proposal_claim: false; legal_commitment_claim: false; real_outreach_claim: false; simulated_only: true }
export interface SenseTrustConversionQualificationMatrixItem { qualification_item_id: string; qualification_matrix_id: string; dimension: string; score: number; simulated_only: true }
export interface SenseTrustConversionQualificationMatrix { qualification_matrix_id: string; partnership_conversion_decision_room_id: string; items: SenseTrustConversionQualificationMatrixItem[]; metadata_only: true; simulated_only: true }
export interface SenseTrustNonBindingIntentItem { intent_item_id: string; non_binding_intent_register_id: string; intent_signal: string; confidence: SenseTrustConversionConfidenceLevel; simulated_only: true }
export interface SenseTrustNonBindingIntentRegister { non_binding_intent_register_id: string; partnership_conversion_decision_room_id: string; items: SenseTrustNonBindingIntentItem[]; metadata_only: true; binding_proposal_claim: false; legal_commitment_claim: false; simulated_only: true }
export interface SenseTrustPartnershipDueDiligenceReadinessItem { due_diligence_item_id: string; due_diligence_readiness_board_id: string; title: string; status: SenseTrustPartnershipConversionStatus; simulated_only: true }
export interface SenseTrustPartnershipDueDiligenceReadinessBoard { due_diligence_readiness_board_id: string; partnership_conversion_decision_room_id: string; items: SenseTrustPartnershipDueDiligenceReadinessItem[]; readiness_score: number; metadata_only: true; real_due_diligence_claim: false; simulated_only: true }
export interface SenseTrustLegalReviewRoutingItem { legal_review_item_id: string; legal_review_routing_board_id: string; routing_type: SenseTrustReviewRoutingType; reason: string; simulated_only: true }
export interface SenseTrustLegalReviewRoutingBoard { legal_review_routing_board_id: string; partnership_conversion_decision_room_id: string; items: SenseTrustLegalReviewRoutingItem[]; metadata_only: true; legal_opinion_claim: false; simulated_only: true }
export interface SenseTrustScientificReviewRoutingItem { scientific_review_item_id: string; scientific_review_routing_board_id: string; routing_type: SenseTrustReviewRoutingType; reason: string; simulated_only: true }
export interface SenseTrustScientificReviewRoutingBoard { scientific_review_routing_board_id: string; partnership_conversion_decision_room_id: string; items: SenseTrustScientificReviewRoutingItem[]; metadata_only: true; scientific_validation_claim: false; simulated_only: true }
export interface SenseTrustRegulatoryReviewRoutingItem { regulatory_review_item_id: string; regulatory_review_routing_board_id: string; routing_type: SenseTrustReviewRoutingType; reason: string; simulated_only: true }
export interface SenseTrustRegulatoryReviewRoutingBoard { regulatory_review_routing_board_id: string; partnership_conversion_decision_room_id: string; items: SenseTrustRegulatoryReviewRoutingItem[]; metadata_only: true; regulatory_authorization_claim: false; simulated_only: true }
export interface SenseTrustConversionRiskItem { conversion_risk_item_id: string; conversion_risk_register_id: string; risk_title: string; risk_level: SenseTrustConversionRiskLevel; mitigation: string; simulated_only: true }
export interface SenseTrustConversionRiskRegister { conversion_risk_register_id: string; partnership_conversion_decision_room_id: string; items: SenseTrustConversionRiskItem[]; highest_risk_level: SenseTrustConversionRiskLevel; metadata_only: true; simulated_only: true }
export interface SenseTrustConversionDecisionItem { conversion_decision_item_id: string; conversion_decision_board_id: string; decision: SenseTrustConversionDecision; rationale: string; simulated_only: true }
export interface SenseTrustConversionDecisionBoard { conversion_decision_board_id: string; partnership_conversion_decision_room_id: string; items: SenseTrustConversionDecisionItem[]; metadata_only: true; binding_decision_claim: false; simulated_only: true }
export interface SenseTrustConversionReadinessScoreItem { score_item_id: string; conversion_readiness_scorecard_id: string; dimension: string; score: number; confidence: SenseTrustConversionConfidenceLevel; simulated_only: true }
export interface SenseTrustConversionReadinessScorecard { conversion_readiness_scorecard_id: string; partnership_conversion_decision_room_id: string; items: SenseTrustConversionReadinessScoreItem[]; aggregate_score: number; recommended_decision: SenseTrustConversionDecision; metadata_only: true; simulated_only: true }
export interface SenseTrustHumanReviewConversionQueueItem { queue_item_id: string; human_review_conversion_queue_id: string; reason: string; reviewer_role: string; simulated_only: true }
export interface SenseTrustHumanReviewConversionQueue { human_review_conversion_queue_id: string; partnership_conversion_decision_room_id: string; items: SenseTrustHumanReviewConversionQueueItem[]; metadata_only: true; simulated_only: true }
export interface SenseTrustConversionBoundaryClaimsGuardrailItem { guardrail_item_id: string; boundary_claims_guardrail_id: string; prohibited_claim: string; safe_language: string; simulated_only: true }
export interface SenseTrustConversionBoundaryClaimsGuardrail { boundary_claims_guardrail_id: string; partnership_conversion_decision_room_id: string; items: SenseTrustConversionBoundaryClaimsGuardrailItem[]; metadata_only: true; simulated_only: true }
export interface SenseTrustConversionAuditTrailItem { audit_trail_item_id: string; conversion_audit_trail_id: string; action: string; actor_role: string; simulated_only: true }
export interface SenseTrustConversionAuditTrail { conversion_audit_trail_id: string; partnership_conversion_decision_room_id: string; items: SenseTrustConversionAuditTrailItem[]; metadata_only: true; append_only_simulated: true; simulated_only: true }
export interface SenseTrustStrategicPartnershipConversionExecutiveReport { report_id: string; partnership_conversion_decision_room_id: string; executive_summary: string; recommended_decision: SenseTrustConversionDecision; qualification_summary: string; diligence_summary: string; risk_summary: string; human_review_summary: string; simulated_only: true }
export interface SenseTrustStrategicPartnershipConversionDecisionRoomState { state_id: string; version: 'v3.6'; rooms: SenseTrustStrategicPartnershipConversionDecisionRoom[]; candidates: SenseTrustPartnershipConversionCandidate[]; qualification_matrices: SenseTrustConversionQualificationMatrix[]; qualification_matrix_items: SenseTrustConversionQualificationMatrixItem[]; intent_registers: SenseTrustNonBindingIntentRegister[]; intent_items: SenseTrustNonBindingIntentItem[]; due_diligence_boards: SenseTrustPartnershipDueDiligenceReadinessBoard[]; due_diligence_items: SenseTrustPartnershipDueDiligenceReadinessItem[]; legal_review_boards: SenseTrustLegalReviewRoutingBoard[]; legal_review_items: SenseTrustLegalReviewRoutingItem[]; scientific_review_boards: SenseTrustScientificReviewRoutingBoard[]; scientific_review_items: SenseTrustScientificReviewRoutingItem[]; regulatory_review_boards: SenseTrustRegulatoryReviewRoutingBoard[]; regulatory_review_items: SenseTrustRegulatoryReviewRoutingItem[]; risk_registers: SenseTrustConversionRiskRegister[]; risk_items: SenseTrustConversionRiskItem[]; decision_boards: SenseTrustConversionDecisionBoard[]; decision_items: SenseTrustConversionDecisionItem[]; readiness_scorecards: SenseTrustConversionReadinessScorecard[]; readiness_score_items: SenseTrustConversionReadinessScoreItem[]; human_review_queues: SenseTrustHumanReviewConversionQueue[]; human_review_queue_items: SenseTrustHumanReviewConversionQueueItem[]; boundary_claims_guardrails: SenseTrustConversionBoundaryClaimsGuardrail[]; boundary_claims_guardrail_items: SenseTrustConversionBoundaryClaimsGuardrailItem[]; audit_trails: SenseTrustConversionAuditTrail[]; audit_trail_items: SenseTrustConversionAuditTrailItem[]; executive_reports: SenseTrustStrategicPartnershipConversionExecutiveReport[]; references: string[]; metadata_only: true; clinical_data_used: false; patient_data_used: false; personal_sensitive_data_used: false; real_clinical_operation_claimed: false; contract_binding_claimed: false; client_claim: false; partnership_claim: false; regulatory_validation_claim: false; diagnostic_truth_certification_claimed: false; real_revenue_claimed: false; real_billing_claimed: false; real_impact_claimed: false; real_capacity_claimed: false; real_scientific_validation_claimed: false; external_certification_claimed: false; real_crm_claimed: false; real_email_automation_claimed: false; binding_proposal_claimed: false; commercial_commitment_claimed: false; legal_commitment_claimed: false; simulated_only: true }
export interface SenseTrustStrategicPartnershipConversionExportPayload { schema: 'sensetrust.strategic_partnership_conversion_export.v1'; exported_at: string; state: SenseTrustStrategicPartnershipConversionDecisionRoomState; public_exposure: 'metadata_only'; simulated_only: true }
export interface SenseTrustStrategicPartnershipConversionValidationResult { valid: boolean; errors: string[] }
