export type SenseTrustPartnerType = 'clinic_network' | 'public_sector' | 'education_network' | 'legal_partner' | 'research_partner' | 'enterprise_partner' | 'government_partner' | 'investor_partner' | 'internal_strategy'
export type SenseTrustPartnerReadinessStatus = 'draft' | 'ready_for_review' | 'partner_profile_ready' | 'evidence_brief_ready' | 'diligence_ready' | 'refine_required' | 'paused' | 'blocked' | 'revoked_simulated'
export type SenseTrustPartnerFitLevel = 'low' | 'moderate' | 'strong' | 'strategic' | 'uncertain'
export type SenseTrustPartnerRiskLevel = 'low' | 'medium' | 'high' | 'critical'
export type SenseTrustPartnerDecisionType = 'go' | 'pause' | 'refine' | 'prepare_brief' | 'require_human_review' | 'require_legal_review' | 'require_regulatory_review' | 'require_scientific_review' | 'block'
export type SenseTrustPartnerConfidenceLevel = 'low' | 'medium' | 'high' | 'simulated_only'

export interface SenseTrustPartnerFitMatrixItem { fit_item_id: string; partner_fit_matrix_id: string; partner_type: SenseTrustPartnerType; fit_score: number; fit_level: SenseTrustPartnerFitLevel; rationale: string; simulated_only: true }
export interface SenseTrustPartnerFitMatrix { partner_fit_matrix_id: string; partner_readiness_room_id: string; items: SenseTrustPartnerFitMatrixItem[]; recommended_partner_type: SenseTrustPartnerType; metadata_only: true; simulated_only: true }
export interface SenseTrustStrategicDiligenceChecklistItem { diligence_item_id: string; diligence_checklist_id: string; title: string; status: SenseTrustPartnerReadinessStatus; required_review: string; simulated_only: true }
export interface SenseTrustStrategicDiligenceChecklist { diligence_checklist_id: string; partner_readiness_room_id: string; items: SenseTrustStrategicDiligenceChecklistItem[]; completion_score: number; metadata_only: true; real_due_diligence_claim: false; simulated_only: true }
export interface SenseTrustPartnerEvidenceBriefItem { brief_item_id: string; partner_evidence_brief_id: string; title: string; source: string; strength: string; simulated_only: true }
export interface SenseTrustPartnerEvidenceBrief { partner_evidence_brief_id: string; partner_profile_id: string; evidence_simulator_id: string; brief_title: string; brief_summary: string; evidence_items: SenseTrustPartnerEvidenceBriefItem[]; evidence_gaps: string[]; proof_risks: string[]; recommended_talk_track: string; prohibited_claims: string[]; required_disclaimers: string[]; metadata_only: true; clinical_evidence_claim: false; scientific_validation_claim: false; regulatory_validation_claim: false; external_certification_claim: false; simulated_only: true }
export interface SenseTrustPartnerObjectionItem { objection_item_id: string; partner_objection_map_id: string; objection: string; response: string; risk_level: SenseTrustPartnerRiskLevel; simulated_only: true }
export interface SenseTrustPartnerObjectionMap { partner_objection_map_id: string; partner_readiness_room_id: string; items: SenseTrustPartnerObjectionItem[]; metadata_only: true; simulated_only: true }
export interface SenseTrustPartnerRiskReviewItem { risk_item_id: string; partner_risk_review_board_id: string; risk_title: string; risk_level: SenseTrustPartnerRiskLevel; mitigation: string; simulated_only: true }
export interface SenseTrustPartnerRiskReviewBoard { partner_risk_review_board_id: string; partner_readiness_room_id: string; items: SenseTrustPartnerRiskReviewItem[]; highest_risk_level: SenseTrustPartnerRiskLevel; metadata_only: true; legal_or_regulatory_opinion_claim: false; simulated_only: true }
export interface SenseTrustPartnerReadinessScoreItem { score_item_id: string; partner_readiness_scorecard_id: string; dimension: string; score: number; confidence: SenseTrustPartnerConfidenceLevel; simulated_only: true }
export interface SenseTrustPartnerReadinessScorecard { partner_readiness_scorecard_id: string; partner_readiness_room_id: string; items: SenseTrustPartnerReadinessScoreItem[]; aggregate_score: number; recommended_decision: SenseTrustPartnerDecisionType; metadata_only: true; simulated_only: true }
export interface SenseTrustPartnerDecisionPathwayItem { pathway_item_id: string; partner_decision_pathway_id: string; decision: SenseTrustPartnerDecisionType; reason: string; required_review: string; simulated_only: true }
export interface SenseTrustPartnerDecisionPathway { partner_decision_pathway_id: string; partner_readiness_room_id: string; items: SenseTrustPartnerDecisionPathwayItem[]; metadata_only: true; binding_decision_claim: false; simulated_only: true }
export interface SenseTrustPartnerHumanReviewQueueItem { queue_item_id: string; partner_human_review_queue_id: string; partner_profile_id: string; review_reason: string; reviewer_role: string; simulated_only: true }
export interface SenseTrustPartnerHumanReviewQueue { partner_human_review_queue_id: string; partner_readiness_room_id: string; items: SenseTrustPartnerHumanReviewQueueItem[]; metadata_only: true; real_regulatory_process_claim: false; simulated_only: true }
export interface SenseTrustPartnerMeetingPreparationItem { prep_item_id: string; partner_meeting_preparation_kit_id: string; title: string; safe_talk_track: string; simulated_only: true }
export interface SenseTrustPartnerMeetingPreparationKit { partner_meeting_preparation_kit_id: string; partner_readiness_room_id: string; items: SenseTrustPartnerMeetingPreparationItem[]; metadata_only: true; real_meeting_claim: false; simulated_only: true }
export interface SenseTrustPartnerFollowUpGovernanceItem { follow_up_item_id: string; partner_follow_up_governance_id: string; action: string; owner_role: string; simulated_only: true }
export interface SenseTrustPartnerFollowUpGovernance { partner_follow_up_governance_id: string; partner_readiness_room_id: string; items: SenseTrustPartnerFollowUpGovernanceItem[]; metadata_only: true; real_crm_claim: false; real_email_claim: false; simulated_only: true }
export interface SenseTrustPartnerMisuseBlocker { blocker_id: string; blocked_misuse: string; risk: SenseTrustPartnerRiskLevel; blocked_action: string; safe_language: string; simulated_only: true }
export interface SenseTrustStrategicPartnerReadinessExecutiveReport { report_id: string; partner_readiness_room_id: string; executive_summary: string; recommended_decision: SenseTrustPartnerDecisionType; fit_summary: string; diligence_summary: string; risk_summary: string; human_review_summary: string; simulated_only: true }
export interface SenseTrustPartnerReadinessProfile { partner_profile_id: string; partner_readiness_room_id: string; partner_type: SenseTrustPartnerType; partner_label: string; partner_context: string; expected_value_hypothesis: string; strategic_fit_level: SenseTrustPartnerFitLevel; partner_risk_level: SenseTrustPartnerRiskLevel; partner_confidence_level: SenseTrustPartnerConfidenceLevel; recommended_decision: SenseTrustPartnerDecisionType; evidence_brief_id: string; diligence_status: SenseTrustPartnerReadinessStatus; required_reviews: string[]; blocked_actions: string[]; metadata_only: true; real_partner_claim: false; client_claim: false; contract_binding_claim: false; partnership_claim: false; commercial_commitment_claim: false; regulatory_authorization_claim: false; simulated_only: true }
export interface SenseTrustStrategicPartnerReadinessRoom { partner_readiness_room_id: string; evidence_simulator_id: string; simulation_console_id: string; operating_model_id: string; scale_gate_id: string; readiness_gate_id: string; room_title: string; readiness_status: SenseTrustPartnerReadinessStatus; partner_profile_count: number; partner_fit_matrix_id: string; diligence_checklist_id: string; partner_evidence_brief_id: string; partner_objection_map_id: string; partner_risk_review_board_id: string; partner_readiness_scorecard_id: string; partner_decision_pathway_id: string; partner_human_review_queue_id: string; partner_meeting_preparation_kit_id: string; partner_follow_up_governance_id: string; executive_report_id: string; recommended_partner_decision: SenseTrustPartnerDecisionType; blocked_actions: string[]; required_reviews: string[]; logical_partner_readiness_hash: string; previous_partner_readiness_hash: string | null; metadata_only: true; contains_clinical_data: false; contains_patient_data: false; contains_personal_sensitive_data: false; real_clinical_operation_claim: false; contract_binding_claim: false; client_claim: false; partnership_claim: false; regulatory_validation_claim: false; diagnostic_truth_certification_claim: false; real_revenue_claim: false; real_billing_claim: false; real_impact_claim: false; real_capacity_claim: false; real_scientific_validation_claim: false; external_certification_claim: false; simulated_only: true }
export interface SenseTrustStrategicPartnerReadinessRoomState { state_id: string; version: 'v3.4'; rooms: SenseTrustStrategicPartnerReadinessRoom[]; profiles: SenseTrustPartnerReadinessProfile[]; fit_matrices: SenseTrustPartnerFitMatrix[]; fit_matrix_items: SenseTrustPartnerFitMatrixItem[]; diligence_checklists: SenseTrustStrategicDiligenceChecklist[]; diligence_items: SenseTrustStrategicDiligenceChecklistItem[]; evidence_briefs: SenseTrustPartnerEvidenceBrief[]; evidence_brief_items: SenseTrustPartnerEvidenceBriefItem[]; objection_maps: SenseTrustPartnerObjectionMap[]; objection_items: SenseTrustPartnerObjectionItem[]; risk_review_boards: SenseTrustPartnerRiskReviewBoard[]; risk_review_items: SenseTrustPartnerRiskReviewItem[]; scorecards: SenseTrustPartnerReadinessScorecard[]; score_items: SenseTrustPartnerReadinessScoreItem[]; decision_pathways: SenseTrustPartnerDecisionPathway[]; decision_pathway_items: SenseTrustPartnerDecisionPathwayItem[]; human_review_queues: SenseTrustPartnerHumanReviewQueue[]; human_review_queue_items: SenseTrustPartnerHumanReviewQueueItem[]; meeting_preparation_kits: SenseTrustPartnerMeetingPreparationKit[]; meeting_preparation_items: SenseTrustPartnerMeetingPreparationItem[]; follow_up_governance: SenseTrustPartnerFollowUpGovernance[]; follow_up_governance_items: SenseTrustPartnerFollowUpGovernanceItem[]; misuse_blockers: SenseTrustPartnerMisuseBlocker[]; executive_reports: SenseTrustStrategicPartnerReadinessExecutiveReport[]; references: string[]; metadata_only: true; clinical_data_used: false; patient_data_used: false; personal_sensitive_data_used: false; real_clinical_operation_claimed: false; contract_binding_claimed: false; client_claim: false; partnership_claim: false; regulatory_validation_claim: false; diagnostic_truth_certification_claimed: false; real_revenue_claimed: false; real_billing_claimed: false; real_impact_claimed: false; real_capacity_claimed: false; real_scientific_validation_claimed: false; external_certification_claimed: false; simulated_only: true }
export interface SenseTrustStrategicPartnerReadinessExportPayload { schema: 'sensetrust.strategic_partner_readiness_export.v1'; exported_at: string; state: SenseTrustStrategicPartnerReadinessRoomState; public_exposure: 'metadata_only'; simulated_only: true }
export interface SenseTrustStrategicPartnerReadinessValidationResult { valid: boolean; errors: string[] }
