export type SenseTrustScaleSimulationStatusType = 'draft' | 'ready_for_review' | 'simulation_reviewed' | 'scenario_ready' | 'refine_required' | 'paused' | 'blocked' | 'revoked_simulated'
export type SenseTrustScaleSimulationScenarioType = 'conservative_scale' | 'controlled_scale' | 'accelerated_scale' | 'government_pilot_scale' | 'clinic_network_scale' | 'education_network_scale' | 'research_partner_scale' | 'investor_partner_scale' | 'internal_only_scale'
export type SenseTrustScaleSimulationDecisionType = 'go' | 'pause' | 'refine' | 'scale_simulated' | 'block' | 'require_legal_review' | 'require_regulatory_review' | 'require_human_review'
export type SenseTrustScaleSimulationRiskLevel = 'low' | 'medium' | 'high' | 'critical'
export type SenseTrustScaleSimulationImpactLevel = 'minimal' | 'moderate' | 'significant' | 'high' | 'uncertain'
export type SenseTrustScaleSimulationCapacityLevel = 'insufficient' | 'limited' | 'adequate' | 'strong' | 'excessive_risk'
export type SenseTrustScaleSimulationConfidenceLevel = 'low' | 'medium' | 'high' | 'simulated_only'

export interface SenseTrustScaleSimulationScenarioInput { input_id: string; scenario_id: string; variable_name: string; simulated_value: string; metadata_only: true; simulated_only: true }
export interface SenseTrustScaleSimulationScenarioOutput { output_id: string; scenario_id: string; output_name: string; simulated_value: string; real_impact_claim: false; real_capacity_claim: false; simulated_only: true }
export interface SenseTrustScaleSimulationScenario { scenario_id: string; simulation_console_id: string; scenario_type: SenseTrustScaleSimulationScenarioType; scenario_title: string; scenario_description: string; scenario_inputs: SenseTrustScaleSimulationScenarioInput[]; scenario_outputs: SenseTrustScaleSimulationScenarioOutput[]; scenario_risk_level: SenseTrustScaleSimulationRiskLevel; scenario_impact_level: SenseTrustScaleSimulationImpactLevel; scenario_capacity_level: SenseTrustScaleSimulationCapacityLevel; scenario_confidence_level: SenseTrustScaleSimulationConfidenceLevel; recommended_decision: SenseTrustScaleSimulationDecisionType; required_reviews: string[]; blocked_actions: string[]; metadata_only: true; real_execution_claim: false; contractual_commitment_claim: false; commercial_commitment_claim: false; regulatory_authorization_claim: false; simulated_only: true }
export interface SenseTrustScenarioDecisionItem { decision_item_id: string; scenario_id: string; decision_type: SenseTrustScaleSimulationDecisionType; decision_reason: string; score_summary: string; required_reviews: string[]; blocked_actions: string[]; next_action: string; decision_hash: string; previous_decision_hash: string | null; timestamp_simulated: string; metadata_only: true; legal_decision_claim: false; regulatory_authorization_claim: false; commercial_commitment_claim: false; simulated_only: true }
export interface SenseTrustScenarioDecisionMatrix { matrix_id: string; simulation_console_id: string; decision_items: SenseTrustScenarioDecisionItem[]; recommended_decision: SenseTrustScaleSimulationDecisionType; metadata_only: true; simulated_only: true }
export interface SenseTrustInstitutionalImpactItem { impact_item_id: string; simulation_id: string; impact_area: string; impact_level: SenseTrustScaleSimulationImpactLevel; score: number; real_impact_claim: false; simulated_only: true }
export interface SenseTrustInstitutionalImpactSimulation { simulation_id: string; simulation_console_id: string; items: SenseTrustInstitutionalImpactItem[]; impact_summary: string; metadata_only: true; real_impact_claim: false; simulated_only: true }
export interface SenseTrustOperationalCapacityItem { capacity_item_id: string; simulation_id: string; capacity_area: string; capacity_level: SenseTrustScaleSimulationCapacityLevel; score: number; real_capacity_claim: false; simulated_only: true }
export interface SenseTrustOperationalCapacitySimulation { simulation_id: string; simulation_console_id: string; items: SenseTrustOperationalCapacityItem[]; capacity_summary: string; metadata_only: true; real_capacity_claim: false; simulated_only: true }
export interface SenseTrustResourceLoadItem { load_item_id: string; simulation_id: string; resource_area: string; load_score: number; financial_commitment_claim: false; simulated_only: true }
export interface SenseTrustResourceLoadSimulation { simulation_id: string; simulation_console_id: string; items: SenseTrustResourceLoadItem[]; load_summary: string; metadata_only: true; financial_commitment_claim: false; simulated_only: true }
export interface SenseTrustScaleRiskSimulationItem { risk_item_id: string; simulation_id: string; risk_title: string; risk_level: SenseTrustScaleSimulationRiskLevel; mitigation: string; legal_or_regulatory_opinion_claim: false; simulated_only: true }
export interface SenseTrustScaleRiskSimulation { simulation_id: string; simulation_console_id: string; items: SenseTrustScaleRiskSimulationItem[]; highest_risk_level: SenseTrustScaleSimulationRiskLevel; metadata_only: true; legal_or_regulatory_opinion_claim: false; simulated_only: true }
export interface SenseTrustReadinessScoreItem { score_item_id: string; simulation_id: string; dimension: string; score: number; confidence: SenseTrustScaleSimulationConfidenceLevel; simulated_only: true }
export interface SenseTrustReadinessScoreSimulation { simulation_id: string; simulation_console_id: string; items: SenseTrustReadinessScoreItem[]; aggregate_score: number; metadata_only: true; regulatory_validation_claim: false; commercial_validation_claim: false; simulated_only: true }
export interface SenseTrustGoPauseRefineScaleSimulator { simulator_id: string; simulation_console_id: string; go_score: number; pause_score: number; refine_score: number; scale_simulated_score: number; recommended_decision: SenseTrustScaleSimulationDecisionType; metadata_only: true; binding_decision_claim: false; simulated_only: true }
export interface SenseTrustHumanReviewSimulationItem { review_item_id: string; simulation_id: string; trigger: string; reviewer_role: string; review_need_score: number; simulated_only: true }
export interface SenseTrustHumanReviewSimulation { simulation_id: string; simulation_console_id: string; items: SenseTrustHumanReviewSimulationItem[]; review_summary: string; metadata_only: true; real_regulatory_process_claim: false; simulated_only: true }
export interface SenseTrustScenarioOutcomeSummary { summary_id: string; simulation_console_id: string; scenario_count: number; recommended_decision: SenseTrustScaleSimulationDecisionType; outcome_summary: string; metadata_only: true; real_outcome_claim: false; simulated_only: true }
export interface SenseTrustSimulationDecisionTraceItem { trace_item_id: string; trace_id: string; scenario_id: string; decision_type: SenseTrustScaleSimulationDecisionType; logical_hash: string; timestamp_simulated: string; metadata_only: true; simulated_only: true }
export interface SenseTrustSimulationDecisionTrace { trace_id: string; simulation_console_id: string; trace_items: SenseTrustSimulationDecisionTraceItem[]; trace_summary: string; metadata_only: true; simulated_only: true }
export interface SenseTrustSimulationAuditTrailItem { audit_id: string; simulation_console_id: string; action: string; logical_hash: string; timestamp_simulated: string; simulated_actor: string; metadata_only: true; simulated_only: true }
export interface SenseTrustSimulationMisuseBlocker { blocker_id: string; blocked_misuse: string; risk: SenseTrustScaleSimulationRiskLevel; blocked_action: string; safe_language: string; simulated_only: true }
export interface SenseTrustStrategicScaleSimulationExecutiveReport { report_id: string; simulation_console_id: string; executive_summary: string; recommended_decision: SenseTrustScaleSimulationDecisionType; scenario_summary: string; risk_summary: string; capacity_summary: string; human_review_summary: string; simulated_only: true }
export interface SenseTrustStrategicScaleSimulationConsole { simulation_console_id: string; operating_model_id: string; scale_gate_id: string; readiness_gate_id: string; closeout_id: string; simulation_console_title: string; simulation_status: SenseTrustScaleSimulationStatusType; scenario_count: number; scenario_decision_matrix_id: string; institutional_impact_simulation_id: string; operational_capacity_simulation_id: string; resource_load_simulation_id: string; scale_risk_simulation_id: string; readiness_score_simulation_id: string; go_pause_refine_scale_simulator_id: string; human_review_simulation_id: string; scenario_outcome_summary_id: string; simulation_decision_trace_id: string; executive_report_id: string; recommended_simulation_decision: SenseTrustScaleSimulationDecisionType; blocked_actions: string[]; required_reviews: string[]; logical_simulation_console_hash: string; previous_simulation_console_hash: string | null; metadata_only: true; contains_clinical_data: false; contains_patient_data: false; contains_personal_sensitive_data: false; real_clinical_operation_claim: false; contract_binding_claim: false; client_claim: false; partnership_claim: false; regulatory_validation_claim: false; diagnostic_truth_certification_claim: false; real_revenue_claim: false; real_billing_claim: false; real_impact_claim: false; real_capacity_claim: false; simulated_only: true }
export interface SenseTrustStrategicScaleSimulationConsoleState { state_id: string; version: 'v3.2'; simulation_consoles: SenseTrustStrategicScaleSimulationConsole[]; scenarios: SenseTrustScaleSimulationScenario[]; scenario_inputs: SenseTrustScaleSimulationScenarioInput[]; scenario_outputs: SenseTrustScaleSimulationScenarioOutput[]; scenario_decision_matrices: SenseTrustScenarioDecisionMatrix[]; scenario_decision_items: SenseTrustScenarioDecisionItem[]; institutional_impact_simulations: SenseTrustInstitutionalImpactSimulation[]; institutional_impact_items: SenseTrustInstitutionalImpactItem[]; operational_capacity_simulations: SenseTrustOperationalCapacitySimulation[]; operational_capacity_items: SenseTrustOperationalCapacityItem[]; resource_load_simulations: SenseTrustResourceLoadSimulation[]; resource_load_items: SenseTrustResourceLoadItem[]; scale_risk_simulations: SenseTrustScaleRiskSimulation[]; scale_risk_items: SenseTrustScaleRiskSimulationItem[]; readiness_score_simulations: SenseTrustReadinessScoreSimulation[]; readiness_score_items: SenseTrustReadinessScoreItem[]; simulators: SenseTrustGoPauseRefineScaleSimulator[]; human_review_simulations: SenseTrustHumanReviewSimulation[]; human_review_items: SenseTrustHumanReviewSimulationItem[]; outcome_summaries: SenseTrustScenarioOutcomeSummary[]; decision_traces: SenseTrustSimulationDecisionTrace[]; decision_trace_items: SenseTrustSimulationDecisionTraceItem[]; audit_trail: SenseTrustSimulationAuditTrailItem[]; misuse_blockers: SenseTrustSimulationMisuseBlocker[]; executive_reports: SenseTrustStrategicScaleSimulationExecutiveReport[]; references: string[]; metadata_only: true; clinical_data_used: false; patient_data_used: false; personal_sensitive_data_used: false; real_clinical_operation_claimed: false; contract_binding_claimed: false; client_claim: false; partnership_claim: false; regulatory_validation_claim: false; diagnostic_truth_certification_claimed: false; real_revenue_claimed: false; real_billing_claimed: false; real_impact_claimed: false; real_capacity_claimed: false; legal_decision_claimed: false; commercial_commitment_claimed: false; simulated_only: true }
export interface SenseTrustStrategicScaleSimulationExportPayload { schema: 'sensetrust.strategic_scale_simulation_export.v1'; exported_at: string; state: SenseTrustStrategicScaleSimulationConsoleState; public_exposure: 'metadata_only'; simulated_only: true }
export interface SenseTrustStrategicScaleSimulationValidationResult { valid: boolean; errors: string[] }
