import { PARTNER_ENGAGEMENT_REFERENCES, PARTNER_ENGAGEMENT_SENSITIVE_DENYLIST, SIMULATED_PARTNER_BOUNDARY_CLAIMS_GUARDRAILS, SIMULATED_PARTNER_BOUNDARY_CLAIMS_GUARDRAIL_ITEMS, SIMULATED_PARTNER_ENGAGEMENT_AUDIT_TRAILS, SIMULATED_PARTNER_ENGAGEMENT_AUDIT_TRAIL_ITEMS, SIMULATED_PARTNER_ENGAGEMENT_EXECUTIVE_REPORTS, SIMULATED_PARTNER_ENGAGEMENT_RISK_ITEMS, SIMULATED_PARTNER_ENGAGEMENT_RISK_REGISTERS, SIMULATED_PARTNER_ENGAGEMENT_ROOMS, SIMULATED_PARTNER_ENGAGEMENT_SCORES, SIMULATED_PARTNER_ENGAGEMENT_SCORE_ITEMS, SIMULATED_PARTNER_ENGAGEMENT_TRACKS, SIMULATED_PARTNER_FOLLOW_UP_DECISION_BOARDS, SIMULATED_PARTNER_FOLLOW_UP_DECISION_ITEMS, SIMULATED_PARTNER_HUMAN_REVIEW_ESCALATION_ITEMS, SIMULATED_PARTNER_HUMAN_REVIEW_ESCALATION_QUEUES, SIMULATED_PARTNER_INTERACTION_LEDGERS, SIMULATED_PARTNER_INTERACTION_LEDGER_ITEMS, SIMULATED_PARTNER_MEETING_BOARDS, SIMULATED_PARTNER_MEETING_ITEMS, SIMULATED_PARTNER_OBJECTION_RESOLUTION_ITEMS, SIMULATED_PARTNER_OBJECTION_RESOLUTION_MAPS, SIMULATED_PARTNER_RESPONSE_ITEMS, SIMULATED_PARTNER_RESPONSE_MATRICES, SIMULATED_STRATEGIC_PARTNER_ENGAGEMENT_CONTROL_ROOM_STATE, SIMULATED_STRATEGIC_PARTNER_ENGAGEMENT_EXPORT_PAYLOAD } from '@/fixtures/sensetrust/simulated-strategic-partner-engagement-control-room'
import type { SenseTrustPartnerEngagementConfidenceLevel, SenseTrustPartnerEngagementDecision, SenseTrustPartnerEngagementRiskLevel, SenseTrustPartnerEngagementStage, SenseTrustPartnerEngagementStatus, SenseTrustPartnerInteractionType, SenseTrustStrategicPartnerEngagementControlRoomState, SenseTrustStrategicPartnerEngagementExportPayload, SenseTrustStrategicPartnerEngagementValidationResult } from '@/types/sensetrust/strategic-partner-engagement-control-room'

export function createStrategicPartnerEngagementControlRoomState() { return createDefaultStrategicPartnerEngagementControlRoomState() }
export function createStrategicPartnerEngagementControlRoom() { return cloneArrayFields(SIMULATED_PARTNER_ENGAGEMENT_ROOMS[0], ['blocked_actions', 'required_reviews']) }
export function createPartnerEngagementTrack() { return cloneArrayFields(SIMULATED_PARTNER_ENGAGEMENT_TRACKS[0], ['required_reviews', 'blocked_actions']) }
export function createPartnerInteractionLedger() { return { ...SIMULATED_PARTNER_INTERACTION_LEDGERS[0], items: SIMULATED_PARTNER_INTERACTION_LEDGERS[0].items.map((x) => ({ ...x })) } }
export function createPartnerInteractionLedgerItem() { return { ...SIMULATED_PARTNER_INTERACTION_LEDGER_ITEMS[0] } }
export function createPartnerMeetingSimulationBoard() { return { ...SIMULATED_PARTNER_MEETING_BOARDS[0], items: SIMULATED_PARTNER_MEETING_BOARDS[0].items.map((x) => ({ ...x })) } }
export function createPartnerMeetingSimulationItem() { return { ...SIMULATED_PARTNER_MEETING_ITEMS[0] } }
export function createPartnerResponseMatrix() { return { ...SIMULATED_PARTNER_RESPONSE_MATRICES[0], items: SIMULATED_PARTNER_RESPONSE_MATRICES[0].items.map((x) => ({ ...x })) } }
export function createPartnerResponseMatrixItem() { return { ...SIMULATED_PARTNER_RESPONSE_ITEMS[0] } }
export function createPartnerObjectionResolutionMap() { return { ...SIMULATED_PARTNER_OBJECTION_RESOLUTION_MAPS[0], items: SIMULATED_PARTNER_OBJECTION_RESOLUTION_MAPS[0].items.map((x) => ({ ...x })) } }
export function createPartnerObjectionResolutionItem() { return { ...SIMULATED_PARTNER_OBJECTION_RESOLUTION_ITEMS[0] } }
export function createPartnerEngagementRiskRegister() { return { ...SIMULATED_PARTNER_ENGAGEMENT_RISK_REGISTERS[0], items: SIMULATED_PARTNER_ENGAGEMENT_RISK_REGISTERS[0].items.map((x) => ({ ...x })) } }
export function createPartnerEngagementRiskItem() { return { ...SIMULATED_PARTNER_ENGAGEMENT_RISK_ITEMS[0] } }
export function createPartnerFollowUpDecisionBoard() { return { ...SIMULATED_PARTNER_FOLLOW_UP_DECISION_BOARDS[0], items: SIMULATED_PARTNER_FOLLOW_UP_DECISION_BOARDS[0].items.map((x) => ({ ...x })) } }
export function createPartnerFollowUpDecisionItem() { return { ...SIMULATED_PARTNER_FOLLOW_UP_DECISION_ITEMS[0] } }
export function createPartnerEngagementReadinessScore() { return { ...SIMULATED_PARTNER_ENGAGEMENT_SCORES[0], items: SIMULATED_PARTNER_ENGAGEMENT_SCORES[0].items.map((x) => ({ ...x })) } }
export function createPartnerEngagementReadinessScoreItem() { return { ...SIMULATED_PARTNER_ENGAGEMENT_SCORE_ITEMS[0] } }
export function createPartnerHumanReviewEscalationQueue() { return { ...SIMULATED_PARTNER_HUMAN_REVIEW_ESCALATION_QUEUES[0], items: SIMULATED_PARTNER_HUMAN_REVIEW_ESCALATION_QUEUES[0].items.map((x) => ({ ...x })) } }
export function createPartnerHumanReviewEscalationItem() { return { ...SIMULATED_PARTNER_HUMAN_REVIEW_ESCALATION_ITEMS[0] } }
export function createPartnerBoundaryClaimsGuardrail() { return { ...SIMULATED_PARTNER_BOUNDARY_CLAIMS_GUARDRAILS[0], items: SIMULATED_PARTNER_BOUNDARY_CLAIMS_GUARDRAILS[0].items.map((x) => ({ ...x })) } }
export function createPartnerBoundaryClaimsGuardrailItem() { return { ...SIMULATED_PARTNER_BOUNDARY_CLAIMS_GUARDRAIL_ITEMS[0] } }
export function createPartnerEngagementAuditTrail() { return { ...SIMULATED_PARTNER_ENGAGEMENT_AUDIT_TRAILS[0], items: SIMULATED_PARTNER_ENGAGEMENT_AUDIT_TRAILS[0].items.map((x) => ({ ...x })) } }
export function createPartnerEngagementAuditTrailItem() { return { ...SIMULATED_PARTNER_ENGAGEMENT_AUDIT_TRAIL_ITEMS[0] } }
export function createStrategicPartnerEngagementExecutiveReport() { return { ...SIMULATED_PARTNER_ENGAGEMENT_EXECUTIVE_REPORTS[0] } }
export function createDefaultStrategicPartnerEngagementControlRooms() { return SIMULATED_PARTNER_ENGAGEMENT_ROOMS.map((x) => cloneArrayFields(x, ['blocked_actions', 'required_reviews'])) }
export function createDefaultPartnerEngagementTracks() { return SIMULATED_PARTNER_ENGAGEMENT_TRACKS.map((x) => cloneArrayFields(x, ['required_reviews', 'blocked_actions'])) }
export function createDefaultPartnerInteractionLedgers() { return SIMULATED_PARTNER_INTERACTION_LEDGERS.map((x) => ({ ...x, items: x.items.map((i) => ({ ...i })) })) }
export function createDefaultPartnerMeetingSimulationBoards() { return SIMULATED_PARTNER_MEETING_BOARDS.map((x) => ({ ...x, items: x.items.map((i) => ({ ...i })) })) }
export function createDefaultPartnerResponseMatrices() { return SIMULATED_PARTNER_RESPONSE_MATRICES.map((x) => ({ ...x, items: x.items.map((i) => ({ ...i })) })) }
export function createDefaultPartnerObjectionResolutionMaps() { return SIMULATED_PARTNER_OBJECTION_RESOLUTION_MAPS.map((x) => ({ ...x, items: x.items.map((i) => ({ ...i })) })) }
export function createDefaultPartnerEngagementRiskRegisters() { return SIMULATED_PARTNER_ENGAGEMENT_RISK_REGISTERS.map((x) => ({ ...x, items: x.items.map((i) => ({ ...i })) })) }
export function createDefaultPartnerFollowUpDecisionBoards() { return SIMULATED_PARTNER_FOLLOW_UP_DECISION_BOARDS.map((x) => ({ ...x, items: x.items.map((i) => ({ ...i })) })) }
export function createDefaultPartnerEngagementReadinessScores() { return SIMULATED_PARTNER_ENGAGEMENT_SCORES.map((x) => ({ ...x, items: x.items.map((i) => ({ ...i })) })) }
export function createDefaultPartnerHumanReviewEscalationQueues() { return SIMULATED_PARTNER_HUMAN_REVIEW_ESCALATION_QUEUES.map((x) => ({ ...x, items: x.items.map((i) => ({ ...i })) })) }
export function createDefaultPartnerBoundaryClaimsGuardrails() { return SIMULATED_PARTNER_BOUNDARY_CLAIMS_GUARDRAILS.map((x) => ({ ...x, items: x.items.map((i) => ({ ...i })) })) }
export function createDefaultPartnerEngagementAuditTrails() { return SIMULATED_PARTNER_ENGAGEMENT_AUDIT_TRAILS.map((x) => ({ ...x, items: x.items.map((i) => ({ ...i })) })) }
export function createDefaultStrategicPartnerEngagementExecutiveReports() { return SIMULATED_PARTNER_ENGAGEMENT_EXECUTIVE_REPORTS.map((x) => ({ ...x })) }
export function createDefaultStrategicPartnerEngagementControlRoomState(): SenseTrustStrategicPartnerEngagementControlRoomState { return { ...SIMULATED_STRATEGIC_PARTNER_ENGAGEMENT_CONTROL_ROOM_STATE, rooms: createDefaultStrategicPartnerEngagementControlRooms(), tracks: createDefaultPartnerEngagementTracks(), interaction_ledgers: createDefaultPartnerInteractionLedgers(), interaction_ledger_items: SIMULATED_PARTNER_INTERACTION_LEDGER_ITEMS.map((x) => ({ ...x })), meeting_simulation_boards: createDefaultPartnerMeetingSimulationBoards(), meeting_simulation_items: SIMULATED_PARTNER_MEETING_ITEMS.map((x) => ({ ...x })), response_matrices: createDefaultPartnerResponseMatrices(), response_matrix_items: SIMULATED_PARTNER_RESPONSE_ITEMS.map((x) => ({ ...x })), objection_resolution_maps: createDefaultPartnerObjectionResolutionMaps(), objection_resolution_items: SIMULATED_PARTNER_OBJECTION_RESOLUTION_ITEMS.map((x) => ({ ...x })), engagement_risk_registers: createDefaultPartnerEngagementRiskRegisters(), engagement_risk_items: SIMULATED_PARTNER_ENGAGEMENT_RISK_ITEMS.map((x) => ({ ...x })), follow_up_decision_boards: createDefaultPartnerFollowUpDecisionBoards(), follow_up_decision_items: SIMULATED_PARTNER_FOLLOW_UP_DECISION_ITEMS.map((x) => ({ ...x })), engagement_readiness_scores: createDefaultPartnerEngagementReadinessScores(), engagement_readiness_score_items: SIMULATED_PARTNER_ENGAGEMENT_SCORE_ITEMS.map((x) => ({ ...x })), human_review_escalation_queues: createDefaultPartnerHumanReviewEscalationQueues(), human_review_escalation_items: SIMULATED_PARTNER_HUMAN_REVIEW_ESCALATION_ITEMS.map((x) => ({ ...x })), boundary_claims_guardrails: createDefaultPartnerBoundaryClaimsGuardrails(), boundary_claims_guardrail_items: SIMULATED_PARTNER_BOUNDARY_CLAIMS_GUARDRAIL_ITEMS.map((x) => ({ ...x })), engagement_audit_trails: createDefaultPartnerEngagementAuditTrails(), engagement_audit_trail_items: SIMULATED_PARTNER_ENGAGEMENT_AUDIT_TRAIL_ITEMS.map((x) => ({ ...x })), executive_reports: createDefaultStrategicPartnerEngagementExecutiveReports(), references: [...PARTNER_ENGAGEMENT_REFERENCES] } }
export function generateLogicalPartnerEngagementHash(seed = 'partner-engagement') { return `logical-${seed}-${seed.length * 79}` }
export function buildStrategicPartnerEngagementControlRoom() { return createStrategicPartnerEngagementControlRoom() }
export function buildPartnerEngagementTrack() { return createPartnerEngagementTrack() }
export function buildPartnerInteractionLedger() { return createPartnerInteractionLedger() }
export function buildPartnerMeetingSimulationBoard() { return createPartnerMeetingSimulationBoard() }
export function buildPartnerResponseMatrix() { return createPartnerResponseMatrix() }
export function buildPartnerObjectionResolutionMap() { return createPartnerObjectionResolutionMap() }
export function buildPartnerEngagementRiskRegister() { return createPartnerEngagementRiskRegister() }
export function buildPartnerFollowUpDecisionBoard() { return createPartnerFollowUpDecisionBoard() }
export function buildPartnerEngagementReadinessScore() { return createPartnerEngagementReadinessScore() }
export function buildPartnerHumanReviewEscalationQueue() { return createPartnerHumanReviewEscalationQueue() }
export function buildPartnerBoundaryClaimsGuardrail() { return createPartnerBoundaryClaimsGuardrail() }
export function buildPartnerEngagementAuditTrail() { return createPartnerEngagementAuditTrail() }
export function classifyPartnerEngagementStage(score = 50): SenseTrustPartnerEngagementStage { if (score >= 85) return 'follow_up_required'; if (score >= 65) return 'simulated_feedback'; if (score >= 45) return 'simulated_meeting'; return 'human_review_required' }
export function classifyPartnerEngagementStatus(score = 50): SenseTrustPartnerEngagementStatus { if (score >= 85) return 'follow_up_ready'; if (score >= 65) return 'response_reviewed'; if (score >= 45) return 'engagement_ready'; return 'refine_required' }
export function classifyPartnerInteractionType(type: SenseTrustPartnerInteractionType = 'simulated_intro') { return type }
export function classifyPartnerEngagementDecision(score = 50): SenseTrustPartnerEngagementDecision { if (score >= 85) return 'follow_up'; if (score >= 65) return 'require_human_review'; if (score >= 45) return 'refine'; return 'pause' }
export function classifyPartnerEngagementRiskLevel(score = 50): SenseTrustPartnerEngagementRiskLevel { if (score >= 85) return 'critical'; if (score >= 65) return 'high'; if (score >= 35) return 'medium'; return 'low' }
export function classifyPartnerEngagementConfidenceLevel(level: SenseTrustPartnerEngagementConfidenceLevel = 'simulated_only') { return level }
export function calculatePartnerEngagementReadinessScore(score = 55) { return clamp(score) }
export function calculatePartnerInteractionCompletenessScore(score = 55) { return clamp(score) }
export function calculatePartnerResponseQualityScore(score = 55) { return clamp(score) }
export function calculatePartnerObjectionResolutionScore(score = 55) { return clamp(score) }
export function calculatePartnerEngagementRiskScore(score = 45) { return clamp(score) }
export function calculatePartnerFollowUpPriorityScore(score = 55) { return clamp(score) }
export function calculatePartnerHumanReviewNeedScore(score = 55) { return clamp(score) }
export function validateStrategicPartnerEngagementControlRooms(s = createDefaultStrategicPartnerEngagementControlRoomState()) { return countCheck(s.rooms.length, 8, 'rooms') }
export function validatePartnerEngagementTracks(s = createDefaultStrategicPartnerEngagementControlRoomState()) { return countCheck(s.tracks.length, 24, 'tracks') }
export function validatePartnerInteractionLedgers(s = createDefaultStrategicPartnerEngagementControlRoomState()) { return countCheck(s.interaction_ledgers.length, 8, 'interaction_ledgers') }
export function validatePartnerMeetingSimulationBoards(s = createDefaultStrategicPartnerEngagementControlRoomState()) { return countCheck(s.meeting_simulation_boards.length, 8, 'meeting_simulation_boards') }
export function validatePartnerResponseMatrices(s = createDefaultStrategicPartnerEngagementControlRoomState()) { return countCheck(s.response_matrices.length, 8, 'response_matrices') }
export function validatePartnerObjectionResolutionMaps(s = createDefaultStrategicPartnerEngagementControlRoomState()) { return countCheck(s.objection_resolution_maps.length, 8, 'objection_resolution_maps') }
export function validatePartnerEngagementRiskRegisters(s = createDefaultStrategicPartnerEngagementControlRoomState()) { return countCheck(s.engagement_risk_registers.length, 8, 'engagement_risk_registers') }
export function validatePartnerFollowUpDecisionBoards(s = createDefaultStrategicPartnerEngagementControlRoomState()) { return countCheck(s.follow_up_decision_boards.length, 8, 'follow_up_decision_boards') }
export function validatePartnerEngagementReadinessScores(s = createDefaultStrategicPartnerEngagementControlRoomState()) { return countCheck(s.engagement_readiness_scores.length, 8, 'engagement_readiness_scores') }
export function validatePartnerHumanReviewEscalationQueues(s = createDefaultStrategicPartnerEngagementControlRoomState()) { return countCheck(s.human_review_escalation_queues.length, 8, 'human_review_escalation_queues') }
export function validatePartnerBoundaryClaimsGuardrails(s = createDefaultStrategicPartnerEngagementControlRoomState()) { return countCheck(s.boundary_claims_guardrails.length, 8, 'boundary_claims_guardrails') }
export function validatePartnerEngagementAuditTrails(s = createDefaultStrategicPartnerEngagementControlRoomState()) { return countCheck(s.engagement_audit_trails.length, 8, 'engagement_audit_trails') }
export function validateNoClinicalDataExposure(p: unknown) { return denylistCheck(p, PARTNER_ENGAGEMENT_SENSITIVE_DENYLIST, ['clinical_data_used":true', 'contains_clinical_data":true']) }
export function validateNoPatientData(p: unknown) { return flagCheck(p, ['patient_data_used":true', 'contains_patient_data":true'], 'patient_data_true') }
export function validateNoPersonalSensitiveData(p: unknown) { return flagCheck(p, ['personal_sensitive_data_used":true', 'contains_personal_sensitive_data":true'], 'personal_sensitive_data_true') }
export function validateNoRealClinicalOperationClaim(p: unknown) { return flagCheck(p, ['real_clinical_operation_claimed":true', 'real_clinical_operation_claim":true'], 'real_clinical_operation_true') }
export function validateNoContractBindingClaim(p: unknown) { return flagCheck(p, ['contract_binding_claimed":true', 'contract_binding_claim":true', 'commercial_commitment_claim":true'], 'contract_binding_true') }
export function validateNoClientClaim(p: unknown) { return flagCheck(p, ['client_claim":true'], 'client_claim_true') }
export function validateNoPartnershipClaim(p: unknown) { return flagCheck(p, ['partnership_claim":true', 'real_partner_claim":true'], 'partnership_claim_true') }
export function validateNoRegulatoryValidationClaim(p: unknown) { return flagCheck(p, ['regulatory_validation_claim":true', 'regulatory_authorization_claim":true'], 'regulatory_validation_true') }
export function validateNoDiagnosticTruthClaim(p: unknown) { return flagCheck(p, ['diagnostic_truth_certification_claimed":true', 'diagnostic_truth_certification_claim":true'], 'diagnostic_truth_true') }
export function validateNoRealRevenueClaim(p: unknown) { return flagCheck(p, ['real_revenue_claimed":true', 'real_revenue_claim":true'], 'real_revenue_true') }
export function validateNoRealBillingClaim(p: unknown) { return flagCheck(p, ['real_billing_claimed":true', 'real_billing_claim":true'], 'real_billing_true') }
export function validateNoRealImpactClaim(p: unknown) { return flagCheck(p, ['real_impact_claimed":true', 'real_impact_claim":true'], 'real_impact_true') }
export function validateNoRealCapacityClaim(p: unknown) { return flagCheck(p, ['real_capacity_claimed":true', 'real_capacity_claim":true'], 'real_capacity_true') }
export function validateNoRealScientificValidationClaim(p: unknown) { return flagCheck(p, ['real_scientific_validation_claimed":true', 'real_scientific_validation_claim":true', 'scientific_validation_claim":true'], 'scientific_validation_true') }
export function validateNoExternalCertificationClaim(p: unknown) { return flagCheck(p, ['external_certification_claimed":true', 'external_certification_claim":true'], 'external_certification_true') }
export function validateNoRealCrmClaim(p: unknown) { return flagCheck(p, ['real_crm_claimed":true', 'real_crm_claim":true'], 'real_crm_true') }
export function validateNoRealEmailAutomationClaim(p: unknown) { return flagCheck(p, ['real_email_automation_claimed":true', 'real_email_automation_claim":true'], 'real_email_automation_true') }
export function buildStrategicPartnerEngagementExportPayload(): SenseTrustStrategicPartnerEngagementExportPayload { return { ...SIMULATED_STRATEGIC_PARTNER_ENGAGEMENT_EXPORT_PAYLOAD, state: createDefaultStrategicPartnerEngagementControlRoomState() } }
export function validateStrategicPartnerEngagementExportPayload(payload = buildStrategicPartnerEngagementExportPayload()) { const checks = [validateStrategicPartnerEngagementControlRooms(payload.state), validatePartnerEngagementTracks(payload.state), validatePartnerInteractionLedgers(payload.state), validatePartnerMeetingSimulationBoards(payload.state), validatePartnerResponseMatrices(payload.state), validatePartnerObjectionResolutionMaps(payload.state), validatePartnerEngagementRiskRegisters(payload.state), validatePartnerFollowUpDecisionBoards(payload.state), validatePartnerEngagementReadinessScores(payload.state), validatePartnerHumanReviewEscalationQueues(payload.state), validatePartnerBoundaryClaimsGuardrails(payload.state), validatePartnerEngagementAuditTrails(payload.state), validateNoClinicalDataExposure(payload.state), validateNoPatientData(payload.state), validateNoPersonalSensitiveData(payload.state), validateNoRealClinicalOperationClaim(payload.state), validateNoContractBindingClaim(payload.state), validateNoClientClaim(payload.state), validateNoPartnershipClaim(payload.state), validateNoRegulatoryValidationClaim(payload.state), validateNoDiagnosticTruthClaim(payload.state), validateNoRealRevenueClaim(payload.state), validateNoRealBillingClaim(payload.state), validateNoRealImpactClaim(payload.state), validateNoRealCapacityClaim(payload.state), validateNoRealScientificValidationClaim(payload.state), validateNoExternalCertificationClaim(payload.state), validateNoRealCrmClaim(payload.state), validateNoRealEmailAutomationClaim(payload.state)]; const errors = checks.flatMap((x) => x.errors); return { valid: errors.length === 0, errors } }
export function assertPartnerEngagementMetadataOnly(p: { metadata_only?: boolean }) { if (!p.metadata_only) throw new Error('partner_engagement_not_metadata_only'); return { valid: true, errors: [] } }
export function assertPartnerEngagementNoSensitiveExposure(p: unknown) { return assertValid(validateNoClinicalDataExposure(p), 'partner_engagement_sensitive_exposure') }
export function assertPartnerEngagementNoLegalBinding(p: unknown) { return assertValid(validateNoContractBindingClaim(p), 'partner_engagement_legal_binding') }
export function assertPartnerEngagementNoRegulatoryAuthorization(p: unknown) { return assertValid(validateNoRegulatoryValidationClaim(p), 'partner_engagement_regulatory_authorization') }
export function assertPartnerEngagementNoCommercialCommitment(p: unknown) { return assertValid(validateNoClientClaim(p), 'partner_engagement_commercial_commitment') }
export function assertPartnerEngagementNoClinicalOperation(p: unknown) { return assertValid(validateNoRealClinicalOperationClaim(p), 'partner_engagement_clinical_operation') }
export function assertPartnerEngagementNoDiagnosticTruthCertification(p: unknown) { return assertValid(validateNoDiagnosticTruthClaim(p), 'partner_engagement_diagnostic_truth') }
export function assertPartnerEngagementNoRealImpact(p: unknown) { return assertValid(validateNoRealImpactClaim(p), 'partner_engagement_real_impact') }
export function assertPartnerEngagementNoRealCapacity(p: unknown) { return assertValid(validateNoRealCapacityClaim(p), 'partner_engagement_real_capacity') }
export function assertPartnerEngagementNoScientificValidation(p: unknown) { return assertValid(validateNoRealScientificValidationClaim(p), 'partner_engagement_scientific_validation') }
export function assertPartnerEngagementNoExternalCertification(p: unknown) { return assertValid(validateNoExternalCertificationClaim(p), 'partner_engagement_external_certification') }
export function assertPartnerEngagementNoRealCrm(p: unknown) { return assertValid(validateNoRealCrmClaim(p), 'partner_engagement_real_crm') }
export function assertPartnerEngagementNoRealEmailAutomation(p: unknown) { return assertValid(validateNoRealEmailAutomationClaim(p), 'partner_engagement_real_email_automation') }
export function linkPartnerEngagementToPartnerReadinessRoom() { return 'SenseTrust Strategic Partner Readiness Room v3.4' }
export function linkPartnerEngagementToEvidenceSimulator() { return 'SenseTrust Strategic Scale Evidence Simulator v3.3' }
export function linkPartnerEngagementToSimulationConsole() { return 'SenseTrust Strategic Scale Simulation Console v3.2' }
export function linkPartnerEngagementToOperatingModel() { return 'SenseTrust Strategic Scale Operating Model v3.1' }
export function linkPartnerEngagementToGitFreezeAutomation() { return 'SenseTrust Git Freeze Automation Memory v1.1 FETCH_HEAD ACL Recovery' }
export function linkPartnerEngagementToMOC() { return ['MOC_SenseTrust', 'MOC_VitalStrata_SenseTrust', 'MOC_NeuroStrata_Trust_Layer', 'MOC_DNDA_Trust_Object', 'MOC_BLC_Rastreabilidade'] }
function cloneArrayFields<T extends Record<string, unknown>>(item: T, keys: string[]): T { const copy = { ...item }; keys.forEach((key) => { const value = item[key]; if (Array.isArray(value)) copy[key as keyof T] = [...value] as T[keyof T] }); return copy }
function clamp(score: number) { return Math.max(0, Math.min(100, score)) }
function countCheck(actual: number, expected: number, label: string): SenseTrustStrategicPartnerEngagementValidationResult { return { valid: actual >= expected, errors: actual >= expected ? [] : [`${label}_count_below_${expected}`] } }
function denylistCheck(payload: unknown, denylist: string[], flags: string[] = []): SenseTrustStrategicPartnerEngagementValidationResult { const serialized = JSON.stringify(payload).toLowerCase(); const errors = [...denylist.filter((term) => serialized.includes(term.toLowerCase())), ...flags.filter((flag) => serialized.includes(flag.toLowerCase()))]; return { valid: errors.length === 0, errors } }
function flagCheck(payload: unknown, flags: string[], error: string): SenseTrustStrategicPartnerEngagementValidationResult { const serialized = JSON.stringify(payload).toLowerCase(); return { valid: !flags.some((flag) => serialized.includes(flag.toLowerCase())), errors: flags.some((flag) => serialized.includes(flag.toLowerCase())) ? [error] : [] } }
function assertValid(result: SenseTrustStrategicPartnerEngagementValidationResult, label: string) { if (!result.valid) throw new Error(`${label}: ${result.errors.join(', ')}`); return result }
