$ErrorActionPreference = "Stop"
$VaultRoot = "C:\Users\User\Documents\NEURO DASH SKIP\VitalStrata_OS"; $VaultId = "b1a32fcb40985ffc"; $SprintTitle = "SenseTrust Strategic Pilot Monitoring Evidence Intake Room v3.9"
$QuickNote = "00_ABRIR_SENSETRUST\43_STRATEGIC_PILOT_MONITORING_EVIDENCE_INTAKE_ROOM_v39.md"; $MainNote = "05_SENSETRUST\$SprintTitle.md"; $RootNote = "00_ABRIR_ULTIMA_NOTA_SENSETRUST.md"; $LastSync = "00_MEMORY_INDEX\_LAST_SYNC.md"; $Manifest = "00_MEMORY_INDEX\MEMORY_MANIFEST.md"; $ManifestJson = "00_MEMORY_INDEX\MEMORY_MANIFEST.json"
$Mocs = @("05_SENSETRUST\MOC_SenseTrust.md","05_SENSETRUST\MOC_VitalStrata_SenseTrust.md","05_SENSETRUST\MOC_NeuroStrata_Trust_Layer.md","05_SENSETRUST\MOC_DNDA_Trust_Object.md","05_SENSETRUST\MOC_BLC_Rastreabilidade.md")
if (!(Test-Path (Join-Path $VaultRoot ".obsidian"))) { throw "Vault Obsidian canonico nao encontrado: $VaultRoot" }
function Ensure-Parent($RelativePath) { $full = Join-Path $VaultRoot $RelativePath; $parent = Split-Path $full -Parent; if (!(Test-Path $parent)) { New-Item -ItemType Directory -Force -Path $parent | Out-Null } }
function Write-Note($RelativePath, $Body) { Ensure-Parent $RelativePath; Set-Content -Path (Join-Path $VaultRoot $RelativePath) -Value $Body -Encoding UTF8 }
$Tags = @("SenseTrust","SenseTrust/v3.9","SenseTrust/StrategicPilotMonitoring","SenseTrust/EvidenceIntake","SenseTrust/MonitoringRoom","SenseTrust/PilotMonitoring","SenseTrust/EvidenceLedger","SenseTrust/ChainOfCustody","SenseTrust/CheckpointMonitoring","SenseTrust/DeviationSignals","SenseTrust/RiskSignals","SenseTrust/HumanReview","SenseTrust/DecisionTriggers","SenseTrust/BoundaryClaims","SenseTrust/LeanFreeze","SenseTrust/v1.2","SenseTrust/v3.8","SenseTrust/v3.7","SenseTrust/v3.6","SenseTrust/TrustLayer","SenseTrust/DNDA","SenseTrust/VitalStrata","SenseTrust/NeuroStrata","SenseTrust/BLC","NeuroStrata/TrustLayer","VitalStrata/SaaS","DNDA/Auditavel","BLC/Rastreabilidade","MetadataOnly","SimulatedOnly","HumanReviewRequired","Neurodireitos","LGPD","Obsidian/NATE")
$TagsYaml = ($Tags | ForEach-Object { "  - $_" }) -join "`n"
$Frontmatter = "---`nvault_id: $VaultId`ntype: sensetrust_strategic_pilot_monitoring_evidence_intake_room`nmodule: SenseTrust`nversion: v3.9`nstatus: simulated_only`ntrust_status: metadata_only`ncreated_by: Codex`ncreated: 2026-06-19`nupdated: 2026-06-19`nlinked_sprint: SenseTrust v3.9 Strategic Pilot Monitoring Evidence Intake Room`ntags:`n$TagsYaml`n---"
$Statement = "A SenseTrust v3.9 nao coleta evidencia real, nao monitora paciente real e nao executa piloto real. Ela organiza uma simulacao de monitoramento, entrada de evidencias, checkpoints, riscos, desvios e decisoes humanas supervisionadas para preparar o fechamento auditavel de um piloto institucional."
$QuickBody = "$Frontmatter`n# 43_STRATEGIC_PILOT_MONITORING_EVIDENCE_INTAKE_ROOM_v39`n`n[[SenseTrust Strategic Pilot Monitoring Evidence Intake Room v3.9]]`n`n## Painel rapido`n`n- Monitoramento simulado.`n- Entrada de evidencias metadata_only.`n- Checkpoints, desvios, riscos e revisao humana.`n- Preparacao explicita para v4.0 closeout.`n`n## Regra operacional`n`n$Statement`n`n## Links`n`n- [[42_STRATEGIC_PILOT_EXECUTION_GOVERNANCE_ROOM_v38]]`n- [[41_GIT_FREEZE_AUTOMATION_LEAN_MODE_v12]]`n- [[40_STRATEGIC_PARTNERSHIP_PILOT_PROPOSAL_ROOM_v37]]`n- [[_LAST_SYNC]]`n- [[MOC_SenseTrust]]`n- [[MEMORY_MANIFEST]]`n"
$MainBody = "$Frontmatter`n# $SprintTitle`n`n$Statement`n`n## Governanca`n`nA sala conecta v3.8, v3.7 e Lean Freeze v1.2 para organizar evidence intake, integridade, chain of custody, checkpoints, desvios, riscos, decisao humana e preparacao v4.0 closeout_ready. DNDA significa Diagnóstico Neurofuncional Dimensional Auditável.`n`n## Limites`n`nmetadata_only, simulated_only, human_review_required, LGPD, neurodireitos, sem dado clinico real, sem paciente real, sem amostra biologica real, sem EEG/qEEG real, sem piloto real, sem contrato, cliente, parceria ou certificacao diagnostica.`n"
$RootBody = "$Frontmatter`n# ABRIR ULTIMA NOTA SENSETRUST`n`n## Ultima nota`n`n- [[43_STRATEGIC_PILOT_MONITORING_EVIDENCE_INTAKE_ROOM_v39]]`n- [[SenseTrust Strategic Pilot Monitoring Evidence Intake Room v3.9]]`n- [[42_STRATEGIC_PILOT_EXECUTION_GOVERNANCE_ROOM_v38]]`n- [[41_GIT_FREEZE_AUTOMATION_LEAN_MODE_v12]]`n- [[40_STRATEGIC_PARTNERSHIP_PILOT_PROPOSAL_ROOM_v37]]`n`n## Painel rapido SenseTrust`n`n- Estado: v3.9 simulated_only metadata_only human_review_required.`n- Escopo: monitoramento simulado e intake de evidencias.`n- Bloqueios: sem evidencia real, paciente, amostra biologica, EEG/qEEG, piloto real, contrato, cliente, parceria ou certificacao diagnostica.`n`n## Links obrigatorios`n`n- [[_LAST_SYNC]]`n- [[MOC_SenseTrust]]`n- [[MEMORY_MANIFEST]]`n- [[Supabase Execution Proof]]`n"
$SyncBody = "# _LAST_SYNC`n`n- updated: 2026-06-19`n- module: SenseTrust`n- latest: [[43_STRATEGIC_PILOT_MONITORING_EVIDENCE_INTAKE_ROOM_v39]]`n- latest_main: [[SenseTrust Strategic Pilot Monitoring Evidence Intake Room v3.9]]`n- base: [[42_STRATEGIC_PILOT_EXECUTION_GOVERNANCE_ROOM_v38]]`n- next: v4.0 closeout_ready preparation`n"
$ManifestBody = "# MEMORY_MANIFEST`n`n- Vault ID: $VaultId`n- Canonical vault: $VaultRoot`n- Latest SenseTrust note: [[43_STRATEGIC_PILOT_MONITORING_EVIDENCE_INTAKE_ROOM_v39]]`n- Latest SenseTrust main note: [[SenseTrust Strategic Pilot Monitoring Evidence Intake Room v3.9]]`n"
$ManifestJsonBody = @{ vault_id = $VaultId; latest_sensetrust_note = "43_STRATEGIC_PILOT_MONITORING_EVIDENCE_INTAKE_ROOM_v39"; latest_sensetrust_main_note = $SprintTitle; updated = "2026-06-19"; status = "simulated_only_metadata_only_human_review_required"; next = "v4.0 closeout_ready preparation" } | ConvertTo-Json -Depth 5
Write-Note $QuickNote $QuickBody; Write-Note $MainNote $MainBody; Write-Note $RootNote $RootBody; Write-Note $LastSync $SyncBody; Write-Note $Manifest $ManifestBody; Write-Note $ManifestJson $ManifestJsonBody
foreach ($moc in $Mocs) { $full = Join-Path $VaultRoot $moc; Ensure-Parent $moc; if (Test-Path $full) { $current = Get-Content -Raw -Path $full } else { $current = "# " + [IO.Path]::GetFileNameWithoutExtension($moc) + "`n" }; if ($current -notmatch "43_STRATEGIC_PILOT_MONITORING_EVIDENCE_INTAKE_ROOM_v39") { $current = $current.TrimEnd() + "`n`n## SenseTrust v3.9`n`n- [[43_STRATEGIC_PILOT_MONITORING_EVIDENCE_INTAKE_ROOM_v39]]`n- [[SenseTrust Strategic Pilot Monitoring Evidence Intake Room v3.9]]`n" }; Set-Content -Path $full -Value $current -Encoding UTF8 }
Write-Output "Obsidian SenseTrust v3.9 atualizado em $VaultRoot"
