$ErrorActionPreference = "Stop"
$VaultRoot = "C:\Users\User\OneDrive\Documentos\PROJETO SAAS OFICIAL"; $VaultId = "projeto-saas-oficial"; $SprintTitle = "SenseTrust Demo Distribution Partner Presentation Kit v4.4"
$SenseTrustRoot = "06_COMMAND_CENTER\SenseTrust"
$QuickNote = "$SenseTrustRoot\00_ABRIR_SENSETRUST\48_DEMO_DISTRIBUTION_PARTNER_PRESENTATION_KIT_v44.md"; $MainNote = "$SenseTrustRoot\05_SENSETRUST\$SprintTitle.md"; $RootNote = "$SenseTrustRoot\00_ABRIR_ULTIMA_NOTA_SENSETRUST.md"; $LastSync = "$SenseTrustRoot\00_MEMORY_INDEX\_LAST_SYNC.md"; $Manifest = "$SenseTrustRoot\00_MEMORY_INDEX\MEMORY_MANIFEST.md"; $ManifestJson = "$SenseTrustRoot\00_MEMORY_INDEX\MEMORY_MANIFEST.json"
$Mocs = @("$SenseTrustRoot\05_SENSETRUST\MOC_SenseTrust.md","$SenseTrustRoot\05_SENSETRUST\MOC_VitalStrata_SenseTrust.md","$SenseTrustRoot\05_SENSETRUST\MOC_NeuroStrata_Trust_Layer.md","$SenseTrustRoot\05_SENSETRUST\MOC_DNDA_Trust_Object.md","$SenseTrustRoot\05_SENSETRUST\MOC_BLC_Rastreabilidade.md")
if (!(Test-Path $VaultRoot)) { throw "Raiz canonica do Projeto SaaS Oficial nao encontrada: $VaultRoot" }
foreach ($folder in @("01_SEGUNDO_CEREBRO","02_DOCUMENTOS","03_SISTEMA","04_CLINICAL_RESTRICTED","05_CASE_ADAPTA","06_COMMAND_CENTER","06_COMMAND_CENTER\SenseTrust")) {
  $folderPath = Join-Path $VaultRoot $folder
  if (!(Test-Path $folderPath)) { New-Item -ItemType Directory -Force -Path $folderPath | Out-Null }
}
function Ensure-Parent($RelativePath) { $full = Join-Path $VaultRoot $RelativePath; $parent = Split-Path $full -Parent; if (!(Test-Path $parent)) { New-Item -ItemType Directory -Force -Path $parent | Out-Null } }
function Write-Note($RelativePath, $Body) { Ensure-Parent $RelativePath; Set-Content -Path (Join-Path $VaultRoot $RelativePath) -Value $Body -Encoding UTF8 }
$Frontmatter = "---`nvault_id: $VaultId`ncanonical_root: C:\Users\User\OneDrive\Documentos\PROJETO SAAS OFICIAL`ncanonical_area: 06_COMMAND_CENTER/SenseTrust`ntype: sensetrust_demo_distribution_partner_presentation_kit`nmodule: SenseTrust`nversion: v4.4`nstatus: simulated_only`ntrust_status: metadata_only`ncreated_by: Codex`ncreated: 2026-06-19`nupdated: 2026-06-19`nlinked_sprint: SenseTrust v4.4 Demo Distribution Partner Presentation Kit`ntags:`n  - SenseTrust`n  - SenseTrust/v4.4`n  - SenseTrust/DemoDistribution`n  - SenseTrust/PartnerPresentationKit`n  - SenseTrust/PilotOS`n  - SenseTrust/ReleaseCandidate`n  - SenseTrust/CommandCenter`n  - SenseTrust/DemoPreparation`n  - SenseTrust/ClaimsMatrix`n  - SenseTrust/LeanFreeze`n  - MetadataOnly`n  - SimulatedOnly`n  - HumanReviewRequired`n  - DemoDistributionOnly`n  - PartnerPresentationOnly`n  - ReleaseCandidateLinked`n  - Neurodireitos`n  - LGPD`n  - Obsidian/NATE`n---"
$Statement = "A SenseTrust v4.4 nao executa operacao real, nao envia comunicacao real, nao formaliza parceria e nao certifica resultado clinico, cientifico, regulatorio ou comercial. Ela organiza um Demo Distribution / Partner Presentation Kit simulado, auditavel e supervisionado, reunindo narrativa institucional, materiais autorizados, roteiro de demonstracao, audience packs, guardrails, matriz de claims e preparacao para revisao humana."
$QuickBody = "$Frontmatter`n# 48_DEMO_DISTRIBUTION_PARTNER_PRESENTATION_KIT_v44`n`n[[SenseTrust Demo Distribution Partner Presentation Kit v4.4]]`n`n$Statement`n`n- [[47_PILOT_OS_RELEASE_CANDIDATE_v43]]`n- [[46_COMMAND_CENTER_INTEGRATION_v42]]`n- [[45_INSTITUTIONAL_HANDOFF_ROOM_v41]]`n- [[44_STRATEGIC_PILOT_OUTCOME_CLOSEOUT_DECISION_ROOM_v40]]`n- [[43_STRATEGIC_PILOT_MONITORING_EVIDENCE_INTAKE_ROOM_v39]]`n- [[42_STRATEGIC_PILOT_EXECUTION_GOVERNANCE_ROOM_v38]]`n- [[41_GIT_FREEZE_AUTOMATION_LEAN_MODE_v12]]`n- [[40_STRATEGIC_PARTNERSHIP_PILOT_PROPOSAL_ROOM_v37]]`n"
$MainBody = "$Frontmatter`n# $SprintTitle`n`n$Statement`n`nDNDA significa Diagnóstico Neurofuncional Dimensional Auditável. Guardrails: simulated_only, metadata_only, human_review_required, demo_distribution_only, partner_presentation_only, release_candidate_linked. Preparacao v4.5 Partner Feedback / Meeting Intelligence apenas simulada.`n"
$RootBody = "$Frontmatter`n# ABRIR ULTIMA NOTA SENSETRUST`n`n- [[48_DEMO_DISTRIBUTION_PARTNER_PRESENTATION_KIT_v44]]`n- [[SenseTrust Demo Distribution Partner Presentation Kit v4.4]]`n- [[47_PILOT_OS_RELEASE_CANDIDATE_v43]]`n- [[46_COMMAND_CENTER_INTEGRATION_v42]]`n- [[45_INSTITUTIONAL_HANDOFF_ROOM_v41]]`n- [[44_STRATEGIC_PILOT_OUTCOME_CLOSEOUT_DECISION_ROOM_v40]]`n- [[43_STRATEGIC_PILOT_MONITORING_EVIDENCE_INTAKE_ROOM_v39]]`n- [[42_STRATEGIC_PILOT_EXECUTION_GOVERNANCE_ROOM_v38]]`n- [[41_GIT_FREEZE_AUTOMATION_LEAN_MODE_v12]]`n- [[40_STRATEGIC_PARTNERSHIP_PILOT_PROPOSAL_ROOM_v37]]`n"
$SyncBody = "# _LAST_SYNC`n`n- updated: 2026-06-19`n- canonical_root: $VaultRoot`n- canonical_area: 06_COMMAND_CENTER/SenseTrust`n- latest: [[48_DEMO_DISTRIBUTION_PARTNER_PRESENTATION_KIT_v44]]`n- latest_main: [[SenseTrust Demo Distribution Partner Presentation Kit v4.4]]`n- next: v4.5 partner feedback meeting intelligence preparation`n"
$ManifestBody = "# MEMORY_MANIFEST`n`n- Vault ID: $VaultId`n- Canonical root: $VaultRoot`n- Canonical SenseTrust area: 06_COMMAND_CENTER/SenseTrust`n- Latest SenseTrust note: [[48_DEMO_DISTRIBUTION_PARTNER_PRESENTATION_KIT_v44]]`n"
$ManifestJsonBody = @{ vault_id = $VaultId; canonical_root = $VaultRoot; canonical_area = "06_COMMAND_CENTER/SenseTrust"; latest_sensetrust_note = "48_DEMO_DISTRIBUTION_PARTNER_PRESENTATION_KIT_v44"; latest_sensetrust_main_note = $SprintTitle; updated = "2026-06-19"; status = "simulated_only_metadata_only_human_review_required_demo_distribution_only" } | ConvertTo-Json -Depth 5
Write-Note $QuickNote $QuickBody; Write-Note $MainNote $MainBody; Write-Note $RootNote $RootBody; Write-Note $LastSync $SyncBody; Write-Note $Manifest $ManifestBody; Write-Note $ManifestJson $ManifestJsonBody
foreach ($moc in $Mocs) { $full = Join-Path $VaultRoot $moc; Ensure-Parent $moc; if (Test-Path $full) { $current = Get-Content -Raw -Path $full } else { $current = "# " + [IO.Path]::GetFileNameWithoutExtension($moc) + "`n" }; if ($current -notmatch "48_DEMO_DISTRIBUTION_PARTNER_PRESENTATION_KIT_v44") { $current = $current.TrimEnd() + "`n`n## SenseTrust v4.4`n`n- [[48_DEMO_DISTRIBUTION_PARTNER_PRESENTATION_KIT_v44]]`n- [[SenseTrust Demo Distribution Partner Presentation Kit v4.4]]`n" }; Set-Content -Path $full -Value $current -Encoding UTF8 }
Write-Output "Obsidian SenseTrust v4.4 script ready for $VaultRoot\06_COMMAND_CENTER\SenseTrust"
