$ErrorActionPreference = "Stop"
$VaultRoot = "C:\Users\User\Documents\NEURO DASH SKIP\VitalStrata_OS"; $VaultId = "b1a32fcb40985ffc"; $SprintTitle = "SenseTrust Institutional Handoff Room v4.1"
$QuickNote = "00_ABRIR_SENSETRUST\45_INSTITUTIONAL_HANDOFF_ROOM_v41.md"; $MainNote = "05_SENSETRUST\$SprintTitle.md"; $RootNote = "00_ABRIR_ULTIMA_NOTA_SENSETRUST.md"; $LastSync = "00_MEMORY_INDEX\_LAST_SYNC.md"; $Manifest = "00_MEMORY_INDEX\MEMORY_MANIFEST.md"; $ManifestJson = "00_MEMORY_INDEX\MEMORY_MANIFEST.json"; $Moc = "05_SENSETRUST\MOC_SenseTrust.md"
if (!(Test-Path (Join-Path $VaultRoot ".obsidian"))) { throw "Vault Obsidian canonico nao encontrado: $VaultRoot" }
function Ensure-Parent($RelativePath) { $full = Join-Path $VaultRoot $RelativePath; $parent = Split-Path $full -Parent; if (!(Test-Path $parent)) { New-Item -ItemType Directory -Force -Path $parent | Out-Null } }
function Write-Note($RelativePath, $Body) { Ensure-Parent $RelativePath; Set-Content -Path (Join-Path $VaultRoot $RelativePath) -Value $Body -Encoding UTF8 }
$Tags = @("SenseTrust","SenseTrust/v4.1","SenseTrust/InstitutionalHandoff","SenseTrust/HandoffPreparation","SenseTrust/HumanReview","SenseTrust/BoundaryClaims","SenseTrust/LeanFreeze","SenseTrust/v4.0","SenseTrust/v3.9","SenseTrust/v3.8","SenseTrust/v3.7","SenseTrust/DNDA","SenseTrust/VitalStrata","SenseTrust/NeuroStrata","MetadataOnly","SimulatedOnly","HumanReviewRequired","Neurodireitos","LGPD","Obsidian/NATE")
$TagsYaml = ($Tags | ForEach-Object { "  - $_" }) -join "`n"
$Frontmatter = "---`nvault_id: $VaultId`ntype: sensetrust_institutional_handoff_room`nmodule: SenseTrust`nversion: v4.1`nstatus: simulated_only`ntrust_status: metadata_only`ncreated_by: Codex`ncreated: 2026-06-19`nupdated: 2026-06-19`nlinked_sprint: SenseTrust v4.1 Institutional Handoff Room`ntags:`n$TagsYaml`n---"
$Statement = "A SenseTrust v4.1 nao formaliza parceria, nao executa operacao real e nao certifica resultado clinico, cientifico, regulatorio ou comercial. Ela organiza um handoff institucional simulado, auditavel e supervisionado, preparando materiais, responsabilidades, evidencias, decisoes e guardrails para revisao humana."
$QuickBody = "$Frontmatter`n# 45_INSTITUTIONAL_HANDOFF_ROOM_v41`n`n[[SenseTrust Institutional Handoff Room v4.1]]`n`n## Regra operacional`n`n$Statement`n`n## Links`n`n- [[44_STRATEGIC_PILOT_OUTCOME_CLOSEOUT_DECISION_ROOM_v40]]`n- [[43_STRATEGIC_PILOT_MONITORING_EVIDENCE_INTAKE_ROOM_v39]]`n- [[42_STRATEGIC_PILOT_EXECUTION_GOVERNANCE_ROOM_v38]]`n- [[41_GIT_FREEZE_AUTOMATION_LEAN_MODE_v12]]`n- [[MOC_SenseTrust]]`n"
$MainBody = "$Frontmatter`n# $SprintTitle`n`n$Statement`n`nDNDA significa Diagnóstico Neurofuncional Dimensional Auditável. Guardrails: simulated_only, metadata_only, human_review_required, handoff_preparation_only, sem dado clinico real, paciente, amostra biologica, EEG/qEEG, cliente, contrato, parceria, billing, CRM, email real, assinatura legal ou certificacao diagnostica.`n"
$RootBody = "$Frontmatter`n# ABRIR ULTIMA NOTA SENSETRUST`n`n- [[45_INSTITUTIONAL_HANDOFF_ROOM_v41]]`n- [[SenseTrust Institutional Handoff Room v4.1]]`n- [[44_STRATEGIC_PILOT_OUTCOME_CLOSEOUT_DECISION_ROOM_v40]]`n- [[43_STRATEGIC_PILOT_MONITORING_EVIDENCE_INTAKE_ROOM_v39]]`n- [[42_STRATEGIC_PILOT_EXECUTION_GOVERNANCE_ROOM_v38]]`n- [[41_GIT_FREEZE_AUTOMATION_LEAN_MODE_v12]]`n"
$SyncBody = "# _LAST_SYNC`n`n- updated: 2026-06-19`n- module: SenseTrust`n- latest: [[45_INSTITUTIONAL_HANDOFF_ROOM_v41]]`n- latest_main: [[SenseTrust Institutional Handoff Room v4.1]]`n- base: [[44_STRATEGIC_PILOT_OUTCOME_CLOSEOUT_DECISION_ROOM_v40]]`n"
$ManifestBody = "# MEMORY_MANIFEST`n`n- Vault ID: $VaultId`n- Latest SenseTrust note: [[45_INSTITUTIONAL_HANDOFF_ROOM_v41]]`n"
$ManifestJsonBody = @{ vault_id = $VaultId; latest_sensetrust_note = "45_INSTITUTIONAL_HANDOFF_ROOM_v41"; latest_sensetrust_main_note = $SprintTitle; updated = "2026-06-19"; status = "simulated_only_metadata_only_human_review_required_handoff_preparation_only" } | ConvertTo-Json -Depth 5
Write-Note $QuickNote $QuickBody; Write-Note $MainNote $MainBody; Write-Note $RootNote $RootBody; Write-Note $LastSync $SyncBody; Write-Note $Manifest $ManifestBody; Write-Note $ManifestJson $ManifestJsonBody
$mocFull = Join-Path $VaultRoot $Moc; Ensure-Parent $Moc; if (Test-Path $mocFull) { $current = Get-Content -Raw -Path $mocFull } else { $current = "# MOC_SenseTrust`n" }; if ($current -notmatch "45_INSTITUTIONAL_HANDOFF_ROOM_v41") { $current = $current.TrimEnd() + "`n`n## SenseTrust v4.1`n`n- [[45_INSTITUTIONAL_HANDOFF_ROOM_v41]]`n- [[SenseTrust Institutional Handoff Room v4.1]]`n" }; Set-Content -Path $mocFull -Value $current -Encoding UTF8
Write-Output "Obsidian SenseTrust v4.1 script ready for $VaultRoot"
