$ErrorActionPreference = "Stop"
$VaultRoot = "C:\Users\User\Documents\NEURO DASH SKIP\VitalStrata_OS"; $VaultId = "b1a32fcb40985ffc"; $SprintTitle = "SenseTrust Command Center Integration v4.2"
$QuickNote = "00_ABRIR_SENSETRUST\46_COMMAND_CENTER_INTEGRATION_v42.md"; $MainNote = "05_SENSETRUST\$SprintTitle.md"; $RootNote = "00_ABRIR_ULTIMA_NOTA_SENSETRUST.md"; $LastSync = "00_MEMORY_INDEX\_LAST_SYNC.md"; $Manifest = "00_MEMORY_INDEX\MEMORY_MANIFEST.md"; $ManifestJson = "00_MEMORY_INDEX\MEMORY_MANIFEST.json"
$Mocs = @("05_SENSETRUST\MOC_SenseTrust.md","05_SENSETRUST\MOC_VitalStrata_SenseTrust.md","05_SENSETRUST\MOC_NeuroStrata_Trust_Layer.md","05_SENSETRUST\MOC_DNDA_Trust_Object.md","05_SENSETRUST\MOC_BLC_Rastreabilidade.md")
if (!(Test-Path (Join-Path $VaultRoot ".obsidian"))) { throw "Vault Obsidian canonico nao encontrado: $VaultRoot" }
function Ensure-Parent($RelativePath) { $full = Join-Path $VaultRoot $RelativePath; $parent = Split-Path $full -Parent; if (!(Test-Path $parent)) { New-Item -ItemType Directory -Force -Path $parent | Out-Null } }
function Write-Note($RelativePath, $Body) { Ensure-Parent $RelativePath; Set-Content -Path (Join-Path $VaultRoot $RelativePath) -Value $Body -Encoding UTF8 }
$Tags = @("SenseTrust","SenseTrust/v4.2","SenseTrust/CommandCenter","SenseTrust/Integration","SenseTrust/ExecutiveDashboard","SenseTrust/DemoPreparation","SenseTrust/ReleaseCandidatePreparation","SenseTrust/ProofChain","SenseTrust/VersionTrail","SenseTrust/Handoff","SenseTrust/LeanFreeze","SenseTrust/v4.1","SenseTrust/v4.0","SenseTrust/v3.9","SenseTrust/v3.8","SenseTrust/v3.7","SenseTrust/v1.2","SenseTrust/TrustLayer","SenseTrust/DNDA","SenseTrust/VitalStrata","SenseTrust/NeuroStrata","SenseTrust/BLC","NeuroStrata/TrustLayer","VitalStrata/SaaS","DNDA/Auditavel","BLC/Rastreabilidade","MetadataOnly","SimulatedOnly","HumanReviewRequired","Neurodireitos","LGPD","Obsidian/NATE")
$TagsYaml = ($Tags | ForEach-Object { "  - $_" }) -join "`n"
$Frontmatter = "---`nvault_id: $VaultId`ntype: sensetrust_command_center_integration`nmodule: SenseTrust`nversion: v4.2`nstatus: simulated_only`ntrust_status: metadata_only`ncreated_by: Codex`ncreated: 2026-06-19`nupdated: 2026-06-19`nlinked_sprint: SenseTrust v4.2 Command Center Integration`ntags:`n$TagsYaml`n---"
$Statement = "A SenseTrust v4.2 nao executa operacao real, nao formaliza parceria e nao certifica resultado clinico, cientifico, regulatorio ou comercial. Ela integra visualmente a trilha simulada da SenseTrust, organizando navegacao, status, evidencias, riscos, guardrails e handoff institucional para revisao humana e demonstracao controlada."
$QuickBody = "$Frontmatter`n# 46_COMMAND_CENTER_INTEGRATION_v42`n`n[[SenseTrust Command Center Integration v4.2]]`n`n## Regra operacional`n`n$Statement`n`n## Links`n`n- [[45_INSTITUTIONAL_HANDOFF_ROOM_v41]]`n- [[44_STRATEGIC_PILOT_OUTCOME_CLOSEOUT_DECISION_ROOM_v40]]`n- [[43_STRATEGIC_PILOT_MONITORING_EVIDENCE_INTAKE_ROOM_v39]]`n- [[42_STRATEGIC_PILOT_EXECUTION_GOVERNANCE_ROOM_v38]]`n- [[41_GIT_FREEZE_AUTOMATION_LEAN_MODE_v12]]`n- [[40_STRATEGIC_PARTNERSHIP_PILOT_PROPOSAL_ROOM_v37]]`n"
$MainBody = "$Frontmatter`n# $SprintTitle`n`n$Statement`n`nDNDA significa Diagnóstico Neurofuncional Dimensional Auditável. Guardrails: simulated_only, metadata_only, human_review_required, command_center_only, demo_preparation_only, sem dado clinico real, paciente, amostra biologica, EEG/qEEG, cliente, contrato, parceria, billing, CRM, email real, assinatura legal ou certificacao diagnostica. Preparacao v4.3 release candidate.`n"
$RootBody = "$Frontmatter`n# ABRIR ULTIMA NOTA SENSETRUST`n`n- [[46_COMMAND_CENTER_INTEGRATION_v42]]`n- [[SenseTrust Command Center Integration v4.2]]`n- [[45_INSTITUTIONAL_HANDOFF_ROOM_v41]]`n- [[44_STRATEGIC_PILOT_OUTCOME_CLOSEOUT_DECISION_ROOM_v40]]`n- [[43_STRATEGIC_PILOT_MONITORING_EVIDENCE_INTAKE_ROOM_v39]]`n- [[42_STRATEGIC_PILOT_EXECUTION_GOVERNANCE_ROOM_v38]]`n- [[41_GIT_FREEZE_AUTOMATION_LEAN_MODE_v12]]`n- [[40_STRATEGIC_PARTNERSHIP_PILOT_PROPOSAL_ROOM_v37]]`n"
$SyncBody = "# _LAST_SYNC`n`n- updated: 2026-06-19`n- module: SenseTrust`n- latest: [[46_COMMAND_CENTER_INTEGRATION_v42]]`n- latest_main: [[SenseTrust Command Center Integration v4.2]]`n- base: [[45_INSTITUTIONAL_HANDOFF_ROOM_v41]]`n- next: v4.3 release candidate preparation`n"
$ManifestBody = "# MEMORY_MANIFEST`n`n- Vault ID: $VaultId`n- Latest SenseTrust note: [[46_COMMAND_CENTER_INTEGRATION_v42]]`n"
$ManifestJsonBody = @{ vault_id = $VaultId; latest_sensetrust_note = "46_COMMAND_CENTER_INTEGRATION_v42"; latest_sensetrust_main_note = $SprintTitle; updated = "2026-06-19"; status = "simulated_only_metadata_only_human_review_required_command_center_only_demo_preparation_only"; next = "v4.3 release candidate preparation" } | ConvertTo-Json -Depth 5
Write-Note $QuickNote $QuickBody; Write-Note $MainNote $MainBody; Write-Note $RootNote $RootBody; Write-Note $LastSync $SyncBody; Write-Note $Manifest $ManifestBody; Write-Note $ManifestJson $ManifestJsonBody
foreach ($moc in $Mocs) { $full = Join-Path $VaultRoot $moc; Ensure-Parent $moc; if (Test-Path $full) { $current = Get-Content -Raw -Path $full } else { $current = "# " + [IO.Path]::GetFileNameWithoutExtension($moc) + "`n" }; if ($current -notmatch "46_COMMAND_CENTER_INTEGRATION_v42") { $current = $current.TrimEnd() + "`n`n## SenseTrust v4.2`n`n- [[46_COMMAND_CENTER_INTEGRATION_v42]]`n- [[SenseTrust Command Center Integration v4.2]]`n" }; Set-Content -Path $full -Value $current -Encoding UTF8 }
Write-Output "Obsidian SenseTrust v4.2 script ready for $VaultRoot"
