$ErrorActionPreference = "Stop"
$VaultRoot = "C:\Users\User\Documents\NEURO DASH SKIP\VitalStrata_OS"; $VaultId = "b1a32fcb40985ffc"; $SprintTitle = "SenseTrust Strategic Pilot Outcome Closeout Decision Room v4.0"
$QuickNote = "00_ABRIR_SENSETRUST\44_STRATEGIC_PILOT_OUTCOME_CLOSEOUT_DECISION_ROOM_v40.md"; $MainNote = "05_SENSETRUST\$SprintTitle.md"; $RootNote = "00_ABRIR_ULTIMA_NOTA_SENSETRUST.md"; $LastSync = "00_MEMORY_INDEX\_LAST_SYNC.md"; $Manifest = "00_MEMORY_INDEX\MEMORY_MANIFEST.md"; $ManifestJson = "00_MEMORY_INDEX\MEMORY_MANIFEST.json"
$Mocs = @("05_SENSETRUST\MOC_SenseTrust.md","05_SENSETRUST\MOC_VitalStrata_SenseTrust.md","05_SENSETRUST\MOC_NeuroStrata_Trust_Layer.md","05_SENSETRUST\MOC_DNDA_Trust_Object.md","05_SENSETRUST\MOC_BLC_Rastreabilidade.md")
if (!(Test-Path (Join-Path $VaultRoot ".obsidian"))) { throw "Vault Obsidian canonico nao encontrado: $VaultRoot" }
function Ensure-Parent($RelativePath) { $full = Join-Path $VaultRoot $RelativePath; $parent = Split-Path $full -Parent; if (!(Test-Path $parent)) { New-Item -ItemType Directory -Force -Path $parent | Out-Null } }
function Write-Note($RelativePath, $Body) { Ensure-Parent $RelativePath; Set-Content -Path (Join-Path $VaultRoot $RelativePath) -Value $Body -Encoding UTF8 }
$Tags = @("SenseTrust","SenseTrust/v4.0","SenseTrust/StrategicPilotOutcome","SenseTrust/Closeout","SenseTrust/DecisionRoom","SenseTrust/LearningLoop","SenseTrust/HandoffPreparation","SenseTrust/OutcomeSynthesis","SenseTrust/EvidenceSynthesis","SenseTrust/HumanReview","SenseTrust/DecisionBoard","SenseTrust/BoundaryClaims","SenseTrust/LeanFreeze","SenseTrust/v1.2","SenseTrust/v3.9","SenseTrust/v3.8","SenseTrust/v3.7","SenseTrust/TrustLayer","SenseTrust/DNDA","SenseTrust/VitalStrata","SenseTrust/NeuroStrata","SenseTrust/BLC","NeuroStrata/TrustLayer","VitalStrata/SaaS","DNDA/Auditavel","BLC/Rastreabilidade","MetadataOnly","SimulatedOnly","HumanReviewRequired","Neurodireitos","LGPD","Obsidian/NATE")
$TagsYaml = ($Tags | ForEach-Object { "  - $_" }) -join "`n"
$Frontmatter = "---`nvault_id: $VaultId`ntype: sensetrust_strategic_pilot_outcome_closeout_decision_room`nmodule: SenseTrust`nversion: v4.0`nstatus: simulated_only`ntrust_status: metadata_only`ncreated_by: Codex`ncreated: 2026-06-19`nupdated: 2026-06-19`nlinked_sprint: SenseTrust v4.0 Strategic Pilot Outcome Closeout Decision Room`ntags:`n$TagsYaml`n---"
$Statement = "A SenseTrust v4.0 nao certifica resultado clinico, cientifico, regulatorio ou comercial. Ela consolida um fechamento simulado, auditavel e supervisionado de piloto institucional, organizando evidencias, riscos, desvios, aprendizados e decisao humana Go/Pause/Refine/Stop."
$QuickBody = "$Frontmatter`n# 44_STRATEGIC_PILOT_OUTCOME_CLOSEOUT_DECISION_ROOM_v40`n`n[[SenseTrust Strategic Pilot Outcome Closeout Decision Room v4.0]]`n`n## Painel rapido`n`n- Closeout simulado.`n- Outcome synthesis metadata_only.`n- Decision board Go/Pause/Refine/Stop.`n- Preparacao explicita para v4.1 institutional handoff.`n`n## Regra operacional`n`n$Statement`n`n## Links`n`n- [[43_STRATEGIC_PILOT_MONITORING_EVIDENCE_INTAKE_ROOM_v39]]`n- [[42_STRATEGIC_PILOT_EXECUTION_GOVERNANCE_ROOM_v38]]`n- [[41_GIT_FREEZE_AUTOMATION_LEAN_MODE_v12]]`n- [[40_STRATEGIC_PARTNERSHIP_PILOT_PROPOSAL_ROOM_v37]]`n- [[_LAST_SYNC]]`n- [[MOC_SenseTrust]]`n- [[MEMORY_MANIFEST]]`n"
$MainBody = "$Frontmatter`n# $SprintTitle`n`n$Statement`n`n## Governanca`n`nA sala conecta v3.9, v3.8, v3.7 e Lean Freeze v1.2 para organizar closeout, evidence synthesis, learning loop, decision board, boundary claims e v4.1 institutional handoff preparation. DNDA significa Diagnóstico Neurofuncional Dimensional Auditável.`n`n## Limites`n`nmetadata_only, simulated_only, human_review_required, handoff_preparation_only, LGPD, neurodireitos, sem dado clinico real, sem paciente real, sem amostra biologica real, sem EEG/qEEG real, sem outcome real, sem piloto real, sem contrato, cliente, parceria ou certificacao diagnostica.`n"
$RootBody = "$Frontmatter`n# ABRIR ULTIMA NOTA SENSETRUST`n`n## Ultima nota`n`n- [[44_STRATEGIC_PILOT_OUTCOME_CLOSEOUT_DECISION_ROOM_v40]]`n- [[SenseTrust Strategic Pilot Outcome Closeout Decision Room v4.0]]`n- [[43_STRATEGIC_PILOT_MONITORING_EVIDENCE_INTAKE_ROOM_v39]]`n- [[42_STRATEGIC_PILOT_EXECUTION_GOVERNANCE_ROOM_v38]]`n- [[41_GIT_FREEZE_AUTOMATION_LEAN_MODE_v12]]`n- [[40_STRATEGIC_PARTNERSHIP_PILOT_PROPOSAL_ROOM_v37]]`n`n## Painel rapido SenseTrust`n`n- Estado: v4.0 simulated_only metadata_only human_review_required handoff_preparation_only.`n- Escopo: closeout simulado, outcome synthesis e decisao humana.`n- Bloqueios: sem outcome real, piloto real, paciente, amostra biologica, EEG/qEEG, contrato, cliente, parceria ou certificacao diagnostica.`n`n## Links obrigatorios`n`n- [[_LAST_SYNC]]`n- [[MOC_SenseTrust]]`n- [[MEMORY_MANIFEST]]`n- [[Supabase Execution Proof]]`n"
$SyncBody = "# _LAST_SYNC`n`n- updated: 2026-06-19`n- module: SenseTrust`n- latest: [[44_STRATEGIC_PILOT_OUTCOME_CLOSEOUT_DECISION_ROOM_v40]]`n- latest_main: [[SenseTrust Strategic Pilot Outcome Closeout Decision Room v4.0]]`n- base: [[43_STRATEGIC_PILOT_MONITORING_EVIDENCE_INTAKE_ROOM_v39]]`n- next: v4.1 institutional handoff preparation`n"
$ManifestBody = "# MEMORY_MANIFEST`n`n- Vault ID: $VaultId`n- Canonical vault: $VaultRoot`n- Latest SenseTrust note: [[44_STRATEGIC_PILOT_OUTCOME_CLOSEOUT_DECISION_ROOM_v40]]`n- Latest SenseTrust main note: [[SenseTrust Strategic Pilot Outcome Closeout Decision Room v4.0]]`n"
$ManifestJsonBody = @{ vault_id = $VaultId; latest_sensetrust_note = "44_STRATEGIC_PILOT_OUTCOME_CLOSEOUT_DECISION_ROOM_v40"; latest_sensetrust_main_note = $SprintTitle; updated = "2026-06-19"; status = "simulated_only_metadata_only_human_review_required_handoff_preparation_only"; next = "v4.1 institutional handoff preparation" } | ConvertTo-Json -Depth 5
Write-Note $QuickNote $QuickBody; Write-Note $MainNote $MainBody; Write-Note $RootNote $RootBody; Write-Note $LastSync $SyncBody; Write-Note $Manifest $ManifestBody; Write-Note $ManifestJson $ManifestJsonBody
foreach ($moc in $Mocs) { $full = Join-Path $VaultRoot $moc; Ensure-Parent $moc; if (Test-Path $full) { $current = Get-Content -Raw -Path $full } else { $current = "# " + [IO.Path]::GetFileNameWithoutExtension($moc) + "`n" }; if ($current -notmatch "44_STRATEGIC_PILOT_OUTCOME_CLOSEOUT_DECISION_ROOM_v40") { $current = $current.TrimEnd() + "`n`n## SenseTrust v4.0`n`n- [[44_STRATEGIC_PILOT_OUTCOME_CLOSEOUT_DECISION_ROOM_v40]]`n- [[SenseTrust Strategic Pilot Outcome Closeout Decision Room v4.0]]`n" }; Set-Content -Path $full -Value $current -Encoding UTF8 }
Write-Output "Obsidian SenseTrust v4.0 atualizado em $VaultRoot"
