import type { SenseTrustInstitutionalReadinessScaleGateState } from '@/types/sensetrust/institutional-readiness-scale-gate'

export function InstitutionalReadinessScaleGateDashboard({ state }: { state: SenseTrustInstitutionalReadinessScaleGateState }) {
  const readiness = Math.round(state.readiness_gates.reduce((sum, item) => sum + item.v3_readiness_score, 0) / state.readiness_gates.length)
  const market = Math.round(state.readiness_gates.reduce((sum, item) => sum + item.market_priority_score, 0) / state.readiness_gates.length)
  const regulatory = Math.round(state.readiness_gates.reduce((sum, item) => sum + item.regulatory_readiness_score, 0) / state.readiness_gates.length)
  const risk = Math.round(state.readiness_gates.reduce((sum, item) => sum + item.institutional_risk_score, 0) / state.readiness_gates.length)
  const guardrails = ['metadata_only', 'no clinical data', 'no patient data', 'no contract', 'no client', 'no partnership', 'no regulatory authorization', 'no diagnostic truth certification']
  return <section className="rounded-md border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xl font-black text-slate-950">SenseTrust Institutional Readiness & Strategic Scale Gate v3.0</p><p className="text-sm font-semibold uppercase tracking-wide text-emerald-700">readiness / scale gate / governance / simulated_only</p></div><span className="rounded-md bg-rose-50 px-3 py-1 text-xs font-black text-rose-700">no binding scale decision</span></div><div className="mt-4 grid gap-3 sm:grid-cols-6"><Metric label="readiness" value={readiness} suffix="%" /><Metric label="scale gates" value={state.strategic_scale_gates.length} /><Metric label="decisoes" value={state.scale_decisions.length} /><Metric label="mercado" value={market} suffix="%" /><Metric label="regulatorio" value={regulatory} suffix="%" /><Metric label="risco" value={risk} suffix="%" /></div><div className="mt-4 flex flex-wrap gap-2">{guardrails.map((item) => <span key={item} className="rounded bg-slate-100 px-2 py-1 text-xs font-bold uppercase text-slate-700">{item}</span>)}</div></section>
}
function Metric({ label, value, suffix = '' }: { label: string; value: number; suffix?: string }) { return <div className="rounded-md bg-slate-50 p-3"><p className="text-xs font-semibold uppercase text-slate-500">{label}</p><p className="mt-1 font-mono text-xl font-black text-slate-950">{value}{suffix}</p></div> }
