import type { SenseTrustInstitutionalPilotCloseoutState } from '@/types/sensetrust/institutional-pilot-closeout'

export function InstitutionalPilotCloseoutDashboard({ state }: { state: SenseTrustInstitutionalPilotCloseoutState }) {
  const maturity = Math.round(state.institutional_maturity_matrices.reduce((sum, item) => sum + item.score, 0) / state.institutional_maturity_matrices.length)
  const v3 = Math.round(state.v3_readiness_matrices.reduce((sum, item) => sum + item.readiness_score, 0) / state.v3_readiness_matrices.length)
  const regulatoryRisk = state.regulatory_pending_items.filter((item) => item.risk_level === 'critical' || item.risk_level === 'high').length
  const guardrails = ['metadata_only', 'no clinical data', 'no patient data', 'no legal binding', 'no regulatory authorization', 'no clinical outcome claim', 'no diagnostic truth certification']
  return <section className="rounded-md border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xl font-black text-slate-950">SenseTrust Institutional Pilot Closeout v2.8</p><p className="text-sm font-semibold uppercase tracking-wide text-emerald-700">closeout / learning loop / v3 readiness / metadata_only</p></div><span className="rounded-md bg-rose-50 px-3 py-1 text-xs font-black text-rose-700">no binding closeout</span></div><div className="mt-4 grid gap-3 sm:grid-cols-6"><Metric label="closeouts" value={state.closeout_reports.length} /><Metric label="aprendizados" value={state.learning_loop_items.length} /><Metric label="decisoes" value={state.closeout_decisions.length} /><Metric label="maturidade" value={maturity} suffix="%" /><Metric label="v3 ready" value={v3} suffix="%" /><Metric label="risco reg." value={regulatoryRisk} /></div><div className="mt-4 flex flex-wrap gap-2">{guardrails.map((item) => <span key={item} className="rounded bg-slate-100 px-2 py-1 text-xs font-bold uppercase text-slate-700">{item}</span>)}</div></section>
}
function Metric({ label, value, suffix = '' }: { label: string; value: number; suffix?: string }) { return <div className="rounded-md bg-slate-50 p-3"><p className="text-xs font-semibold uppercase text-slate-500">{label}</p><p className="mt-1 font-mono text-xl font-black text-slate-950">{value}{suffix}</p></div> }
