import type { SenseTrustStrategicScaleSimulationConsoleState } from '@/types/sensetrust/strategic-scale-simulation-console'

export function StrategicScaleSimulationConsoleDashboard({ state }: { state: SenseTrustStrategicScaleSimulationConsoleState }) {
  const readiness = Math.round(state.readiness_score_simulations.reduce((sum, item) => sum + item.aggregate_score, 0) / state.readiness_score_simulations.length)
  const impactItems = state.institutional_impact_items.length
  const capacityItems = state.operational_capacity_items.length
  const guardrails = ['metadata_only', 'no clinical data', 'no patient data', 'no contract', 'no client', 'no partnership', 'no regulatory authorization', 'no diagnostic truth certification', 'no real impact claim', 'no real capacity claim']
  return <section className="rounded-md border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xl font-black text-slate-950">SenseTrust Strategic Scale Simulation Console v3.2</p><p className="text-sm font-semibold uppercase tracking-wide text-emerald-700">scenario simulation / impact / capacity / risk / human review</p></div><span className="rounded-md bg-rose-50 px-3 py-1 text-xs font-black text-rose-700">no real measured impact</span></div><div className="mt-4 grid gap-3 sm:grid-cols-6"><Metric label="consoles" value={state.simulation_consoles.length} /><Metric label="cenarios" value={state.scenarios.length} /><Metric label="readiness" value={readiness} suffix="%" /><Metric label="impactos" value={impactItems} /><Metric label="capacidade" value={capacityItems} /><Metric label="riscos" value={state.scale_risk_items.length} /></div><div className="mt-4 flex flex-wrap gap-2">{guardrails.map((item) => <span key={item} className="rounded bg-slate-100 px-2 py-1 text-xs font-bold uppercase text-slate-700">{item}</span>)}</div></section>
}
function Metric({ label, value, suffix = '' }: { label: string; value: number; suffix?: string }) { return <div className="rounded-md bg-slate-50 p-3"><p className="text-xs font-semibold uppercase text-slate-500">{label}</p><p className="mt-1 font-mono text-xl font-black text-slate-950">{value}{suffix}</p></div> }
