import type { SenseTrustStrategicPartnershipPilotProposalRoomState } from '@/types/sensetrust/strategic-partnership-pilot-proposal-room'

export function StrategicPartnershipPilotProposalRoomDashboard({ state }: { state: SenseTrustStrategicPartnershipPilotProposalRoomState }) {
  const avgScope = Math.round(state.candidates.reduce((sum, item) => sum + item.non_binding_scope_score, 0) / state.candidates.length)
  const reviews = state.legal_review_items.length + state.scientific_review_items.length + state.regulatory_review_items.length + state.human_review_items.length
  const guardrails = ['metadata_only', 'no clinical data', 'no binding proposal', 'no LOI', 'no MOU', 'human review', 'legal review']
  return <section className="rounded-md border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xl font-black text-slate-950">SenseTrust Strategic Partnership Pilot Proposal Room v3.7</p><p className="text-sm font-semibold uppercase tracking-wide text-emerald-700">non-binding scope / value hypothesis / entry-exit criteria / review queues</p></div><span className="rounded-md bg-rose-50 px-3 py-1 text-xs font-black text-rose-700">non-binding only</span></div><div className="mt-4 grid gap-3 sm:grid-cols-6"><Metric label="rooms" value={state.rooms.length} /><Metric label="candidates" value={state.candidates.length} /><Metric label="scope" value={state.scope_matrix_items.length} /><Metric label="evidence" value={state.evidence_items.length} /><Metric label="reviews" value={reviews} /><Metric label="scope score" value={avgScope} suffix="%" /></div><div className="mt-4 flex flex-wrap gap-2">{guardrails.map((item) => <span key={item} className="rounded bg-slate-100 px-2 py-1 text-xs font-bold uppercase text-slate-700">{item}</span>)}</div></section>
}

function Metric({ label, value, suffix = '' }: { label: string; value: number; suffix?: string }) { return <div className="rounded-md bg-slate-50 p-3"><p className="text-xs font-semibold uppercase text-slate-500">{label}</p><p className="mt-1 font-mono text-xl font-black text-slate-950">{value}{suffix}</p></div> }
