import type { SenseTrustStrategicScaleOperatingModelState } from '@/types/sensetrust/strategic-scale-operating-model'

export function StrategicScaleOperatingModelDashboard({ state }: { state: SenseTrustStrategicScaleOperatingModelState }) {
  const readiness = Math.round(state.readiness_scorecards.reduce((sum, item) => sum + item.operating_readiness_score, 0) / state.readiness_scorecards.length)
  const cadence = Math.round(state.readiness_scorecards.reduce((sum, item) => sum + item.cadence_coverage_score, 0) / state.readiness_scorecards.length)
  const raci = Math.round(state.readiness_scorecards.reduce((sum, item) => sum + item.raci_completeness_score, 0) / state.readiness_scorecards.length)
  const human = Math.round(state.readiness_scorecards.reduce((sum, item) => sum + item.human_review_score, 0) / state.readiness_scorecards.length)
  const guardrails = ['metadata_only', 'no clinical data', 'no patient data', 'no contract', 'no client', 'no partnership', 'no regulatory authorization', 'no diagnostic truth certification']
  return <section className="rounded-md border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xl font-black text-slate-950">SenseTrust Strategic Scale Operating Model v3.1</p><p className="text-sm font-semibold uppercase tracking-wide text-emerald-700">operating model / cadence / RACI / human review / simulated_only</p></div><span className="rounded-md bg-rose-50 px-3 py-1 text-xs font-black text-rose-700">no real operation</span></div><div className="mt-4 grid gap-3 sm:grid-cols-6"><Metric label="models" value={state.operating_models.length} /><Metric label="cadence" value={cadence} suffix="%" /><Metric label="RACI" value={raci} suffix="%" /><Metric label="risks" value={state.risk_items.length} /><Metric label="human" value={human} suffix="%" /><Metric label="ready" value={readiness} suffix="%" /></div><div className="mt-4 flex flex-wrap gap-2">{guardrails.map((item) => <span key={item} className="rounded bg-slate-100 px-2 py-1 text-xs font-bold uppercase text-slate-700">{item}</span>)}</div></section>
}
function Metric({ label, value, suffix = '' }: { label: string; value: number; suffix?: string }) { return <div className="rounded-md bg-slate-50 p-3"><p className="text-xs font-semibold uppercase text-slate-500">{label}</p><p className="mt-1 font-mono text-xl font-black text-slate-950">{value}{suffix}</p></div> }
