import type { SenseTrustStrategicPartnerEngagementControlRoomState } from '@/types/sensetrust/strategic-partner-engagement-control-room'

export function StrategicPartnerEngagementControlRoomDashboard({ state }: { state: SenseTrustStrategicPartnerEngagementControlRoomState }) {
  const average = Math.round(state.engagement_readiness_scores.reduce((sum, item) => sum + item.aggregate_score, 0) / state.engagement_readiness_scores.length)
  const guardrails = ['metadata_only', 'no patient data', 'no contract', 'no client', 'no partnership', 'no CRM', 'no real email', 'no regulatory validation', 'no scientific validation']
  return <section className="rounded-md border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xl font-black text-slate-950">SenseTrust Strategic Partner Engagement Control Room v3.5</p><p className="text-sm font-semibold uppercase tracking-wide text-emerald-700">tracks / ledger / meeting simulation / responses / follow-up / human review</p></div><span className="rounded-md bg-rose-50 px-3 py-1 text-xs font-black text-rose-700">no CRM or real email</span></div><div className="mt-4 grid gap-3 sm:grid-cols-6"><Metric label="rooms" value={state.rooms.length} /><Metric label="tracks" value={state.tracks.length} /><Metric label="ledger" value={state.interaction_ledger_items.length} /><Metric label="risks" value={state.engagement_risk_items.length} /><Metric label="guardrails" value={state.boundary_claims_guardrail_items.length} /><Metric label="readiness" value={average} suffix="%" /></div><div className="mt-4 flex flex-wrap gap-2">{guardrails.map((item) => <span key={item} className="rounded bg-slate-100 px-2 py-1 text-xs font-bold uppercase text-slate-700">{item}</span>)}</div></section>
}

function Metric({ label, value, suffix = '' }: { label: string; value: number; suffix?: string }) { return <div className="rounded-md bg-slate-50 p-3"><p className="text-xs font-semibold uppercase text-slate-500">{label}</p><p className="mt-1 font-mono text-xl font-black text-slate-950">{value}{suffix}</p></div> }
